[bitnami/mongodb-sharded] Use common helper to manage app secrets
bitnami/charts pull request #10828
Opened 2022-06-21 09:49 UTC by joancafom

### Description of the change

Use the `common.secrets.passwords.manage` helper to prevent app secrets from being regenerated during an upgrade process.

### Benefits

- Passwords are reused during the upgrade process
- New pods can join the cluster without issues

### Possible drawbacks

None

### Applicable issues

  - fixes #10771 

### Additional information

NA

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-06-22 15:22 UTC, FraPazGal approved these changes
LGTM

2022-07-14 07:58 UTC, gongomgra approved these changes
LGTM!

2022-07-14 07:59 UTC, migruiz4 approved these changes
LGTM!

2022-07-14 08:00 UTC, gongomgra requested changes

2022-07-14 08:00 UTC, gongomgra commented on bitnami/mongodb-sharded/Chart.yaml
> -version: 5.0.17
why not 5.1.0?

2022-07-14 08:01 UTC, migruiz4 approved these changes

2022-07-14 08:01 UTC, gongomgra approved these changes

2022-07-14 08:19 UTC, merged