[bitnami/thanos] Creates separate service for grpc port of query module
bitnami/charts pull request #11051
Opened 2022-07-05 22:25 UTC by felippe-mendonca

Signed-off-by: Felippe Mendonça <mendonca.felippe@gmail.com>

### Description of the change

As previously discussed at https://github.com/bitnami/charts/issues/11028, this PR creates a separate Kubernetes Service for Thanos Query gRPC port. 

### Benefits

Having a separate gRPC service, will be possible to configure this Service with specific annotations in order to make gRPC Ingress works, such as Traefik 2.0.

### Possible drawbacks

### Applicable issues

  - fixes https://github.com/bitnami/charts/issues/11028

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-07-08 16:01 UTC, fmulero requested changes
Thanks a lot @felippe-mendonca I looks very well, I have only two little suggestions. Could you have it a look?

2022-07-08 16:01 UTC, fmulero commented on bitnami/thanos/templates/query/service-grpc-headless.yaml
> +    - port: {{ if .Values.query.service.grpc }}{{ coalesce .Values.query.service.ports.grpc .Values.query.service.grpc.port }}{{ else }}{{ .Values.query.service.ports.grpc }}{{ end }}
Typo here and I think we can simplify:
```suggestion
    - port: {{ .Values.query.serviceGrpc.ports.grpc }}
```

2022-07-08 16:41 UTC, felippe-mendonca commented
> Thanks a lot @felippe-mendonca I looks very well, I have only two little suggestions. Could you have it a look?

Hey @fmulero! Thanks for your review, I've accept the suggested changes!

2022-07-08 20:50 UTC, felippe-mendonca commented on bitnami/thanos/templates/query/service.yaml
> +    - port: {{ $query.service.ports.http }}
@fmulero also changed here, removing the backward compatibility config

2022-07-12 10:22 UTC, fmulero submitted a review, later dismissed
LGTM, Well done!. I am going to run some more tests, if everything goes well your PR will be merge by bitnami-bot.

2022-07-12 13:15 UTC, merged