[bitnami/keycloak] make metrics scrape target configurable
bitnami/charts pull request #11124
Opened 2022-07-11 07:39 UTC by tamcore

### Description of the change

This change will allow the scrape path to be configurable, as `/metrics` will only work, if `httpRelativePath` is set to `/`

### Benefits

Monitoring will work if `httpRelativePath` set to a non-default value.

### Possible drawbacks

### Applicable issues

  - fixes #

### Additional information

```
keycloak@keycloak-2:/$ curl -s http://localhost:8080/metrics; echo
<html><body><h1>Resource not found</h1></body></html>

keycloak@keycloak-2:/$ curl -s http://localhost:8080/auth/metrics | head -n1; echo
# HELP base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the Java virtual machine.

```
### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-07-12 08:57 UTC, javsalgar reviewed
Thank you so much for the PR!

2022-07-12 08:57 UTC, javsalgar commented on bitnami/keycloak/Chart.yaml
> +version: 9.4.1
Could you bump the minor version? It is adding a non-breaking feature

2022-07-14 09:41 UTC, javsalgar requested changes

2022-07-14 09:41 UTC, javsalgar commented on bitnami/keycloak/Chart.yaml
> +version: 9.5.1
Please change it to 9.5.0

2022-07-14 15:41 UTC, migruiz4 submitted a review, later dismissed
Looks good to me, thank you for your contribution!

2022-07-15 12:16 UTC, migruiz4 approved these changes

2022-07-18 10:47 UTC, carrodher approved these changes

2022-07-18 10:48 UTC, migruiz4 approved these changes
@carrodher, could you please merge this PR?
Changes requested by @javsalgar have been applied, but our current PR policy won't let me merge until he changes his review status (currently on PTO)

2022-07-18 10:50 UTC, merged