[bitnami/postgresql-ha] Add labels to volume claim template
bitnami/charts pull request #11225
Opened 2022-07-18 08:39 UTC by sl4dy

Allow addition of labels to volume claim template in the StatefulSet.

Signed-off-by: Milan Sladky <milan.sladky@sentinelone.com>

### Description of the change

Allow addition of labels to volume claim template in the StatefulSet.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-07-20 20:05 UTC, carrodher commented
Thanks for your PR, in order to make the GH actions work and to be able to verify the changes, could you rebase from `master`? Thank you

2022-07-21 14:06 UTC, sl4dy commented
@carrodher @fmulero rebased

2022-08-08 10:58 UTC, fmulero requested changes
Thanks a lot @sl4dy !!!

Sorry to be a little bit picky, but could you take a glance to my comment about the version? All the rest look perfect

2022-08-08 10:58 UTC, fmulero commented on bitnami/postgresql-ha/Chart.yaml
> +version: 9.2.9
We are adding a new feature, so according to [semver](https://semver.org/), we should release the version `9.3.0`

```suggestion
version: 9.3.0
```

2022-08-08 11:25 UTC, sl4dy commented
@fmulero done

2022-08-08 11:39 UTC, fmulero approved these changes
LGTM

2022-08-08 11:39 UTC, merged