[bitnami/spark] Add Spark Helm Chart tests
bitnami/charts pull request #11280
Opened 2022-07-20 15:16 UTC by mdhont

Signed-off-by: Michiel <michield@vmware.com>

### Description of the change

Add Goss and Cypress tests for the Bitnami Spark Helm Chart

Succesful runs:

https://github.com/mdhont/charts/actions/runs/2697956667
https://github.com/mdhont/charts/actions/runs/2702437703
https://github.com/mdhont/charts/actions/runs/2702521971

2022-07-20 19:46 UTC, carrodher requested changes
Changes in the README shouldn't be needed, the current heading is fine

2022-07-21 08:02 UTC, FraPazGal requested changes
Thanks for the PR @mdhont! I added a few comments on it, could you please check them?

I was also thinking about Cypress's usefulness here. If we are doing a couple of basic checks at `/`, could we migrate them to be done in goss via [goss.http](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#http)? If we can use goss, we could remove cypress and avoid doing another deployment for it.

2022-07-21 14:24 UTC, carrodher approved these changes
Changes in the README were removed that was the reason why I requested changes. Let's wait for the test experts review 😄

2022-07-22 11:15 UTC, agomezmoron commented on .vib/spark/cypress/cypress/integration/spark_spec.js
> +it('checks if the amount of workers is correct', () => {
I agree on @FraPazGal's thoughts. We should keep the **minimum number of tests** to ensure the integration works.

2022-07-22 11:17 UTC, agomezmoron commented on .vib/spark/goss/goss.yaml
> +    exec: cat /opt/bitnami/spark/RELEASE | grep "Spark $APP_VERSION"
I prefer this one because this will check spark-shell is installed and spark working too.

2022-07-22 11:17 UTC, agomezmoron commented on .vib/spark/goss/goss.yaml
> +  pyspark-ok:
I'd remove that too

2022-08-02 07:48 UTC, mdhont commented
@FraPazGal, I've made the changes you suggested but adapted the tests to the new test strategy as well.

2022-08-02 08:12 UTC, agomezmoron submitted a review, later dismissed
@mdhont now looks much better! LGTM

2022-08-02 10:45 UTC, FraPazGal reviewed
Hi @mdhont, I added a few more comments. Please check when possible.

Beside them, could you please remove the `Trivy` action from the vib pipelines? We are removing that action from the `bitnami/charts` repo. See: https://github.com/bitnami/charts/pull/11500

2022-08-02 10:45 UTC, FraPazGal commented on .vib/spark/cypress/cypress/integration/spark_spec.js
> +  const expectedWorkers = 2;
I think we should add  this via `Cypress.env`

2022-08-03 07:46 UTC, mdhont commented
Successful test run:

https://github.com/mdhont/charts/pull/7

2022-08-05 06:46 UTC, mdhont commented
Successful test run with the latest changes:

https://github.com/mdhont/charts/runs/7669909626

2022-08-05 12:30 UTC, FraPazGal approved these changes
LGTM! Thanks a lot for the PR @mdhont!

2022-08-05 14:24 UTC, agomezmoron approved these changes
LGTM

2022-08-05 14:46 UTC, merged