[bitnami/keycloak] remove Wildfly management port and secret key
bitnami/charts pull request #11326
Opened 2022-07-24 19:18 UTC by kherock

### Description of the change

Since Keycloak 17, there isn't any listener bound to port 9990, and the management password passed to the image isn't used. This PR removes all references to these obsoleted features.

### Benefits

See #11129

### Possible drawbacks

### Applicable issues

  - Closes #11129

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-08-01 14:42 UTC, kherock commented
Anything I can do to help move this along?

2022-08-01 15:07 UTC, migruiz4 commented
I'm sorry for the late response @kherock. 
The PR looks good to me, but could you please fix the branch conflicts and update the chart version at Chart.yaml?

bitnami/keycloak 9.6.1 has already been released

2022-08-01 15:13 UTC, migruiz4 requested changes

2022-08-01 15:13 UTC, migruiz4 commented on bitnami/keycloak/Chart.yaml
> +version: 9.6.1
```suggestion
version: 9.6.2
```

2022-08-03 13:53 UTC, kherock commented
Hey, I think this should be ready!

2022-08-03 14:10 UTC, migruiz4 commented
Hi @kherock,

The same issue happened again, version 9.6.2 has already been released, could you please rebase your branch and bump another version? 

Please @ me when done.

2022-08-03 15:02 UTC, kherock commented
@migruiz4

2022-08-04 07:46 UTC, migruiz4 approved these changes
Looks good to me, thank you for your contribution!

2022-08-04 07:46 UTC, merged