[bitnami/mysql] Create shared service for mysql
bitnami/charts pull request #11433
Opened 2022-07-30 08:57 UTC by nobiit

### Description of the change
Create a service that will include both primary and secondary

### Benefits
Separating primary and secondary is great if implemented. But sometimes they are not useful. For example, in an old application, only 1 URI could be specified for the database. Creating a service that includes both Primary and Secondary will be useful for that case

### Possible drawbacks
None

### Applicable issues
None

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-08-05 08:08 UTC, javsalgar commented
Thanks for the PR! Could you fix the merge issue?

2022-08-05 08:32 UTC, nobiit commented
Hey @javsalgar , I fixed the conflict. Can you review it again ?

2022-08-21 02:35 UTC, nobiit commented
Hey @javsalgar .Can you review it again ?

2022-08-23 11:26 UTC, javsalgar requested changes
Thank you! Minor change

2022-08-23 11:26 UTC, javsalgar commented on bitnami/mysql/Chart.yaml
> +version: 9.2.6
As it is adding a non-breaking feature, could you bump the minor version?

2022-09-14 01:34 UTC, closed without merging