[bitnami/keycloak] Added ability to toggle http port on k8s service
bitnami/charts pull request #11504
Opened 2022-08-02 12:14 UTC by andrewgkew

Signed-off-by: Andrew Kew <andrew@quadcorps.co.uk>

### Description of the change

Added the ability to toggle off the http port on k8s service. 

### Benefits

This is useful when running keycloak behind a load balancer and only wanting https path to be accessible 

### Possible drawbacks

No drawbacks as you can leave the default value (true) and it works as before

### Applicable issues

None

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-08-04 11:29 UTC, andrewgkew commented
@rafariossaa my PR keeps conflicting I assume when other merges bump the version (patch). I have bumped mine up a minor release version to  9.7.0 is this wrong?

2022-08-05 07:05 UTC, rafariossaa requested changes
Hi,
  This is ok. This repo has quite a bit of updates lately so sometimes you need to rebase several times you PR until it could be merged.

2022-08-05 07:05 UTC, rafariossaa commented on bitnami/keycloak/Chart.yaml
> +version: 9.7.0
Please, add a newline here.

2022-08-05 08:26 UTC, andrewgkew commented on bitnami/keycloak/Chart.yaml
> +version: 9.7.0
added

2022-08-05 12:08 UTC, andrewgkew commented
@rafariossaa I will continue to fix the merge conflicts as the version change. Can you let me know what else you need from me to get this merged please. i have tested the logic locally and it works really well. Thanks

2022-08-09 10:42 UTC, andrewgkew reviewed
have added new line to chart file

2022-08-12 08:52 UTC, andrewgkew commented
@joancafom just want to manage my expectation on when you think this PR might be looked at and hopefully merged :)

2022-08-19 10:04 UTC, joancafom reviewed
Hi @andrewgkew 

Sorry for the delay! I have added some comments of your changes, could you please take a look at them when you have a chance?

2022-08-19 10:04 UTC, joancafom commented on bitnami/keycloak/templates/service.yaml
> +    {{- if .Values.service.http.enabled }}
You also need to replicate this in `headless-service.yaml`

2022-08-19 13:36 UTC, andrewgkew commented on bitnami/keycloak/templates/service.yaml
> +    {{- if .Values.service.http.enabled }}
@joancafom - I hear what you saying about the new field, but to me, the http port is by default set to port 80
To then turn it off you would need to set

`
service:
  ports:
    http: ""
`
I dont find that very intuitive. Having to set something to empty to turn it off?

Actually thinking about it using auth.tls.enabled for the https port seems a little weird too as its meant to relate to the service itself, so maybe we need to be more specific in the service config (now that I think about it)

`
service:
  http:
    enabled: true
    port: 80

  tls:
    enabled: true
    port: 443

`
What do you think? I am not sure about unsetting one parameter that can turn it off, I would rather be specific about it?

Re: headless-service I will update that ones we have come to a decision on the above.

2022-09-05 15:31 UTC, andrewgkew commented
@marcosbc any movement on this PR?

2022-09-05 17:25 UTC, marcosbc approved these changes
LGTM! Thanks for the contribution! And sorry for the delay in checking this.

2022-09-05 17:25 UTC, merged