[bitnami/kafka] adding extra rules to jmx template
bitnami/charts pull request #11996
Opened 2022-08-22 17:45 UTC by davidballano

### Description of the change

Adding a config called extrarules that defauls to "" that will add extra jmx rules to jmx-configmap.yaml template

### Benefits

User will be able to add extra metrics to monitor Kafka from their values.yaml without having to either create a new configmap or modify the chart template jmx-configmap.yaml

### Possible drawbacks
There should not be any drawbacks, if the setting is not used the default rules will still apply.
### Applicable issues
NA

### Additional information
I couldnt get readme-generator-for-helm to work to generate the README

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-08-23 08:06 UTC, fmulero requested changes
Hi @davidballano. Thanks a lot for your contribution, it looks great!

I left some comments, Could you take them a look?

2022-08-23 15:50 UTC, davidballano commented on bitnami/kafka/values.yaml
> +    extrarules: ""
sure thing.

2022-08-23 15:54 UTC, davidballano commented on bitnami/kafka/Chart.yaml
> +version: 18.2.1
my mistake.

2022-08-25 08:45 UTC, fmulero approved these changes
Great!, LGTM. Thanks a lot @davidballano

2022-08-25 08:55 UTC, fmulero approved these changes

2022-08-25 08:59 UTC, merged