[bitnami/elasticsearch] Ability to add extraHosts
bitnami/charts pull request #12145
Opened 2022-08-24 20:35 UTC by arpitjindal97

**Description of the change**

Necessary if, 
 - You have another set of nodes that you want to introduce in this existing cluster.
 - Helps in migrating data to different K8s cluster by adding external data & master nodes
 - Extend an existing cluster running somewhere else

Parameter `extraHosts` is a list of manual configurable elasticsearch hosts.

**Benefits**
hosts list contains additional customizable items.

**Possible drawbacks**
N/A

**Applicable issues**
N/A

**Additional information**
N/A

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-08-26 17:41 UTC, marcosbc commented on bitnami/elasticsearch/Chart.yaml
> +version: 19.2.3
Since this is adding a new feature, could you increase the minor instead? I.e. to `19.3.0`.

2022-08-26 17:41 UTC, marcosbc requested changes
Thanks for the PR! Please have a look at my comment whenever you have a chance.

2022-09-01 17:20 UTC, arpitjindal97 commented
Do 'Rebase and Merge'

2022-09-05 08:22 UTC, marcosbc commented
Hi @arpitjindal97, sorry for the delay, could you rebase your branch on your side with the latest changes? If I do it, the DCO check would not succeed, unfortunately.

2022-09-06 08:43 UTC, arpitjindal97 commented
Done

2022-09-07 11:03 UTC, marcosbc approved these changes
LGTM! Thanks for the contribution!

2022-09-07 11:03 UTC, merged