[bitnami/elasticsearch]fix elasticsearch  envFrom
bitnami/charts pull request #12446
Opened 2022-09-15 15:32 UTC by wangguoyan

Signed-off-by: wangguoyan <717338097@qq.com>

### Description of the change
Values.data/coordinating.extraEnvVarsCM and Values.extraEnvVarsSecret is repeat effective for data/coordinating statefulset envFrom
Values.extraEnvVarsCM and Values.master.extraEnvVarsSecret is not effective for data/coordinating statefulset envFrom
replace one of Values.data/coordinating.extraEnvVarsCM with Values.extraEnvVarsCM on data/coordinating statefulset
replace one of Values.extraEnvVarsSecret with Values.data/coordinating.extraEnvVarsSecret on data/coordinating statefulset

### Benefits
Values.extraEnvVarsCM and Values.data/coordinating.extraEnvVarsSecret effect for data/coordinating. statefulset

### Possible drawbacks

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-10-05 04:36 UTC, wangguoyan commented
@corico44

2022-10-07 15:10 UTC, corico44 commented on bitnami/elasticsearch/Chart.yaml
> +version: 19.4.1
There is a version conflict. Update the version taking into account the current version of master.

2022-10-10 17:00 UTC, corico44 requested changes
Please, @wangguoyan, remove the first line indicating that you have signed the PR and remove the empty section titles such as **Possible drawbacks** and **Additional information**.

2022-10-11 11:18 UTC, corico44 approved these changes

2022-10-11 11:19 UTC, merged