[bitnami/tomcat] fix extraPodSpec bad indentation
bitnami/charts pull request #12464
Opened 2022-09-16 15:30 UTC by itscaro

### Description of the change

### Benefits

### Possible drawbacks

### Applicable issues

  - fixes #

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-10-07 15:11 UTC, corico44 commented on bitnami/tomcat/Chart.yaml
> +version: 10.4.4
There is a version conflict. Updates the version taking into account the current version of master.

2022-10-10 17:01 UTC, corico44 requested changes
Please, @itscaro , add more relevant info to the PR text.

2022-10-19 19:36 UTC, itscaro commented
@corico44 Added. thanks in advance

2022-10-21 15:10 UTC, corico44 approved these changes
LGTM!

2022-10-21 15:12 UTC, merged