[bitnami/cassandra] Use custom probes if given
bitnami/charts pull request #12483
Opened 2022-09-19 12:32 UTC by orgads

Without this change, in order to use a custom probe, the user has to
specify the probe parameters, and also must specify for the original
probe "enabled: false".

Issue: #12354

2022-09-20 13:52 UTC, migruiz4 requested changes
Hi @orgads, could you please update the chart version?
Other that that, the changes look good to me

2022-09-20 15:00 UTC, carrodher approved these changes

2022-09-20 19:21 UTC, orgads commented
Done

2022-09-20 21:31 UTC, carrodher approved these changes

2022-09-21 10:58 UTC, migruiz4 approved these changes

2022-09-21 10:58 UTC, merged