[bitnami/dokuwiki] Use custom probes if given
bitnami/charts pull request #12490
Opened 2022-09-19 13:14 UTC by orgads

Without this change, in order to use a custom probe, the user has to
specify the probe parameters, and also must specify for the original
probe "enabled: false".

Issue: #12354

2022-09-28 07:51 UTC, orgads commented
ping

2022-10-07 15:12 UTC, corico44 approved these changes
LGTM

2022-10-10 15:40 UTC, corico44 requested changes
The PR format is not correct.

2022-10-11 06:22 UTC, orgads commented
@corico44 I initially opened a PR for all the charts, in which I used the template. See #12374. But then I was asked to split it and create a PR for each chart.

Obviously, this is too much for manual work (96 charts), so I wrote a script that creates these PRs.

All the other charts are already merged, and nobody complained about the template.

Does it really matter? If you insist, I'll change it, but I really don't see the value here.

2022-10-17 07:35 UTC, corico44 commented
Seeing that other similar PRs with the same format have been accepted, this PR is also accepted.

2022-10-17 07:36 UTC, corico44 approved these changes

2022-10-17 07:44 UTC, merged