[bitnami/pytorch] Use custom probes if given
bitnami/charts pull request #12551
Opened 2022-09-19 13:28 UTC by orgads

Without this change, in order to use a custom probe, the user has to
specify the probe parameters, and also must specify for the original
probe "enabled: false".

Issue: #12354

2022-10-05 17:05 UTC, orgads commented
ping

2022-10-07 15:16 UTC, corico44 approved these changes
LGTM

2022-10-10 15:41 UTC, corico44 requested changes
Please, @orgads , modify the PR format since it is not correct. It should look something like this: https://github.com/bitnami/charts/pull/11297. When you try to create a new PR, GitHub gives you a template. Modify this PR using that format.

2022-10-17 07:46 UTC, corico44 approved these changes
Seeing that other similar PRs with the same format have been accepted, this PR is also accepted.

2022-10-17 07:47 UTC, merged