[bitname/external-dns] Support designate application credentials for external-dns
bitnami/charts pull request #12948
Opened 2022-10-13 16:42 UTC by baurmatt

### Description of the change

This change allows to configure OpenStack application credentials which are an alternative to username/password.

https://docs.openstack.org/keystone/queens/user/application_credentials.html

### Benefits

Use dedicated application credentials.

### Possible drawbacks

-

### Applicable issues

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-10-18 11:10 UTC, rafariossaa requested changes

2022-10-18 11:10 UTC, rafariossaa commented on bitnami/external-dns/README.md
> +| `designate.authType`                          | When using the Designate provider, specify the OpenStack auth type. (optional)
I guess `authType` should be in a new line and not overriding `username`

2022-10-18 11:10 UTC, rafariossaa commented on bitnami/external-dns/values.yaml
> +  ## @param designate.authType When using the Designate provider, specify the OpenStack auth type. (optional)
I guess `authType` should be in a new line and not overriding `username`

2022-10-18 11:13 UTC, rafariossaa commented
Could you take a look to my comments ?

2022-10-18 11:30 UTC, baurmatt commented
@rafariossaa Thanks for taking a look! :) The diff is only confusing. `username` was present twice in the documentation. See my first commit.

2022-10-19 08:12 UTC, rafariossaa commented
Sorry, I missed that.

2022-10-20 06:46 UTC, merged