[bitnami/minio] add commonLabels to standalone deployment template
bitnami/charts pull request #12962
Opened 2022-10-14 20:37 UTC by clearly-tyler-whitney

### Description of the change

Adds `commonLabels` to standalone MinIO `deployment.spec.template.spec.metadata` in the style of existing Bitnami charts.

### Benefits

### Possible drawbacks

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-10-20 08:18 UTC, migruiz4 requested changes
Hi @clearly-tyler-whitney,

Could you please bump the version of the chart to `11.10.9`? Version 11.10.8 was already released.

In addition, it would be great if you could apply the same change to the statefulset for 'distributed' mode.

2022-10-20 14:35 UTC, clearly-tyler-whitney commented on bitnami/minio/Chart.yaml
> +version: 11.10.8
Bumped to 11.10.10

2022-10-20 14:37 UTC, clearly-tyler-whitney commented
> Hi @clearly-tyler-whitney,
> 
> Could you please bump the version of the chart to `11.10.9`? Version 11.10.8 was already released.
> 
> In addition, it would be great if you could apply the same change to the statefulset for 'distributed' mode.

Gladly. Title updated.

2022-10-24 13:20 UTC, migruiz4 commented
Hi @clearly-tyler-whitney,

The commit https://github.com/bitnami/charts/pull/12962/commits/f4b55cb275715a22f571822aa575069065e79cd6 wasn't signed and is causing the DCO to fail. Could you please amend this issue?

2022-10-24 14:14 UTC, clearly-tyler-whitney commented
> Hi @clearly-tyler-whitney,
> 
> The commit [f4b55cb](https://github.com/bitnami/charts/commit/f4b55cb275715a22f571822aa575069065e79cd6) wasn't signed and is causing the DCO to fail. Could you please amend this issue?

Hi @migruiz4, the DCO issue has been addressed. Apologies for the hassle.

2022-10-24 14:44 UTC, migruiz4 approved these changes
Thank you very much! Looks good to me!

2022-10-24 14:44 UTC, merged