[bitnami/keycloak] Add support for custom infinispan/jgroups cache stacks (e.g. istio)
bitnami/charts pull request #13155
Opened 2022-10-26 13:46 UTC by dominikschlosser

### Description of the change

Add the possibility to use cache stacks beside the default 'kubernetes' one as well as additional ports used by those stacks.

### Benefits

The change allows the chart to be used in environments where infinispan discovery and communication does not work according to the standard kubernetes stack. This is the case, for example, in the context of the istio service mesh or even when a remote infinispan cluster is configured as cache store. Then additional port mappings and adjustments to the stack are required.

See https://www.keycloak.org/server/caching for caching-options supported out-of-the-box by keycloak.

### Possible drawbacks

None, as only optional parameters are added.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2022-10-27 09:03 UTC, carrodher commented
Thanks for creating this PR. Please note we just released a new major version of this Helm chart (https://github.com/bitnami/charts/pull/13103) so there are some conflicts appearing. Could you please resolve the conflicts?

2022-10-28 11:31 UTC, corico44 requested changes
There is a conflict related to the current keycloak version. Can you fix it, please?

2022-10-31 10:27 UTC, dominikschlosser commented
> There is a conflict related to the current keycloak version. Can you fix it, please?

Hey @corico44. i fixed the conflicts but can not resolve your requested changes in GH.

2022-11-02 10:51 UTC, corico44 approved these changes
LGTM!

2022-11-02 10:51 UTC, merged