[bitnami/contour] Adding CRDs for Contour 1.23
bitnami/charts pull request #13404
Opened 2022-11-08 10:28 UTC by langecode

### Description of the change

Upgrading CRDs to match Contour version 1.23

### Benefits

Allow for features of 1.23 to be used.

### Possible drawbacks

N/A

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

Signed-off-by: Thor Anker Kvisgård Lange <tal@netic.dk>

2022-11-11 09:32 UTC, jotamartos requested changes
Thanks your your contribution. I just added some comments for you to check

2022-11-11 09:32 UTC, jotamartos commented on bitnami/contour/Chart.yaml
> +version: 10.0.1
Please update the chart to 10.1.0. This adds new functionalities to the chart

2022-11-11 09:32 UTC, jotamartos commented on bitnami/contour/resources/contourconfiguration.yaml
> +---
Please remove this first line in all the files you edited.

2022-11-30 04:25 UTC, langecode commented
Bumb. Review comments implemented a while ago.

2022-11-30 15:35 UTC, jotamartos commented
Sorry for the delay, I didn't get any notification regarding your update. Changes LGTM but there are some conflicts now. Can you upgrade your base branch and resolve the conflicts? 

Thanks

2022-11-30 17:27 UTC, langecode commented
Yup, merged from upstream `main` now.

2022-12-01 10:05 UTC, jotamartos approved these changes

2022-12-01 10:05 UTC, merged