bitnami/spring-cloud-data-flow Fix for #13383
bitnami/charts pull request #13405
Opened 2022-11-08 10:29 UTC by juanpablo-santos

Signed-off-by: Juan Pablo Santos Rodríguez <juanpablo.santos@gmail.com>

### Description of the change
Provides a Fix for #13383, _Unable to set SPRING_APPLICATION_JSON env var_

### Benefits

will be able to set `SPRING_APPLICATION_JSON` through a values.yaml file

### Possible drawbacks

### Applicable issues

  - fixes #13383

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2022-11-09 14:07 UTC, migruiz4 requested changes
Hi @juanpablo-santos,

Thank you very much for your contribution, can you please take a look at my comment?

2022-11-11 17:52 UTC, juanpablo-santos commented on bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
>              {{- end }}
Hi @migruiz4 , thanks for your review :-) I've applied the suggested fix, so it should be ready to go

2022-11-11 18:19 UTC, juanpablo-santos commented on bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
>              {{- end }}
Also, just noticed that one of the cicd checks has failed after last commit, but not sure why. Surely the stack trace is self explanatory, but I'm relatively new to helm, so no clue :-?

2022-11-17 14:08 UTC, juanpablo-santos commented
closing this PR as it's no longer needed, #13383 already provides a solution for this.

2022-11-17 14:08 UTC, closed without merging