[bitnami/thanos] Set custom topology key for podAntiAffinityPreset
bitnami/charts pull request #13581
Opened 2022-11-18 11:06 UTC by alirezaDavid

Signed-off-by: Alireza Davoodi <alizdavoodi@gmail.com>

### Description of the change

Set custom topology key for podAntiAffinityPreset, e.g. `failure-domain.beta.kubernetes.io/zone`

Related MR:
https://github.com/bitnami/charts/pull/13435#issue-1442344820

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2022-11-18 15:51 UTC, carrodher commented
Thanks for the contribution. Please note the GH actions are failing due to the following error
```
ERROR: Missing metadata for key: query.podAntiAffinityPresetTopologyKey
```

That is because when a new parameter is added, you need to specify some metadata to render the table appearing in the README file. You can use any other parameter as example

2022-11-23 08:49 UTC, migruiz4 requested changes
Hi @alirezaDavid, thank you for your contribution! 
The changes look good to me, but I need to ask you to bump the chart version again since version 11.6.2 was already released.

2022-11-23 08:49 UTC, migruiz4 commented on bitnami/thanos/Chart.yaml
> +version: 11.6.2
Version `11.6.2` has been already released, could you please bump the chart version again? https://github.com/bitnami/charts/blob/main/bitnami/thanos/Chart.yaml

2022-11-24 07:02 UTC, migruiz4 approved these changes
Thank you for your contribution!

2022-11-24 07:23 UTC, merged