[bitnami/nginx] Fix failing git-repo-syncer container
bitnami/charts pull request #13948
Opened 2022-12-13 21:28 UTC by varac

### Description of the change

This fixes !13627, which tried to fix the initial git cloning but broke the subsequent git-repo-syncer container, because the /tmp/app/.git (and all other hidden files/dirs) were not moved to /app.

### Applicable issues

  - fixes !13627

### Additional information

With nginx chart 13.2.16 - 13.2.17, the git-repo-syncer container will fail with: 

        fatal: not a git repository (or any parent up to mount point /)
        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)
- [x] I tested the chart locally

Sorry for screwing up !13627 :pray:

2022-12-15 09:51 UTC, migruiz4 requested changes
Hi @varac,

Could you please take a look at my comment below?

2022-12-15 09:51 UTC, migruiz4 commented on bitnami/nginx/templates/deployment.yaml
>                [[ "$?" -eq 0 ]] && rm -rf /app/* && mv /tmp/app/* /app/
To be consistent with the `bitnami/apache` deployment template, could you please add it at the beginning and include the comment?

https://github.com/bitnami/charts/blob/73555a16d36e42d3301541abfc09b1810e2634c6/bitnami/apache/templates/deployment.yaml#L72-L80

```suggestion
            - |
              # Allow the mv to move hidden directories
              shopt -s dotglob
              [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source "/opt/bitnami/scripts/git/entrypoint.sh"
              git clone {{ .Values.cloneStaticSiteFromGit.repository }} --branch {{ .Values.cloneStaticSiteFromGit.branch }} /tmp/app
              [[ "$?" -eq 0 ]] && rm -rf /app/* && mv /tmp/app/* /app/
```

2022-12-15 20:29 UTC, varac commented
> Hi @varac,
> 
> Could you please take a look at my comment below?

@migruiz4 Done, is it ok like this ?

2022-12-19 14:24 UTC, migruiz4 commented
Hi @varac, 
I'm closing this PR as this issue was already addressed at https://github.com/bitnami/charts/pull/13969

2022-12-19 14:24 UTC, closed without merging