[bitnami/sonarqube] Close gap with upstream SonarQube Helm chart
bitnami/charts pull request #14252
Opened 2023-01-10 15:15 UTC by aoterolorenzo

Signed-off-by: Alberto Otero Lorenzo <lorenzoa@vmware.com>

### Description of the change

- [ ] Adds a feature in order to be able to install plugins from the chart
- [ ] Sets logic to include CACerts and parse them into SONARQUBE_WEB_JVM_OPTS and SONAR_CE_JAVAOPTS env vars

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-01-18 18:13 UTC, aoterolorenzo commented
Plugins provisioning working as expected with below values:

```
plugins:
  install: [ "https://github.com/AmadeusITGroup/sonar-stash/releases/download/1.3.0/sonar-stash-plugin-1.3.0.jar" ]
```

![Captura de Pantalla 2023-01-18 a las 18 49 45](https://user-images.githubusercontent.com/7276373/213260963-1c709b05-d6c2-4637-964f-531aa3c0f1bd.png)

![Captura de Pantalla 2023-01-18 a las 18 50 04](https://user-images.githubusercontent.com/7276373/213260997-44b0f979-f77c-49ce-9a09-fd375aa2e686.png)

2023-01-27 14:50 UTC, aoterolorenzo commented
Ready to review! 

Example values for using the new features (I just used as an example and for easy testing an injection of the Spanish institution FNMT root certificate):

```
extraDeploy:
  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ca-certs-secret
      namespace: default
    data:
      cert.cer: |-
        MIIFgzCCA2ugAwIBAgIPXZONMGc2yAYdGsdUhGkHMA0GCSqGSIb3DQEBCwUAMDsxCzAJBgNVBAYT
        AkVTMREwDwYDVQQKDAhGTk1ULVJDTTEZMBcGA1UECwwQQUMgUkFJWiBGTk1ULVJDTTAeFw0wODEw
        MjkxNTU5NTZaFw0zMDAxMDEwMDAwMDBaMDsxCzAJBgNVBAYTAkVTMREwDwYDVQQKDAhGTk1ULVJD
        TTEZMBcGA1UECwwQQUMgUkFJWiBGTk1ULVJDTTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
        ggIBALpxgHpMhm5/yBNtwMZ9HACXjywMI7sQmkCpGreHiPibVmr75nuOi5KOpyVdWRHbNi63URcf
        qQgfBBckWKo3Shjf5TnUV/3XwSyRAZHiItQDwFj8d0fsjz50Q7qsNI1NOHZnjrDIbzAzWHFctPVr
        btQBULgTfmxKo0nRIBnuvMApGGWn3v7v3QqQIecaZ5JCEJhfTzC8PhxFtBDXaEAUwED653cXeuYL
        j2VbPNmaUtu1vZ5Gzz3rkQUCwJaydkxNEJY7kvqcfw+Z374jNUUeAlz+taibmSXaXvMiwzn15Cou
        08YfxGyqxRxqAQVKL9LFwag0Jl1mpdICIfkYtwb1TplvqKtMUejPUBjFd8g5CSxJkjKZqLsXF3mw
        WsXmo8RZZUc1g16p6DULmbvkzSDGm0oGObVo/CK67lWMK07q87Hj/LaZmtVC+nFNCM+HHmpxffnT
        tOmlcYF7wk5HlqX2doWjKI/pgG6BU6VtX7hI+cL5NqYuSf+4lsKMB7ObiFj86xsc3i1w4peSMKGJ
        47xVqCfWS+2QrYv6YyVZLag13cqXM7zlzced0ezvXg5KkAYmY6252TUtB7p2ZSysV4999AeU14EC
        ll2jB0nVetBX+RvnU0Z1qrB5QstocQjpYL05ac70r8NWQMetUqIJ5G+GR4of6ygnXYMgrwTJbFaa
        i0b1AgMBAAGjgYMwgYAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
        FPd9xf3E6Jobd2Sn9R2gzL+HYJptMD4GA1UdIAQ3MDUwMwYEVR0gADArMCkGCCsGAQUFBwIBFh1o
        dHRwOi8vd3d3LmNlcnQuZm5tdC5lcy9kcGNzLzANBgkqhkiG9w0BAQsFAAOCAgEAB5BK3/MjTvDD
        nFFlm5wioooMhfNzKWtN/gHiqQxjAb8EZ6WdmF/9ARP67Jpi6Yb+tmLSbkyU+8B1RXxlDPiyN8+s
        D8+Nb/kZ94/sHvJwnvDKuO+3/3Y3dlv2bojzr2IyIpMNOmqOFGYMLVN0V2Ue1bLdI4E7pWYjJ2cJ
        j+F3qkPNZVEI7VFY/uY5+ctHhKQV8Xa7pO6kO8Rf77IzlhEYt8llvhjho6Tc+hj507wTmzl6NLrT
        Qfv6MooqtyuGC2mDOL7Nii4LcK2NJpLuHvUBKwrZ1pebbuCoGRw6IYsMHkCtA+fdZn71uSANA+iW
        +YJF1DngoABd15jmfZ5nc8OaKveri6E6FO80vFIOiZiaBECEHX5FaZNXzuvO+FB8TxxuBEOb+dY7
        Ixjp6o7RTUaN8Tvkasq6+yO3m/qZASlaWFot4/nUbQ4mrcFuNLwy+AwF+mWj2zs3gyLp1txyM/1d
        8iC9djwj2ij3+RvrWWTV3F9yfiD8zYm1kGdNYno/Tq0dwzn+evQoFt9B9kiABdcPUXmsEKvU7ANm
        5mqwujGSQkBqvjrTcuFqN1W8rB2Vt2lh8kORdOag0wokRqEIr9baRRmW1FMdW4R58MD3R++Lj8UG
        rp1MYp3/RgT408m2ECVAdf4WqslKYIYvuu8wd+RU4riEmViAqhOLUTpPSPaLtrM=
plugins:
  install: [ "https://github.com/AmadeusITGroup/sonar-stash/releases/download/1.6.0/sonar-stash-plugin-1.6.0.jar" ]
```

You can check if the certificate has been successful installed executing the following command on the sonarqube main pod CLI:

`echo changeit | keytool -list -v -keystore $(find $JAVA_HOME -name cacerts) | grep FNMT`

Ensuring the output is similar to:

```
Warning: use -cacerts option to access cacerts keystore
Enter keystore password:  Owner: OU=AC RAIZ FNMT-RCM, O=FNMT-RCM, C=ES
Issuer: OU=AC RAIZ FNMT-RCM, O=FNMT-RCM, C=ES
Owner: CN=AC RAIZ FNMT-RCM SERVIDORES SEGUROS, OID.2.5.4.97=VATES-Q2826004J, OU=Ceres, O=FNMT-RCM, C=ES
Issuer: CN=AC RAIZ FNMT-RCM SERVIDORES SEGUROS, OID.2.5.4.97=VATES-Q2826004J, OU=Ceres, O=FNMT-RCM, C=ES
```


Also, you can check the plugin provisioning through the CLI with the below command and output, or in the web interface accessible on port 80:

```
sonarqube@sonarqube-7467d6f7fb-b8xc9:/$ ls /opt/bitnami/sonarqube/extensions/plugins/
sonar-stash-plugin-1.6.0.jar
```

2023-02-02 09:27 UTC, carrodher commented on bitnami/sonarqube/templates/_helpers.tpl
> +
```suggestion
```

2023-02-02 09:27 UTC, carrodher commented on bitnami/sonarqube/values.yaml
> +provisioningFolder: "/bitnami/sonarqube-provisioning"
```suggestion
## @param provisioningFolder Directory to use for provisioning content to Sonarqube
##
provisioningFolder: "/bitnami/sonarqube-provisioning"
```

2023-02-02 09:27 UTC, carrodher commented on bitnami/sonarqube/values.yaml
> +  enabled: true
```suggestion
  ## @param caCerts.enabled Enable the use of caCerts
  ##
  enabled: true
```

2023-02-02 09:27 UTC, carrodher commented on bitnami/sonarqube/values.yaml
> +    tag: 11-debian-11-r63
Please note you need to define this container image in our internal test & release pipeline so the tag is automatically updated as the other images of this Helm chart

2023-02-02 09:27 UTC, carrodher commented on bitnami/sonarqube/values.yaml
> +  secret: ca-certs-secret
```suggestion
  ## @param caCerts.secret Name of the secret containing the certificates
  ##
  secret: ca-certs-secret
```

2023-02-02 09:27 UTC, carrodher commented on bitnami/sonarqube/values.yaml
> +  noCheckCertificate: true
```suggestion
  ## @param plugins.netrcCreds .netrc secret file with a key "netrc" to use basic auth while downloading plugins
  ##
  netrcCreds: ""
  ## @param plugins.noCheckCertificate Set to true to not validate the server's certificate to download plugin
  ##
  noCheckCertificate: true
```

2023-02-02 09:27 UTC, carrodher commented on bitnami/sonarqube/values.yaml
> +    tag: 11-debian-11-r63
Please note you need to define this container image in our internal test & release pipeline so the tag is automatically updated as the other images of this Helm chart

2023-02-09 10:19 UTC, javsalgar requested changes

2023-02-09 10:19 UTC, javsalgar commented on bitnami/sonarqube/templates/_helpers.tpl
> +
I see that this is being used only once. Aren't we actually creating more lines than necessary by creating a macro?

2023-02-09 10:19 UTC, javsalgar commented on bitnami/sonarqube/templates/_helpers.tpl
> +{{- define "sonarqube.installPlugins.configMap" -}}
Same here

2023-02-09 10:19 UTC, javsalgar commented on bitnami/sonarqube/templates/_helpers.tpl
> +    {{ printf "%s-install-plugins-initcontainer" (include "common.names.fullname" .) }}
Same here

2023-02-09 15:01 UTC, javsalgar approved these changes

2023-02-10 14:51 UTC, merged