[bitnami/keycloak] Fix NetworkPolicy to open the Infinispan port (7800)
bitnami/charts pull request #14576
Opened 2023-01-27 23:28 UTC by agtogna

### Description of the change

Open port 7800 in the NetworkPolicy to allow Infinispan cache traffic between pods.

### Benefits

Without port 7800 the pods Infinispan caches do not see each other, thus having a split cache (equivalent to local cache)

### Applicable issues

#14575 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-01-30 09:18 UTC, Mauraza commented
Hi @agtogna,

Thanks for the contribution!!
Did you try to add to the port in the [statefulset](ttps://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/statefulset.yaml) instead of the NetworkPolicy?

2023-01-30 10:36 UTC, agtogna commented
> Hi @agtogna,
> 
> Thanks for the contribution!! Did you try to add to the port in the statefulset instead of the NetworkPolicy?

Hello @Mauraza , I did not try it, however I don't think it would work since the 7800 port would still not be in the networkPolicy

2023-02-01 12:11 UTC, Mauraza commented
> Hello @Mauraza , I did not try it, however I don't think it would work since the 7800 port would still not be in the networkPolicy

But I think this needs to be in the statefulset.yaml too. 
Could you test if is working to add these values 🔽  to the ones you already have?
```yaml
extraContainerPorts: 
  - name: Infinispan
    containerPort: 7800
    protocol: TCP
service:
  extraPorts: 
    - name: Infinispan
      port: 7800
      targetPort: Infinispan
      protocol: TCP 
```

2023-02-02 14:44 UTC, agtogna commented
> 

Hello @Mauraza , I've tried adding both, but I still need to modify the network policy to allow traffic on port 7800/TCP.
By the way, I do not think adding the 7800 in the Service is a good idea: it should not be reachable as a service, should only be used by the pods to communicate between them.
I've only added the `extraContainerPorts` to my PR.

2023-02-03 09:36 UTC, Mauraza requested changes
Hi @agtogna,

Could you please check my comments?

2023-02-03 09:36 UTC, Mauraza commented on bitnami/keycloak/values.yaml
> +    protocol: TCP
This is not necessary to change. 
```suggestion
extraContainerPorts: []
```
You must add this part to the container port:
```yaml
containerPorts:
  http: 8080
  https: 8443
  infinispan: 7800
``` 
And in the satefulset.yaml:
```yaml
   ...
          ports:
          ...
            - name: infinispan
              containerPort: {{ .Values.containerPorts.infinispan }}
              protocol: TCP
...
```

2023-02-03 09:36 UTC, Mauraza commented on bitnami/keycloak/templates/networkpolicy.yaml
> +        - port: 7800
```suggestion
        - port: {{ .Values.containerPorts.infinispan }}
```

2023-02-03 09:36 UTC, Mauraza requested changes

2023-02-03 09:36 UTC, Mauraza commented on bitnami/keycloak/Chart.yaml
> +version: 13.0.4
```suggestion
version: 13.1.0
```

2023-02-08 08:57 UTC, Mauraza reviewed
Hi @agtogna,

The tests are failing for a little thing, could you update values.yaml?

2023-02-08 08:57 UTC, Mauraza commented on bitnami/keycloak/values.yaml
>  containerPorts:
The only this missing is updating the comments with the new port:
```yaml
## @param containerPorts.http Keycloak HTTP container port
## @param containerPorts.https Keycloak HTTPS container port
## @param containerPorts.infinispan Keycloak infinispan container port
```

2023-02-15 09:22 UTC, Mauraza commented
Hi @agtogna,

I missing port infinispan (7800) in statefulset.yaml
```yaml
.....
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
            {{- if .Values.tls.enabled }}
            - name: https
              containerPort: {{ .Values.containerPorts.https }}
              protocol: TCP
            {{- end }}
            - name: infinispan
              containerPort: {{ .Values.containerPorts.infinispan }}
              protocol: TCP
....
```

2023-02-16 11:38 UTC, Mauraza commented on bitnami/keycloak/README.md
> +
Sorry, Could you add this line? 
```suggestion
Specify each parameter using the `--set key=value[,key=value]` argument to `helm install`. For example,
```

2023-02-20 08:47 UTC, Mauraza approved these changes
Hi @agtogna,

Thanks for the contribution! LGTM!

2023-02-20 08:47 UTC, merged