Update health-configmap.yaml
bitnami/charts pull request #14934
Opened 2023-02-17 09:54 UTC by DevKhaverko

### Description of the change

### Benefits

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-02-17 16:06 UTC, marcosbc commented
@DevKhaverko Please add some more information to the PR, especially the context of the change and some explanations to understand why this is needed.

2023-02-19 06:14 UTC, DevKhaverko commented
@marcosbc added description

2023-02-20 15:10 UTC, marcosbc requested changes

2023-02-20 15:10 UTC, marcosbc commented on bitnami/redis/templates/health-configmap.yaml
> -{{- end }}
It seems like these options are removed, which allows for stuff like specifying a custom Redis port or SSL/TLS support. Could you re-add them?

2023-02-20 15:10 UTC, marcosbc commented on bitnami/redis/templates/health-configmap.yaml
> +    #!/usr/bin/env bash
In this base image, Bash is guaranteed to be located at:
```suggestion
    #!/bin/bash
```

2023-02-20 15:10 UTC, marcosbc commented on bitnami/redis/templates/health-configmap.yaml
> +        "${redis_cli[@]}" info replication 2>/dev/null | grep "role" | tr -d "\r" | tr -d "\n"
Isn't `redis info replication` specific to `--set architecture=replication` option for the chart (and not `standalone`)?

In addition, a small improvement that could be made:

```suggestion
        "${redis_cli[@]}" info replication 2>/dev/null | grep -Eo "^role:.*"
```

(please also apply this below)

2023-03-15 02:22 UTC, closed without merging