bitnami/spark NFS Support
bitnami/charts pull request #15294
Opened 2023-03-02 01:09 UTC by nicolas-g

### Description of the change

Updated Master and Worker StatefulSets manifest to enable NFS volume mount.
NFS server IP support is required so we can mount across different namespaces.

### Benefits

Multiple Spark deployments in different namespaces will be able to use the same NFS share volume.

### Possible drawbacks

NA

### Applicable issues

Since PVC is a namespace scoped, it limits you from mounting the same NFS share from workloads running in different namespaces.

### Additional information

NA

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-03-02 10:00 UTC, dgomezleon requested changes
Thanks for contributing. Please take a look at my suggestions.

2023-03-02 10:00 UTC, dgomezleon commented on bitnami/spark/values.yaml
> +
Use the same approach as the rest of the file:

* Uncomment the parameters.
* Add a comment like this `@param master.nfs_server_ip` for each of them.
* Run the [readme-generator](https://github.com/bitnami-labs/readme-generator-for-helm) after that.
Apart from that, don't place it in the middle of a section. For example, these lines are in the middle of `Container resource requests and limits`

2023-03-02 17:09 UTC, nicolas-g commented
Hi @dgomezleon , thank you for the guidance !

> Use the same approach as the rest of the file:
> 
> * Uncomment the parameters.
> * Add a comment like this `@param master.nfs_server_ip` for each of them.
done


> * Run the [readme-generator](https://github.com/bitnami-labs/readme-generator-for-helm) after that.

This is what I'm getting when running the binary:

```bash
 readme-generator-for-helm -v values.yaml -r README.md
Skipping check for metrics.masterAnnotations.prometheus.io/scrape
Skipping check for metrics.masterAnnotations.prometheus.io/path
Skipping check for metrics.masterAnnotations.prometheus.io/port
Skipping check for metrics.workerAnnotations.prometheus.io/scrape
Skipping check for metrics.workerAnnotations.prometheus.io/path
Skipping check for metrics.workerAnnotations.prometheus.io/port
INFO: Checking missing metadata...


######
The following errors must be fixed before proceeding
######


ERROR: Metadata provided for non existing key: master.nfs_server_ip
ERROR: Metadata provided for non existing key: master.nfs_server_path:
ERROR: Metadata provided for non existing key: master.nfs_mount_path:
ERROR: Metadata provided for non existing key: master.nfs_server_ip
ERROR: Metadata provided for non existing key: master.nfs_server_path:
ERROR: Metadata provided for non existing key: master.nfs_mount_path:
/snapshot/tmp/readme-generator-for-helm/lib/checker.js:93
    throw new Error('ERROR: Wrong metadata!');
    ^

Error: ERROR: Wrong metadata!
    at checkKeys (/snapshot/tmp/readme-generator-for-helm/lib/checker.js:93:11)
    at getParsedMetadata (/snapshot/tmp/readme-generator-for-helm/index.js:26:3)
    at runReadmeGenerator (/snapshot/tmp/readme-generator-for-helm/index.js:52:28)
    at Object.<anonymous> (/snapshot/tmp/readme-generator-for-helm/bin/index.js:22:1)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47
```

>   Apart from that, don't place it in the middle of a section. For example, these lines are in the middle of `Container resource requests and limits`

Can you point me to the exact line number where you want me to add these vars ?

2023-03-02 17:44 UTC, dgomezleon requested changes

2023-03-02 17:44 UTC, dgomezleon commented on bitnami/spark/values.yaml
> +
You need to include the parameter under the comment too:

```suggestion
  ## NFS
  ## @param master.nfs_server_ip Optionally specify the IP of NFS Server
  nfs_server_ip: ""
  ## @param master.nfs_server_path: Optionally specify the NFS server volume path (required if nfs_server_ip is defined)
  nfs_server_path: ""
  ## @param master.nfs_mount_path: Optionally specify the local path that will mount the NFS share volume (required if nfs_server_ip is defined)
  nfs_mount_path: ""
```

You could use line 280, under ` extraVolumeMounts: []`

2023-03-04 10:42 UTC, jouve commented
I think this should go in your release extraVolumes/extraVolumeMounts rather than the chart

2023-03-22 21:41 UTC, closed without merging