[bitnami/thanos]: add dnsConfig option
bitnami/charts pull request #15694
Opened 2023-03-22 20:05 UTC by antoinedeschenes

### Description of the change

Exposes dnsConfig settings on Thanos pod, allowing to set resolv.conf options.

### Benefits

Allows setting resolv.conf DNS options such as custom `nameservers`, `searches` or `options`. In this particular case we want to set the `ndots` option to reduce the number of DNS requests from `query`.

### Possible drawbacks

People sometimes use `dnsConfig` along `dnsPolicy`, but it's not being added.

### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-03-23 16:57 UTC, marcosbc requested changes
Thanks for the contribution! Please have a look at my request whenever you have a chance.

2023-03-23 16:57 UTC, marcosbc commented on bitnami/thanos/Chart.yaml
> +version: 12.3.2
Since this is adding a new feature, could you increase the minor?

2023-03-27 00:40 UTC, onedr0p approved these changes

2023-03-28 08:56 UTC, marcosbc approved these changes
LGTM, thanks!

2023-03-28 08:56 UTC, merged