[bitnami/jenkins] Removed double word from values.yaml
bitnami/charts pull request #16379
Opened 2023-05-04 12:27 UTC by DouweMeulenbroek

Removed a double 'be be' in the values.yaml
Just a cosmetic change in the description in the values.yaml. No technical changes.

### Description of the change

### Benefits

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-05-05 07:11 UTC, migruiz4 requested changes

2023-05-05 07:11 UTC, migruiz4 commented on bitnami/jenkins/Chart.yaml
> +version: 12.2.0
Could you please bump a patch version? `12.1.2` should be fine.

Our charts follow [semver](https://semver.org/) versioning: majors for non-backward compatible changes, minors for new features and capabilities, and patches for bug fixes.

2023-05-08 13:41 UTC, DouweMeulenbroek commented
Ofcourse, my appologies. I've changed the version number.

2023-05-08 18:54 UTC, carrodher commented
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

2023-05-29 02:22 UTC, closed without merging