[bitnami/minio] Use `mc quota` instead of old deprecated (removed) sy…
bitnami/charts pull request #16407
Opened 2023-05-05 13:39 UTC by sereinity

### Description of the change

Correctly (un)define quota limits with `mc` tools, the current code doesn't work with the current default version of minio loaded in the chart.

### Benefits

We can again set the quota, upgrades doesn't fail.

### Possible drawbacks

This code works with recent version of minio, but will not with older versions.

### Applicable issues

- fixes #16111 

### Additional information

 I defined a new keyword to set quota: `set` that does the same has `hard` but have a better matching with the `mc` arguments which will help users understand what it does (and need less cases in the template).

I added a special check on `hard` to keep the compatibility with older configuration (added on not about it being deprecated).

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-05-08 07:17 UTC, Mauraza requested changes
Hi @sereinity,

Thanks for the contribution!! Could you check my comments?

2023-05-08 07:17 UTC, Mauraza commented on bitnami/minio/Chart.yaml
> +version: 12.4.4
As you said is a breaking change so I think we should update a mayor version
```suggestion
version: 13.0.0
```

2023-05-15 11:49 UTC, Mauraza commented
Hi @sereinity,

Could you check the README.md? It seems there is an error with this part. 
Maybe [this](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#documentation-requirements) help.

2023-05-15 13:34 UTC, sereinity commented
> Hi @sereinity,
> 
> Could you check the README.md? It seems there is an error with this part. Maybe [this](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#documentation-requirements) help.

done

2023-05-15 14:02 UTC, Mauraza reviewed
On second thought, if it is not a breaking change, I think it makes more sense to have a minor because the same command is no longer executed.

With that change, we are ready to merge!

2023-05-15 14:02 UTC, Mauraza commented on bitnami/minio/Chart.yaml
> +version: 12.5.1
```suggestion
version: 12.6.0
```

2023-05-15 15:08 UTC, sereinity commented on bitnami/minio/Chart.yaml
> +version: 12.5.1
done

2023-05-15 15:25 UTC, Mauraza approved these changes
Hi @sereinity,

Thanks for the contribution!!! LGTM!

2023-05-15 15:25 UTC, merged