[bitnami/kubeapps] Switch Readiness check to grpc. Fix home URL
bitnami/charts pull request #16556
Opened 2023-05-10 06:07 UTC by absoludity

### Description of the change

Switches the readiness and liveness probes to use grpc_health_probe (until our minimum k8s version supports this natively) rather than the http get which depends on the gRPC-Gateway which we don't otherwise use.

Also fixes the Chart.home attribute which had been accidentally (I think?) switched to "https://bitnami.com" along with all the other charts (which don't have their own bitnami/vmware home pages) in #16546 .

### Benefits

Readiness and liveness checks are using the actual endpoint which is used by the app.
More useful homepage for chart.

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [N/A] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-05-11 09:49 UTC, dgomezleon requested changes
Thanks for contributing. I suggested a couple of changes to make it work.

2023-05-11 09:49 UTC, dgomezleon commented on bitnami/kubeapps/templates/kubeappsapis/deployment.yaml
> +              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.kubeappsapis.containerPorts.http }}"]
```suggestion
              command: ["grpc_health_probe", "-addr=:{{ .Values.kubeappsapis.containerPorts.http }}"]
```

2023-05-11 09:49 UTC, dgomezleon commented on bitnami/kubeapps/templates/kubeappsapis/deployment.yaml
> +              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.kubeappsapis.containerPorts.http }}"]
```suggestion
              command: ["grpc_health_probe", "-addr=:{{ .Values.kubeappsapis.containerPorts.http }}"]
```

2023-05-11 11:28 UTC, absoludity commented
> Thanks for contributing. I suggested a couple of changes to make it work.

Thanks @dgomezleon . Sorry, I just applied the same change that we have in our dev chart and hadn't realised that the bitnami one had some differences.

2023-05-12 08:27 UTC, dgomezleon approved these changes
LGTM

2023-05-12 08:27 UTC, merged