Enable qps/burst/maxeventageseconds in event exporter
bitnami/charts pull request #16554
Opened 2023-05-09 23:37 UTC by DavidHe1127

…/maxEventAgeSeconds

### Description of the change

Enable settings of 3 params.

### Benefits

Allow settings of these values. They are available in https://github.com/resmoio/kubernetes-event-exporter#troubleshoot-events-discarded-warning.

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-05-10 10:36 UTC, DavidHe1127 commented
> Hi @DavidHe1127,
> 
> Could you please provide more details about these values?
> 
> The value `config` in the 'bitnami/kubernetes-event-exporter' chart is rendered as a template, so it is not necessary for them to be present in the default `values.yaml` to be configured.
> 
> The real effect of this change would be setting the default config values `kubeQPS: 60, kubeBurst: 60, maxEventAgeSeconds: 10` for all existing deployments.

Did you mean that I can just set them via config and they would work correctly? Code snippet is written in Pulumi

```
    values: {
      config: {
        logLevel: 'error',
        logFormat: 'json',
        kubeQPS: 60,
        kubeBurst: 60,
        maxEventAgeSeconds: 10,
        route: {
          routes: [
            {
              match: [
                {
                  receiver: 'dump',
                },
              ],
            },
          ],
        },
        receivers: [
          {
            name: 'dump',
            stdout: {},
          },
        ],
      },
    },
```

2023-05-10 10:56 UTC, migruiz4 commented
Yes, additional parameters can be added under the `config:` value and will be added to your deployment.

I can't provide an example using Pulumi at the moment, but here are some other usage examples:
```
# Using helm CLI
$ helm install test bitnami/kubernetes-event-exporter --set config.kubeQPS=60 --set config.kubeBurst=120 --dry-run
...
---
# Source: kubernetes-event-exporter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-kubernetes-event-exporter
  namespace: "default"
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.3.1
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    kubeBurst: 120
    kubeQPS: 60
    leaderElection: {}
    logFormat: pretty
    logLevel: debug
    receivers:
    - file:
        layout: {}
        path: /dev/stdout
      name: dump
    route:
      routes:
      - match:
        - receiver: dump
```

```
#Providing a values.yaml file
$ cat test.yaml                                                             
config:
  kubeQPS: 60
  kubeBurst: 60
  maxEventAgeSeconds: 10
$helm install test bitnami/kubernetes-event-exporter -f test.yaml --dry-run
...
---
# Source: kubernetes-event-exporter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-kubernetes-event-exporter
  namespace: "default"
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.3.1
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    kubeBurst: 60
    kubeQPS: 60
    leaderElection: {}
    logFormat: pretty
    logLevel: debug
    maxEventAgeSeconds: 10
    receivers:
    - file:
        layout: {}
        path: /dev/stdout
      name: dump
    route:
      routes:
      - match:
        - receiver: dump
```

2023-05-10 10:59 UTC, DavidHe1127 commented
> Yes, additional parameters can be added under the `config:` value and will be added to your deployment.
> 
> I can't provide an example using Pulumi at the moment, but here are some other usage examples:
> 
> ```
> # Using helm CLI
> $ helm install test bitnami/kubernetes-event-exporter --set config.kubeQPS=60 --set config.kubeBurst=120 --dry-run
> ...
> ---
> # Source: kubernetes-event-exporter/templates/configmap.yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: test-kubernetes-event-exporter
>   namespace: "default"
>   labels:
>     app.kubernetes.io/name: kubernetes-event-exporter
>     helm.sh/chart: kubernetes-event-exporter-2.3.1
>     app.kubernetes.io/instance: test
>     app.kubernetes.io/managed-by: Helm
> data:
>   config.yaml: |
>     kubeBurst: 120
>     kubeQPS: 60
>     leaderElection: {}
>     logFormat: pretty
>     logLevel: debug
>     receivers:
>     - file:
>         layout: {}
>         path: /dev/stdout
>       name: dump
>     route:
>       routes:
>       - match:
>         - receiver: dump
> ```
> 
> ```
> #Providing a values.yaml file
> $ cat test.yaml                                                             
> config:
>   kubeQPS: 60
>   kubeBurst: 60
>   maxEventAgeSeconds: 10
> $helm install test bitnami/kubernetes-event-exporter -f test.yaml --dry-run
> ...
> ---
> # Source: kubernetes-event-exporter/templates/configmap.yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: test-kubernetes-event-exporter
>   namespace: "default"
>   labels:
>     app.kubernetes.io/name: kubernetes-event-exporter
>     helm.sh/chart: kubernetes-event-exporter-2.3.1
>     app.kubernetes.io/instance: test
>     app.kubernetes.io/managed-by: Helm
> data:
>   config.yaml: |
>     kubeBurst: 60
>     kubeQPS: 60
>     leaderElection: {}
>     logFormat: pretty
>     logLevel: debug
>     maxEventAgeSeconds: 10
>     receivers:
>     - file:
>         layout: {}
>         path: /dev/stdout
>       name: dump
>     route:
>       routes:
>       - match:
>         - receiver: dump
> ```

Awesome! Thanks. I will remove them from values file but I think it's still worth it to add them to the comment section as well as in README. What do you think?

I will also change the version to `2.4.1`.

2023-05-11 07:57 UTC, migruiz4 requested changes
Hi there!

I left some suggestions to help you adapt this PR as a description improvement as you proposed.

2023-05-11 07:57 UTC, migruiz4 commented on bitnami/kubernetes-event-exporter/values.yaml
> +## @param config.maxEventAgeSeconds maximum age of an event that can be processed
The `@param` is a reserved word used by the [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm/) to associate the values with their description/metadata.

These values would be removed so this section would need to be replaced.

I would suggest a more generic approach by referencing the upstream documentation and mentioning that this setting is rendered as a template to improve the user experience:

```suggestion
## Kubernetes event exporter configuration, rendered as a template
## ref: https://github.com/resmoio/kubernetes-event-exporter#configuration
```

2023-05-11 11:47 UTC, merged