[bitnami/redis-cluster] support external host to cluster announcement preffered type
bitnami/charts pull request #18028
Opened 2023-07-29 12:39 UTC by yo-ga

### Description of the change

### Benefits

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-08-10 18:46 UTC, yo-ga commented
@carrodher  Is there any updates or reviews?

2023-08-16 10:36 UTC, aoterolorenzo requested changes
Hi @yo-ga,

Sorry for all the delay with this, and thanks for the contribution!

I just left a minor comment, for the rest LGTM

Could you update the branch to merge? Thank you.

2023-08-16 10:36 UTC, aoterolorenzo commented on bitnami/redis-cluster/Chart.yaml
> +version: 8.6.13
I would update a minor version since dis adds new support

2023-08-17 09:25 UTC, aoterolorenzo approved these changes
LGTM

2023-08-17 09:25 UTC, merged