[bitnami/deespeed] feat: :tada: Add chart
bitnami/charts pull request #18139
Opened 2023-08-02 10:17 UTC by javsalgar

### Description of the change

This PR adds bitnami/deepspeed to the catalog. It has the following features:

 -  Bitnami standards
 -  Deploy as Job or Deployment
 -  Custom configuration and projects via configmaps or git
 -  SSH connection via keys instead of passwordless

### Benefits

New product to the chart

### Possible drawbacks

n/a

### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-08-04 17:14 UTC, fmulero reviewed
Great work @javsalgar! I like the new version identifier in the helpers !

I left some comments, Could you review them?

2023-08-04 17:14 UTC, fmulero commented on bitnami/deepspeed/templates/client/hostfile-configmap.yaml
> +    {{- end }}
Not sure why and it isn't a big problem, when template is rendered the `hostfile` starts with a blank line

2023-08-07 08:51 UTC, fmulero commented on bitnami/deepspeed/templates/client/hostfile-configmap.yaml
> +    {{- end }}
You right, after installation CM shows the right content, helm template shows the blank line at the beginning. We can close this conversation, it shouldn't be a problem.

2023-08-07 08:52 UTC, fmulero submitted a review, later dismissed
LGTM

2023-08-07 08:59 UTC, migruiz4 requested changes
Please take a look at my comments

2023-08-07 08:59 UTC, migruiz4 commented on bitnami/deepspeed/templates/client/networkpolicy.yaml
> +              {{- if .Values.podLabels }}
Value `podLabels` is missing in the values.yaml

2023-08-07 08:59 UTC, migruiz4 commented on bitnami/deepspeed/templates/client/client-dep-job.yaml
> +  {{- if .Values.useJob }}
Shouldn't this be `.Values.client.useJob`?

2023-08-07 08:59 UTC, migruiz4 commented on bitnami/deepspeed/templates/worker/worker-service.yaml
> +  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" $root.Values.service.sessionAffinityConfig "context" $root) | nindent 4 }}
```suggestion
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" $root.Values.worker.externalAccess.service.sessionAffinityConfig "context" $root) | nindent 4 }}
```

2023-08-07 08:59 UTC, migruiz4 commented on bitnami/deepspeed/templates/client/hostfile-configmap.yaml
> +    {{- if .Values.overrideHostFile }}
```suggestion
    {{- if .Values.config.overrideHostFile }}
```

2023-08-07 08:59 UTC, migruiz4 commented on bitnami/deepspeed/templates/_helpers.tpl
> +      find {{ $block.client.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ $block.containerSecurityContext.runAsUser }}:{{ $block.
```suggestion
      mkdir -p {{ $block.persistence.mountPath }}
      chown {{ $block.containerSecurityContext.runAsUser }}:{{ $block.podSecurityContext.fsGroup }} {{ $block.persistence.mountPath }}
      find {{ $block.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ $block.containerSecurityContext.runAsUser }}:{{ $block.podSecurityContext.fsGroup }}
```

2023-08-07 08:59 UTC, migruiz4 commented on bitnami/deepspeed/templates/worker/worker-statefulset.yaml
> +        {{- if .Values.worker.persistence.selector }}
Conversation marked as resolved, but value is still missing

2023-08-07 08:59 UTC, migruiz4 commented on bitnami/deepspeed/templates/worker/worker-statefulset.yaml
> +    {{- end }}
`.Values.labels` is missing in the values.yaml

2023-08-07 11:12 UTC, migruiz4 requested changes
Sorry, a few more comments

2023-08-07 11:12 UTC, migruiz4 commented on bitnami/deepspeed/templates/worker/worker-service.yaml
> +  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" $root.Values.externalAccess.service.sessionAffinityConfig "context" $root) | nindent 4 }}
My bad, I was missing the `worker` on my previous suggestion
```suggestion
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" $root.Values.worker.externalAccess.service.sessionAffinityConfig "context" $root) | nindent 4 }}
```

2023-08-07 11:12 UTC, migruiz4 commented on bitnami/deepspeed/templates/client/client-dep-job.yaml
> +    {{- end }}
`client.labels` missing in values.yaml

2023-08-07 11:12 UTC, migruiz4 commented on bitnami/deepspeed/templates/worker/worker-statefulset.yaml
> +    {{- include "common.tplvalues.render" (dict "value" .Values.labels "context" $) | nindent 4 }}
```suggestion
    {{- include "common.tplvalues.render" (dict "value" .Values.worker.labels "context" $) | nindent 4 }}
```

2023-08-07 11:43 UTC, migruiz4 approved these changes
Looks good to me!

2023-08-07 11:56 UTC, merged