[bitnami/kafka] Use the container port instead of the service port
bitnami/charts pull request #18319
Opened 2023-08-09 10:04 UTC by jadolg

### Description of the change

In the Kafka chart, when metrics are enabled, the exporter needs to point to all pods, not to the service.
This change makes it so the port used to reach the pods is the actual pod port and not the service port.

### Benefits

Makes the exporter start working correctly again

### Possible drawbacks

### Applicable issues

- fixes #18284 

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-08-18 14:30 UTC, jotamartos submitted a review, later dismissed
Thank you for your contribution. However, the branch has conflicts that needs to be resolved. You can learn more about that below.

2023-08-25 13:19 UTC, migruiz4 commented
Hi @jadolg,

Could you please update your branch again? A new version was released but GitHub won't let me solve conflicts in the UI.

2023-08-25 13:55 UTC, jadolg commented
> Hi @jadolg,
> 
> Could you please update your branch again? A new version was released but GitHub won't let me solve conflicts in the UI.

Done

2023-08-28 07:26 UTC, jotamartos requested changes
Please bump the Chart version accordingly.

2023-08-28 07:26 UTC, jotamartos commented on bitnami/kafka/Chart.yaml
> +version: 24.0.16
```suggestion
version: 25.1.2
```

2023-08-28 11:44 UTC, jotamartos approved these changes

2023-08-28 11:45 UTC, merged

2023-08-29 11:06 UTC, PDVJAM commented
25.1.2 chart still has service ports instead of container ones.

2023-09-04 09:56 UTC, jotamartos commented
Hi @PDVJAM,

Could you please provide more information? I just downloaded the latest bitnami/kafka chart and saw that these changes are included in the chart's templates. 

Thanks

2023-09-05 10:28 UTC, PDVJAM commented
@jotamartos Hey. Yes, now all ok. But the 25.1.2 was still not updated, but according to the merge - it should have.