[bitnami/supabase] Support for customizing standard labels
bitnami/charts pull request #18751
Opened 2023-08-21 11:24 UTC by juan131

### Description of the change

This PR follows up #18154 ensuring this chart is adapted to use new helpers' format, hence adding support for customizing standard labels.

### Benefits

User can customize standard labels.

### Possible drawbacks

None

### Applicable issues

N/A

### Additional information

#18154 must be merged **before** this PR

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-08-24 07:37 UTC, juan131 commented on bitnami/supabase/templates/studio/deployment.yaml
> +      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
fixed at https://github.com/bitnami/charts/pull/18751/commits/1058280d2f4f8f94b90ba32085394e4f60708f4c

2023-08-24 10:36 UTC, fmulero requested changes
Could you update the dependencies?

2023-08-24 12:09 UTC, juan131 commented
Let's wait for Kong to be released with the required changes

2023-08-28 06:27 UTC, juan131 commented
Kong released! Unblocking PR

2023-08-28 06:55 UTC, fmulero approved these changes
LGTM

2023-08-28 07:09 UTC, merged