[bitnami/redis] Support enableServiceLinks
bitnami/charts pull request #18779
Opened 2023-08-22 11:37 UTC by AnisimoffNikita

### Description of the change

Add `enableServiceLinks` option to `master`, `replica`, `sentinel` and `metrics` pod specs.

### Benefits

EnableServiceLinks indicates whether information about services should be injected into pod's environment variables. Optional: Defaults to true.

### Possible drawbacks

### Applicable issues

- fixes #18775

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-08-22 16:38 UTC, jouve requested changes

2023-08-22 16:38 UTC, jouve commented on bitnami/redis/Chart.yaml
> +version: 17.15.7
```suggestion
version: 17.16.0
```

2023-08-23 16:47 UTC, jouve commented
you need to bump Chart.yaml again (https://github.com/bitnami/charts/commit/e3c23350ca2a96918c40265674cb53e58ff42183)

2023-08-24 12:48 UTC, juan131 requested changes

2023-08-25 13:57 UTC, juan131 approved these changes
LGTM

2023-08-25 13:58 UTC, merged