[bitnami/schema-registry] fix fullName of kafka subchart
bitnami/charts pull request #18926
Opened 2023-08-29 11:22 UTC by Nemeq

### Description of the change
- Changed the fullName generation on the helpers.tpl to match the name of the Kafka subchart.

### Benefits
- The chart will work with the Kafka sub chart, right now it fails because the fullName is generated incorrectly.

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-09-06 09:27 UTC, rafariossaa commented
Hi,
  Could you indicate how to reproduce the issue ?
  This is default for `nameOverride: ""` and I got the right name for kafa rendered for the environment variable: `SCHEMA_REGISTRY_KAFKA_BROKERS`.

2023-09-06 09:41 UTC, Nemeq commented
Hi,
I guess is a not so common case
```
helm install kafka oci://registry-1.docker.io/bitnamicharts/schema-registry -n kafka-test-2
```
then in the schema-registry, the setting will be like this:
```
SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka-kafka-controller-0.kafka-kafka-controller-headless.kafka-test-2.svc.cluster.local:9092
```
When it should be:
```
PLAINTEXT://kafka-controller-0.kafka-controller-headless.kafka-test-2.svc.cluster.local:9092
```

2023-09-08 09:38 UTC, rafariossaa commented
The first part is the deployment name, for example, if you install it with:
```
$ helm install mysch -f values.yaml . 
```
Then I got:
```
SCHEMA_REGISTRY_KAFKA_BROKERS: "PLAINTEXT://mysch-kafka-controller-0.mysch-kafka-controller-headless.default.svc.cluster.local:9092"
```
I think that makes completely sense because that way, if you have more than one deployment of this kind in the namespace, you could differentiate them easily.

2023-09-08 11:54 UTC, Nemeq commented
You are right about that, if we remove the default name then it will not be clear what is the actual name, the only problem is that if you do the same mistake as me and put the release as Kafka it will fail, but not sure how to prevent it.

2023-09-14 08:54 UTC, rafariossaa requested changes

2023-09-14 08:54 UTC, rafariossaa commented on bitnami/schema-registry/templates/_helpers.tpl
> +{{- end -}}
Also, update the Chart.yaml version.

2023-10-05 02:17 UTC, closed without merging