bitnami/kafka add the ability to reference an existing cluster id secret
bitnami/charts pull request #19518
Opened 2023-09-25 21:35 UTC by thomasbellio

### Description of the change

This change allows the user of the chart to deploy Kafka in Kraft mode such that it will reference an existing Cluster ID secret in K8s. 

### Benefits

This will enable users that are deploying secret configuration through Vault or some other means so that they don't have to include potentially sensitive information like the cluster id in source code. 

### Possible drawbacks

There don't appear to be many drawbacks to this approach, it makes the chart more flexible. One draw back might be that this adds some new complexity as do all new configuration options.  The added parameter `existingClusterIdSecret` is incompatible with explicitly setting your clusterId in the values.yaml so that might cause confusion.

### Applicable issues

N/A

### Additional information

N/A

### Checklist

- [x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-09-26 09:27 UTC, aoterolorenzo requested changes
@thomasbellio thank you for contributing! I just wrote some comments above.

2023-09-26 09:27 UTC, aoterolorenzo commented on bitnami/kafka/Chart.yaml
> +version: 25.1.13
As this is a new feature, we should bump a minor to correctly follow [semver](https://semver.org/)

```suggestion
version: 25.2.0
```

2023-09-26 09:27 UTC, aoterolorenzo commented on bitnami/kafka/templates/broker/statefulset.yaml
> +                  name: {{ ternary (printf "%s-kraft-cluster-id" (include "common.names.fullname" .)) .Values.kraft.existingClusterIdSecret  (not .Values.kraft.existingClusterIdSecret) }}
Searching over a negated value in a ternary seems a little tricky. What about...

```suggestion
                  name: {{ default (printf "%s-kraft-cluster-id" (include "common.names.fullname" .)) .Values.kraft.existingClusterIdSecret }}
```

2023-09-26 09:27 UTC, aoterolorenzo commented on bitnami/kafka/templates/controller-eligible/statefulset.yaml
> +                  name: {{ ternary (printf "%s-kraft-cluster-id" (include "common.names.fullname" .)) .Values.kraft.existingClusterIdSecret  (not .Values.kraft.existingClusterIdSecret) }}
```suggestion
                  name: {{ default (printf "%s-kraft-cluster-id" (include "common.names.fullname" .)) .Values.kraft.existingClusterIdSecret }}
```

2023-09-26 22:33 UTC, thomasbellio commented
@aoterolorenzo Thanks for the suggestions, I integrated those.

2023-09-29 10:55 UTC, aoterolorenzo approved these changes
LGTM! Thank you @thomasbellio

2023-09-29 10:55 UTC, merged