[bitnami/mlflow] feat: 🎉 Add chart
bitnami/charts pull request #20069
Opened 2023-10-11 14:47 UTC by javsalgar

### Description of the change

### Benefits

### Possible drawbacks

This PR adds a helm chart for MLflow. Has the following features:

- TLS support
- Network policies
- Prometheus metrics
- HPA and VPA
- Bitnami standards

### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-10-13 07:13 UTC, fmulero requested changes
Great @javsalgar!

I left some comments, could you give them a glance?

2023-10-13 07:13 UTC, fmulero commented on bitnami/mlflow/templates/run/source-configmap.yaml
> +  name: {{ printf "%s-source" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
Shouldn't it be?
```suggestion
  name: {{ include "mlflow.v0.run.source.configMapName" . }}
```

2023-10-16 08:09 UTC, javsalgar commented on .vib/mlflow/goss/goss.yaml
> +      - /admin_password={{ .Vars.tracking.auth.password }}/
This is necessary for random users (a.k.a openshift) to work

2023-10-16 08:48 UTC, fmulero approved these changes
Great @javsalgar LGTM

2023-10-16 08:50 UTC, merged