[bitnami/postgresql-ha] feat: annotate pgpool deployment by checksum of custom user secrets
bitnami/charts pull request #20958
Opened 2023-11-15 04:49 UTC by jjangga0214

### Description of the change

https://github.com/bitnami/charts/issues/16396#issuecomment-1741981842

### Benefits

People will not create issues like #16396.

### Possible drawbacks

- When a user provides his/her own secret, the user still have to restart the deployment manually. But this is the obvious thing the user can expect, so not a drawback actually. To  automate such task, the user should use another tool like [Reloader](https://github.com/stakater/Reloader) by the way.
- The maintainers should sync the condition in the `if` statement between the *`deployment.yaml`* and *`custom-users-secrets.yaml`* when modified.

### Applicable issues

None, but related to #16396.

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-11-15 08:42 UTC, carrodher commented
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

2023-11-15 09:29 UTC, jjangga0214 commented
Signed it, thanks for the kind and prompt reply :)

2023-11-17 15:32 UTC, joancafom requested changes
Thanks for you PR! I left you a small comment as a review, could you please take a look at it when you have the chance?

2023-11-17 15:32 UTC, joancafom commented on bitnami/postgresql-ha/templates/pgpool/deployment.yaml
> +    checksum/custom-users-secrets: {{ include (print $.Template.BasePath "/custom-users-secrets.yaml") . | sha256sum }}
Isn't it `/pgpool/custom-users-secrets.yaml` the correct path?

```suggestion
    checksum/custom-users-secrets: {{ include (print $.Template.BasePath "/pgpool/custom-users-secrets.yaml") . | sha256sum }}
```

2023-11-27 11:40 UTC, jjangga0214 commented
@joancafom Yes, you're right! Thanks :)

2023-11-30 10:51 UTC, joancafom approved these changes
LGTM! Thanks for your changes 😁

2023-11-30 10:52 UTC, merged