[bitnami/template] allow specific annotations for controllers
bitnami/charts pull request #21010
Opened 2023-11-16 16:08 UTC by agrevtsev

### Description of the change

Allow to specify annotations for specific controllers (e.g. daemonset, deployment, statefulset)

### Benefits

There is no possibility to add annotations only for specific daemonset/deployment/statefulset.
My proposal is introduce such entities as deploymentAnnotations, statefulsetAnnotations and daemonsetAnnotations, as for now we can only apply annotations to daemonset/deployment/statefulset globally, by the means of .Values.commonAnnotations.
For example: when one wants to use [stakater/Reloader](https://github.com/stakater/Reloader) to reload daemonset/deployment/statefulset on secret/configmap change, one must add specific annotation to the entity one wants to manage as such.

### Possible drawbacks

### Applicable issues

- fixes #20983

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-11-21 13:09 UTC, juan131 requested changes
Please use the `"common.tplvalues.merge"` helper.

2023-11-21 13:09 UTC, juan131 commented on template/CHART_NAME/templates/daemonset.yaml
> +    {{- end }}
```suggestion
  {{- if or .Values.%%MAIN_OBJECT_BLOCK%%.daemonsetAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" .Values.%%MAIN_OBJECT_BLOCK%%.daemonsetAnnotations .Values.commonAnnotations "context" .) | fromYaml }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
```

2023-11-21 13:09 UTC, juan131 commented on template/CHART_NAME/templates/deployment.yaml
> +    {{- end }}
```suggestion
  {{- if or .Values.%%MAIN_OBJECT_BLOCK%%.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" .Values.%%MAIN_OBJECT_BLOCK%%.deploymentAnnotations .Values.commonAnnotations "context" .) | fromYaml }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
```

2023-11-21 13:09 UTC, juan131 commented on template/CHART_NAME/templates/statefulset.yaml
> +    {{- end }}
```suggestion
  {{- if or .Values.%%MAIN_OBJECT_BLOCK%%.statefulsetAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" .Values.%%MAIN_OBJECT_BLOCK%%.statefulsetAnnotations .Values.commonAnnotations "context" .) | fromYaml }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
```

2023-11-22 12:32 UTC, agrevtsev commented
> Please use the `"common.tplvalues.merge"` helper.
hi @juan131! Should i squash commits?

2023-11-22 13:08 UTC, juan131 approved these changes
LGTM

2023-11-22 13:08 UTC, juan131 commented
Don't worry about squashing, it'll be done while merging.

2023-11-22 13:08 UTC, merged