[bitnami/wordpress] Support for cronjobs in wordpress
bitnami/charts pull request #21412
Opened 2023-12-06 10:29 UTC by lotyp

### Description of the change

This pull request introduces CronJob support to the Bitnami WordPress Helm chart. It adds a new section in the values.yaml file for configuring CronJobs

### Benefits

The integration of CronJob support provides several benefits:

* Enables automation of routine WordPress tasks, enhancing the functionality of the WordPress deployment.
* Offers flexibility to chart users to define their own custom CronJobs according to their specific needs.
* Ensures that CronJobs are consistently and correctly configured, following the Bitnami chart standards.

### Possible drawbacks

* Introducing CronJobs adds an additional layer of complexity to the chart, which might require users to have a bit more understanding of Kubernetes CronJobs.
* In cases where CronJobs are not configured properly, it might lead to unintended behaviors or performance issues.

### Applicable issues

* Initial implementation, no existing issues related to this feature.

### Additional information

* This change has been tested to ensure that it does not interfere with the existing functionalities of the WordPress chart and follows the Bitnami best practices for Helm chart development.

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-12-06 15:09 UTC, lotyp commented
I have tested this functionality by manually disabling default cron behavior in `wp-config.php`

2023-12-07 09:54 UTC, jevgenijsblaus approved these changes

2023-12-11 08:21 UTC, juan131 requested changes
Thanks for this contribution! I added a few comments

2023-12-11 08:21 UTC, juan131 commented on bitnami/wordpress/values.yaml
> +    ## @param
```suggestion
```

2023-12-11 08:21 UTC, juan131 commented on bitnami/wordpress/values.yaml
> +        pullSecrets: []
It is not allowed to include non-Bitnami images on Bitnami charts. As an alternative you may use `bitnami/os-shell` image as other charts do.

2023-12-11 08:21 UTC, juan131 commented on bitnami/wordpress/templates/cronjobs.yaml
> +            {{- end }}
Why do we need all these env. vars, mounted configuration, etc.?

2023-12-11 08:21 UTC, juan131 commented on bitnami/wordpress/values.yaml
> +  scheduler:
It seems there's only one cronjob you're actually defining. Do you expect to add support for more? Isn't this sth that can be already covered with `extraDeploy` parameter?

2023-12-11 08:21 UTC, juan131 commented on bitnami/wordpress/templates/cronjobs.yaml
> +            {{- end }}
Use "common.labels.standard" helper merging `.Values.commonLabels` with `.Values.cronJobs.scheduler.podLabels`. Also, consider annotations.
See how others charts do it:

- https://github.com/bitnami/charts/blob/main/bitnami/redmine/templates/cronjob.yaml#L24-L30

2023-12-11 08:21 UTC, juan131 commented on bitnami/wordpress/templates/cronjobs.yaml
> +  concurrencyPolicy: {{ .Values.cronJobs.scheduler.concurrencyPolicy }}
Do we want to allow concurrency?

2023-12-11 08:21 UTC, juan131 commented on bitnami/wordpress/templates/cronjobs.yaml
> +apiVersion: batch/v1
```suggestion
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
```

2024-01-01 02:14 UTC, closed without merging

2024-07-24 19:54 UTC, brandan-schmitz commented
Any change this can be re-opened as it was never completed but is still a very useful thing to get added?

2024-07-25 05:53 UTC, carrodher commented
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

2024-07-25 21:40 UTC, lotyp commented
> Any change this can be re-opened as it was never completed but is still a very useful thing to get added?

I remember about this PR 😅

Unfortunately right now I don't have any k8s cluster available to test this out, but if I will have time I could finish it.