bitnami/redis Add namespaceOverride capability to redis chart
bitnami/charts pull request #21479
Opened 2023-12-08 08:51 UTC by jgmartinez

### Description of the change

Similarly as in other charts, this change adds the namespaceOverride variable to Redis, allowing to deploy the chart in a different namespace as the helm installation default. This is really useful when the chart is installed as a dependency of another chart.

### Benefits

Redis can now be deployed in a different namespace as the indicated in the Helm installation command, if needed.

### Possible drawbacks

Namespace in namespaceOverride needs to be created prior installation, due to Helm's limitation on creating namespaces for subcharts.

### Applicable issues

No open issues

### Additional information

This replaces #21365

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-12-08 08:52 UTC, jgmartinez commented
@fmulero Moved here

2023-12-11 08:25 UTC, fmulero approved these changes
Thanks a lot Juan for your contribution.

LGTM

2023-12-11 09:03 UTC, fmulero requested changes
Sorry again @jgmartinez

I've just figure out that some special characters have been included in your changes instead of white spaces. Please replace all of them with a single white space

2023-12-11 09:08 UTC, jgmartinez commented on bitnami/redis/templates/headless-svc.yaml
> +  namespace: {{ include "common.names.namespace" . | quote }}
That was weird, should be fine now 😄

2023-12-11 12:13 UTC, fmulero commented on bitnami/redis/templates/headless-svc.yaml
> +  namespace: {{ include "common.names.namespace" . | quote }}
Great! thanks

2023-12-11 12:14 UTC, fmulero approved these changes
LGTM

2023-12-11 12:14 UTC, merged