bitnami/haproxy - loadBalancerSourceRanges should be list and not string
bitnami/charts pull request #21490
Opened 2023-12-10 12:06 UTC by nirroz93

### Description of the change
Bug fix, using values:
```
service:
  type: LoadBalancer
  loadBalancerSourceRanges: 
    - 1.1.1.1/32
    - 2.2.2.2/32
```
The output template is:
```
# Source: haproxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-release-haproxy
  namespace: "my-namespace"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.9.0
    helm.sh/chart: haproxy-0.10.9
    app.kubernetes.io/component: haproxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  loadBalancerSourceRanges: [1.1.1.1/32 2.2.2.2/32]
```
Which is invalid service

### Benefits
Bug fix

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-12-10 12:16 UTC, nirroz93 commented
Before the change I'm getting an error:
```Error: UPGRADE FAILED: cannot patch "my-release-haproxy" with kind Service: Service "my-release-haproxy" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[1.1.1.1/32 2.2.2.2/32]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24 ```
After the change it's working

2023-12-10 12:18 UTC, nirroz93 commented
The funny thing is that the output of helm template looks the same actually...

2023-12-15 10:08 UTC, migruiz4 requested changes
Hi @nirroz93,

Thank you very much for your contribution! Could you please take a look at my comment?

2023-12-15 10:08 UTC, migruiz4 commented on bitnami/haproxy/templates/service.yaml
> +    {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
Could you please keep it in the same line? The `nindent` already adds the new line when rendering

Additionally, please add a condition for empty values:

```suggestion
  {{- if not (empty .Values.service.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
```

2023-12-17 10:33 UTC, nirroz93 commented
Thanks @migruiz4 , done

2023-12-21 10:13 UTC, migruiz4 approved these changes
Looks good to me, thank you for your contribution!

2023-12-21 10:26 UTC, merged