Add namespaceOverride for Minio chart deployment
bitnami/charts pull request #21638
Opened 2023-12-19 08:24 UTC by opencmit2

### Description of the change

To ensure that the Minio sub-chart is deployed to a specific namespace, the 'namespaceOverride' parameter is now included. This change addresses issues where the Minio sub-chart was not being deployed to the intended namespace when included as a sub-chart.
### Benefits

### Possible drawbacks

### Applicable issues

- fixes #21626 

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2023-12-19 11:35 UTC, juan131 reviewed
Thanks so much for this contribution, we really appreciate it! I left some minor/cosmetic requests, please address them when you find the time for it.

2023-12-19 11:35 UTC, juan131 commented on bitnami/minio/Chart.yaml
> +version: 12.10.11
Please note you're adding a new parameter. Therefore, you need to bump the minor version:
```suggestion
version: 12.11.0
```

2023-12-19 11:35 UTC, juan131 commented on bitnami/minio/templates/distributed/statefulset.yaml
> +{{- $releaseNamespace := (include "common.names.namespace" .) }}
Parenthesis not required:
```suggestion
{{- $releaseNamespace := include "common.names.namespace" . }}
```

2023-12-19 11:35 UTC, juan131 commented on bitnami/minio/templates/prometheusrule.yaml
> +{{- $releaseNamespace := default (include "common.names.namespace" .) .Values.metrics.prometheusRule.namespace  }}
Remove extra space:
```suggestion
{{- $releaseNamespace := default (include "common.names.namespace" .) .Values.metrics.prometheusRule.namespace }}
```

2023-12-19 11:35 UTC, juan131 commented on bitnami/minio/templates/prometheusrule.yaml
> +  namespace: {{ $releaseNamespace | quote  }}
Remove extra space:
```suggestion
  namespace: {{ $releaseNamespace | quote }}
```

2023-12-19 11:35 UTC, juan131 commented on bitnami/minio/templates/servicemonitor.yaml
> +  namespace: {{ $releaseNamespace | quote  }}
Remove extra space:
```suggestion
  namespace: {{ $releaseNamespace | quote }}
```

2023-12-20 02:31 UTC, opencmit2 commented
Hi @juan131 
now it has been dealt with, please review.

2023-12-20 07:08 UTC, juan131 approved these changes
LGTM

2023-12-20 07:10 UTC, juan131 requested changes

2023-12-20 07:10 UTC, juan131 commented on bitnami/minio/templates/tls-secrets.yaml
> +{{- $releaseNamespace := (include "common.names.namespace" . }}
Typo:
```suggestion
{{- $releaseNamespace := include "common.names.namespace" . }}
```

2023-12-21 09:27 UTC, juan131 approved these changes

2023-12-21 09:27 UTC, merged

2023-12-21 09:27 UTC, juan131 commented
Thanks for your contribution @opencmit2 ! The PR is now merged and the new chart version should be available within the next few hours.