[bitnami/jupyterhub] add missing service api tokens to hub's secret
bitnami/charts pull request #21784
Opened 2023-12-28 14:46 UTC by rmoreas

## Name and Version:

bitnami/jupyterhub 5.2.9

## Description of the change

Fix exception "hub.services.XXX.apiToken not found in either k8s Secret!" thrown by `jupyterhub_config.py` when
defining [services](https://z2jh.jupyter.org/en/latest/administrator/services.html) in `hub.services` as documented by
upstream z2jh.

## What steps will reproduce the bug?

Overwrite `hub.configuration` to include the following:

```yaml
hub:
  configuration: |
    # ...
    hub:
      {{- if .Values.hub.services }}
      services:
        {{- include "common.tplvalues.render" ( dict "value" .Values.hub.services "context" $ ) | nindent 8 }}
      {{- else }}
      services: {}
      {{- end }}
    # ...
```
Define a service below `hub.services`. E.g.:

```yaml
hub:
  services:
    service-admin:
      apiToken: XXXXXXXXXXXXXXXXXXX
      admin: true
```

Defining above service results in an exception:

```
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[E 2023-12-28 12:24:50.528 JupyterHub app:3382]
    Traceback (most recent call last):
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 3379, in launch_instance_async
        await self.initialize(argv)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 2857, in initialize
        self.load_config_file(self.config_file)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/traitlets/config/application.py", line 113, in inner
        return method(app, *args, **kwargs)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/traitlets/config/application.py", line 950, in load_config_file
        for (config, fname) in self._load_config_files(
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/traitlets/config/application.py", line 909, in _load_config_files
        config = loader.load_config()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/traitlets/config/loader.py", line 626, in load_config
        self._read_file_as_dict()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/traitlets/config/loader.py", line 659, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa
      File "/etc/jupyterhub/jupyterhub_config.py", line 401, in <module>
        service["api_token"] = get_secret_value(f"hub.services.{key}.apiToken")
      File "/etc/jupyterhub/z2jh.py", line 57, in get_secret_value
        raise Exception(f"{key} not found in either k8s Secret!")
    Exception: hub.services.service-admin.apiToken not found in either k8s Secret!
```` 

## What do you see instead?

The hub should run without throwing an exception and define the requested services as documented at https://z2jh.jupyter.org/en/latest/administrator/services.html

## Root cause

`jupyterhub_config.py` as generated in the hub's [ConfigMap](../blob/main/bitnami/jupyterhub/templates/hub/configmap.yaml)
uses the `get_secret_value` function of the `z2jh` module to retrieve the API tokens of services defined in `hub.services`, but
these API tokens are not added to the hub's managed [Secret](../blob/main/bitnami/jupyterhub/templates/hub/secret.yaml).

## Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-01-02 08:47 UTC, fmulero requested changes
Thanks a lot @rmoreas and Happy New Year!

Great contribution!!! Very useful and it works as expected. I left some comments I hope you can review them.

2024-01-02 08:47 UTC, fmulero commented on bitnami/jupyterhub/templates/_helpers.tpl
> +*/}}
Could you add usage instructions here in the documentation?

2024-01-02 08:47 UTC, fmulero commented on bitnami/jupyterhub/templates/_helpers.tpl
> +    {{- $service_key := index . 1 }}
If you use a dictionary instead of a list, it would be a little bit clearer and easier to understand.

2024-01-02 08:47 UTC, fmulero commented on bitnami/jupyterhub/templates/hub/secret.yaml
> +  {{- range $key, $service := .Values.hub.services }}
`hub.services` is not defined in the `values.yaml` file. It should be defined and it would be great if you could add a configuration example.

2024-01-02 08:47 UTC, fmulero commented on bitnami/jupyterhub/Chart.yaml
> +version: 5.2.10
As I understand `hub.services` was not supported before and with these changes you are adding this feature. According to [semver](https://semver.org/) a new minor version should be released:
```suggestion
version: 5.3.0
```

2024-01-03 07:44 UTC, fmulero approved these changes
Brilliant! Thanks a lot @rmoreas 

LGTM

2024-01-03 07:44 UTC, merged

2024-01-03 08:01 UTC, rmoreas commented
@fmulero thanks for the quick review and merge. Best wishes for 2024 too, 366 days to make the best of it!