[bitnami/odoo] Fix secret name for external database password
bitnami/charts pull request #22683
Opened 2024-01-24 07:28 UTC by AlMaVizca

### Description of the change

The deployment cannot find the secret with external database password and fails to start.
This change makes consistent definition between the secret for the external database password with the deployment secret definition.

### Benefits

The pod will start without errors

### Possible drawbacks

Unknown

### Applicable issues

- fixes #14741

### Additional information

I tried to run the CI action on my side, but It didn't work, and I don't know if it's because of some specifications for the project itself.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-01-24 08:08 UTC, carrodher commented
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

2024-01-25 11:57 UTC, joancafom requested changes
Thanks for your changes! I left a comment for you as a review, could you please check?

2024-01-25 11:57 UTC, joancafom commented on bitnami/odoo/templates/externaldb-secrets.yaml
> +  name: {{ printf "%s-externaldb" .Release.Name | trunc 63 | trimSuffix "-" }}
I think the old approach is the right one to follow, please perform the changes in 

https://github.com/bitnami/charts/blob/09b80f82df6a51202b219805ae4b0d743ae406cc/bitnami/odoo/templates/_helpers.tpl#L100-L102

to use `(include "common.names.fullname" .)` instead 😁

2024-01-26 08:25 UTC, joancafom approved these changes
LGTM! Thanks for your changes 🚀

2024-01-26 08:26 UTC, merged