Update flink chart
bitnami/charts pull request #23397
Opened 2024-02-12 08:58 UTC by daroga0002

### Description of the change

Closes https://github.com/bitnami/charts/issues/22225

As per Flink docs taskmanager host name must be unique:
![image](https://github.com/bitnami/charts/assets/20227477/84c6808c-444d-470e-b84f-dd8035d35f88)

currently it is assigned to any taskmanager pod same name what is causing issues with registration to pekko framework. So in result chart doesnt work when you setup more replicas than one for taskmanager deployment. This PR is taking a unique name for `taskmanager.host` name which is equal to pod name (using downward API)

### Benefits

This chart will start working with more than one task manager host

### Possible drawbacks

none

### Applicable issues

- fixes #22225

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-02-12 09:00 UTC, daroga0002 commented
@dgomezleon can you take a look into it

2024-02-15 11:07 UTC, juan131 requested changes
Hi @daroga0002 

Thanks so much for this contribution! IMHO, we should change the way to deploy TaskManger and use a statefulset instead since, as you pointed out, it's required a unique FQDN per replica, see use cases for using statefulsets:

> Stable, unique network identifiers.

Source: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets

I've double-checked this with @aoterolorenzo and he agrees on applying this change.

2024-02-23 13:27 UTC, daroga0002 commented
> Hi @daroga0002
> 
> Thanks so much for this contribution! IMHO, we should change the way to deploy TaskManger and use a statefulset instead since, as you pointed out, it's required a unique FQDN per replica, see use cases for using statefulsets:
> 
> > Stable, unique network identifiers.
> 
> Source: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets
> 
> I've double-checked this with @aoterolorenzo and he agrees on applying this change.

I think you missed my point, those `Stable, unique network identifiers.` are required during task manager lifecycle. When taskmanager disconnects from cluster then his lifecycle ends.



But looks that even my proposed change doesnt solve issue as then jobmanager is no able to reverse nslookup taskmanager what is causing issue with job distribution.


Unfortunatelly looks this chart is `broken` by design and it can run only with taskamanger replicas setup only to 1.

2024-02-26 09:43 UTC, juan131 commented
Hi @daroga0002 

Please check my approach for using a statefulset at https://github.com/bitnami/charts/pull/23904

2024-02-26 09:54 UTC, daroga0002 commented
As I mentioned, this doesnt require statefulset (which will be also limiting it). Flink cluster is dynamic and fully supports `Deployment` types.

I believe I found where is issue (basing on manifests directly from flink https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/deployment/resource-providers/standalone/kubernetes/#common-cluster-resource-definitions).


Issue is that jobmanager and taskmanager are forming Pekko cluster. Each Taskmanager in cluster must have `unique` name  (so service delivered for taskmanager by this chart is useless).

Change in mentioned PR was solving problem with forming Pekko cluster, but it not solved part where Jobmanager should initiate task on taskmanager. This is cuased that registration of task manager (`FLINK_CFG_TASKMANAGER_HOST`) using pod name `metadata.name` is not resolvable from job manager  (as Kubernetes doesnt register pod names in own DNS system).

Solution (which require testing) seems be doing it in same way as Flink documentation example resources which are registering taskmanager using POD adress (using `status.podIP`) so then communication will be happening using IPs instead hostnames.

2024-02-26 10:10 UTC, juan131 commented
@daroga0002 using a statefulset doesn't imply that Flink cluster isn't dynamic nor stateful. The solution I'm proposing combining statefulset's with headless services' capabilities provide you a solution for the registering pod names in the DNS system.

Please give it a try and play with it scaling up/down the number of Taskmanager replicas.

2024-03-05 13:10 UTC, closed without merging