[bitnami/schema-registry] Fixed SS init script to copy ssl.keystore and ssl.trustore to correct folder for HTTPS setup
bitnami/charts pull request #23583
Opened 2024-02-17 18:30 UTC by ETisREAL

As highlighted in the issue #21791 it was necessary to update the Stateful Set init script to copy the ssl.keystore.jks and ssl.trustore.jsk files (if present) over to `/opt/bitnami/schema-registry/certs/` to enable HTTPS setup

2024-02-21 14:53 UTC, Mauraza requested changes
Hi @ETisREAL,

Thanks for the contribution!!!! I think it is not necessary to upgrade to major, it is not a breaking change.

2024-02-21 14:53 UTC, Mauraza commented on bitnami/schema-registry/Chart.yaml
> +version: 17.0.0
```suggestion
version: 16.8.1
```

2024-02-21 18:46 UTC, ETisREAL commented on bitnami/schema-registry/Chart.yaml
> +version: 17.0.0
Sure thing :)

2024-02-23 14:55 UTC, Mauraza approved these changes
LGTM!

2024-02-23 15:01 UTC, merged

2024-02-23 17:34 UTC, ETisREAL commented
Thank you @Mauraza :) Have a nice WE