[bitnami/elasticsearch] feat: :sparkles: :lock: Add readOnlyRootFilesystem support
bitnami/charts pull request #23779
Opened 2024-02-22 08:31 UTC by javsalgar

Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>

### Description of the change

This PR performs the necessary changes to enable readOnlyRootFilesystem. This consists of:

- Adding emptyDir directories in all container writable paths
- Update image with one compatible with an emptydir conf folder
- Add runAsGroup

IMPORTANT: In order to avoid potentially breaking changes, this PR sets the readOnlyRootFilesystem value to `false`.

### Benefits

More security in the chart

### Possible drawbacks

Potential unforeseen issues with customizations

### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-03-05 07:56 UTC, CeliaGMqrz approved these changes
LGTM

2024-03-06 11:16 UTC, alemorcuq requested changes

2024-03-06 11:16 UTC, alemorcuq commented on bitnami/elasticsearch/templates/data/statefulset.yaml
> +          {{- if .Values.coordinating.containerSecurityContext.enabled }}
This is not a coordinating node but you are using the coordinating settings here. Same with the rest of nodes.

2024-03-06 14:58 UTC, merged

2024-03-13 02:12 UTC, dunn commented
when i try to upgrade to a version including this change, the new initcontainer is failing for me with 
```
copy-default-plugins cp: cannot create directory '/plugins/': No such file or directory
```

i'm running elasticsearch as a subchart with these values:
```yaml
elasticsearch:
  coordinating:
    replicaCount: 0
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0
  master:
    replicaCount: 2
    masterOnly: false
    resources:
      requests:
        cpu: "500m"
        memory: 1Gi
      limits:
        cpu: "1000m"
        memory: 1Gi
```