[bitnami/matomo] Separate config for cronjobs
bitnami/charts pull request #24339
Opened 2024-03-11 13:23 UTC by Xartos

### Description of the change

I wanted to be able to have separate config for the cronjobs compared to the matomo deployment.
So I extracted persistent volume and resources config.
I also added `podSecurityContext` and `extraEnvVars` for both cronjobs

### Benefits

One major benefit is that you can now disable persistence for the cronjobs since they were unable to be scheduled if you had persistence on matomo and `ReadWriteOnce` volumes.
And otherwise this adds more ability to setup the cronjobs a bit differently than the matomo deployment to match the needs of the cluster.

### Possible drawbacks

There's a bit more config now which might be perceived as complex. But I think that the benefits overcomes the drawbacks.

### Applicable issues

- fixes #

### Additional information

This will cause some disruption of the config where some config were moved from one place to another so I opted to bump a minor version for this.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-03-13 16:19 UTC, Mauraza commented
Hi @Xartos,

Thanks for the contribution!! Your changes made the tests fail, so I just updated it, and let's see how is going.

2024-03-13 16:22 UTC, Mauraza commented
The helm list is failing, could you check it?
```bash
helm lint .
==> Linting .
[ERROR] templates/cronjob.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 80: did not find expected '-' indicator
[ERROR] templates/cronjob.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 80: did not find expected '-' indicator

Error: 1 chart(s) linted, 1 chart(s) failed
```

2024-03-15 07:22 UTC, Xartos commented
@Mauraza I totally missed to test with the default config :sweat_smile: But I should've solved that issue now :slightly_smiling_face:

2024-03-18 11:33 UTC, Mauraza commented
Hi @Xartos,

Could you add a small note in the README.md about this change? I think the users should be notified.

2024-03-19 14:43 UTC, Xartos commented
@Mauraza Do you not think this is enough

https://github.com/bitnami/charts/pull/24339/files#diff-190bc6e7ebe50a8f1a98ec55511936b5066371f377f79ceacf2f83b3c6a37f7fR475-R478

If not would you like me do expand even more in that section or would you like me do add something in some other section?

2024-03-20 12:25 UTC, Mauraza requested changes
That looks good but I think if someone with the cronjobs disabled the upgrade it is going to fail, so it should be major.

2024-03-20 12:25 UTC, Mauraza commented on bitnami/matomo/Chart.yaml
> +version: 5.6.0
```suggestion
version: 6.0.0
```

2024-03-20 12:25 UTC, Mauraza commented on bitnami/matomo/README.md
> +### To 5.6.0
```suggestion
### To 6.0.0
```

2024-03-20 16:59 UTC, Mauraza approved these changes
Hi @Xartos,
Thanks again for the contribution! LGTM!

2024-03-20 16:59 UTC, merged

2024-03-26 14:37 UTC, viceice reviewed
broken because of a typo `enabled` vs `enable`

#24682