Bitnami/sealedsecrets Fix ServiceMonitor endpoint
bitnami/charts pull request #24653
Opened 2024-03-25 15:27 UTC by aneurinprice

### Description of the change

Change configures the container and service to work with the ServiceMonitor. By default it will configure the metrics on 8081.

### Benefits

The servicemonitor will actually work.

### Possible drawbacks

n/a

### Applicable issues

n/a

### Additional information

Currently, the serviceMonitor points towards port `8080` on the sealedSecrets service. Metrics are not served on that port.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-03-25 16:48 UTC, carrodher commented
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

2024-03-25 20:44 UTC, aneurinprice commented
@carrodher Fixed 👍

2024-04-02 07:56 UTC, migruiz4 commented
Hi @aneurinprice,

I see you included changes to the `bitnami/zookeeper` chart in this PR too.
I'm sorry but we can not accept PRs modifying more than one chart, so those changes would need to be submitted in a separate PR could you please fix that?

2024-04-02 09:02 UTC, aneurinprice commented
@migruiz4 My mistake, fixed 👍

2024-04-02 09:23 UTC, migruiz4 requested changes
I have noticed these changes are related to https://github.com/bitnami-labs/sealed-secrets/pull/1369.

I'm sorry but I can not accept this PR, as the approach we should follow should be to imitate upstream:
- Add a `metrics` containerPort 8081.
- Create a new `-metrics` service.
- Update the serviceMonitor to use the new metrics service.

Additionally, we should format those changes to follow our chart standards:
- Add control value `metrics.enabled`.
- Add value `containerPorts.metrics`.
- Format the new metrics service and its associated values according to our guidelines ([Example](https://github.com/bitnami/charts/blob/main/bitnami/drupal/templates/metrics-svc.yaml))

I know updating this PR may be too much to ask, so feel free to let me know if you would like to update this PR or close it, in which case I will submit the changes as soon as possible.

2024-04-02 10:40 UTC, aneurinprice commented
I'll take care of it.

2024-04-09 08:41 UTC, aneurinprice commented
@migruiz4 Ping

2024-04-22 09:24 UTC, migruiz4 commented on bitnami/sealed-secrets/Chart.yaml
> +version: 2.0.2
```suggestion
version: 2.1.0
```

2024-05-07 11:00 UTC, migruiz4 approved these changes
Thank you for applying the suggested changes!

2024-05-07 11:00 UTC, merged