[bitnami/thanos] Add custom tsdb path
bitnami/charts pull request #25334
Opened 2024-04-23 15:28 UTC by alecrajeev

### Description of the change

Adding an option for a custom tsdb path.

### Benefits

This allows a user to set a tsdb path for a custom volume mount.

### Possible drawbacks

### Applicable issues

### Additional information

This makes it much easier to set an ephemeral volume for the tsdb.

* https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-04-24 09:39 UTC, dgomezleon requested changes
Thank you for contributing. Please bump it as a minor version as it includes new values.

2024-04-24 09:39 UTC, dgomezleon commented on bitnami/thanos/Chart.yaml
> +version: 15.2.2
```suggestion
version: 15.3.0
```

2024-04-24 15:34 UTC, alecrajeev commented
> Thank you for contributing. Please bump it as a minor version as it includes new values.

good suggestion

2024-04-25 12:54 UTC, alecrajeev commented on bitnami/thanos/README.md
> +| `receive.tsdbPath`                                          | path to the time series database
thank you for fixing this!

2024-04-25 14:34 UTC, merged