[bitnami/argo-cd] Chart modification to activate external Redis
bitnami/charts pull request #25566
Opened 2024-05-06 14:28 UTC by myeong-han

### Description of the change
This PR contains changes to improve the issue of calling `externalRedis.host` without referencing `externalRedis.existingSecret` when `redis.enabled` specified in `values.yaml` is `false`.

### Benefits
When deploying argo-cd, you can use an existing Redis instead of deploying a new Redis.
<img width="752" alt="Screenshot 2024-05-06 at 11 22 03 PM" src="https://github.com/bitnami/charts/assets/31746222/afd68f77-89dc-4196-a314-e1364c58a445">
 

### Possible drawbacks

### Applicable issues

- fixes #15064

### Additional information
To enable externalRedis, two values in `values.yaml` must be disabled.
- `redis.enabled=false`
- `redisWait.enabled=false`

Specifies the label of externalRedis Service.
- `externalRedis.selector`

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-05-07 07:19 UTC, dgomezleon requested changes
Hi @myeong-han ,

I think you are assuming that Redis is always used (internal or external). Note that most of the `else` conditions should also validate if an external Redis is configured. Otherwise, the logic below should not be added. Could you please double-check it taking into account if Redis is not used?

2024-05-07 08:45 UTC, myeong-han commented
I hadn't thought about it. This is because the `argocd.redisHost` value used in `templates/server/deployment.yaml` was determined by `redis.enabled` in `./templates/_helpers.tpl`.

However, we confirmed that the value is not a problem even if redis is not used, so we did not modify the definition.

Please let me know if there is any mistake.

### Additional information
Required value
- `redis.enabled=false`
- `redisWait.enabled=false`
- `externalRedis.enabled=true`

2024-05-08 09:09 UTC, dgomezleon approved these changes
LGTM

2024-05-08 09:10 UTC, dgomezleon approved these changes

2024-05-08 09:25 UTC, merged