[bitnami/milvus] feat: config external kafka tls client certs setting…
bitnami/charts pull request #26118
Opened 2024-05-20 09:22 UTC by chenraoCR

…s (bitnami#26110)

### Description of the change

### Benefits

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-05-21 06:43 UTC, migruiz4 requested changes
Thank you for your contribution @chenraoCR! I have updated the comments at `milvus.prepareMilvusInitContainer` to use capital letters.

Additionally, I would like to request one change in this PR.

Instead of `{{- if (not (empty .Values.*)) }}` could you please use `{{- if .Values.* }}`? That would simplify the conditionals and help improve code readability.

2024-05-21 06:43 UTC, migruiz4 commented on bitnami/milvus/templates/_helpers.tpl
> +      # server tls certs settings
```suggestion
      # Milvus server TLS settings
```

2024-05-21 06:43 UTC, migruiz4 commented on bitnami/milvus/templates/_helpers.tpl
> +      # kafka settings
```suggestion
      # Kafka settings
```

2024-05-21 06:43 UTC, migruiz4 commented on bitnami/milvus/templates/_helpers.tpl
> +      # tls settings
```suggestion
      # Kafka TLS settings
```

2024-05-21 09:01 UTC, chenraoCR commented
> Thank you for your contribution @chenraoCR! I have updated the comments at `milvus.prepareMilvusInitContainer` to use capital letters.
> 
> Additionally, I would like to request one change in this PR.
> 
> Instead of `{{- if (not (empty .Values.*)) }}` could you please use `{{- if .Values.* }}`? That would simplify the conditionals and help improve code readability.

noted

2024-05-23 02:36 UTC, chenraoCR commented on bitnami/milvus/templates/_helpers.tpl
> +      # server tls certs settings
resolved

2024-05-24 14:22 UTC, chenraoCR commented
@migruiz4  i committed the PR for quite some time and updated the requested changes, could u please merge it?

2024-05-30 07:53 UTC, migruiz4 commented
Hi @chenraoCR,

I'm sorry for the inconvenience. We were having an issue with the CI/CD pipeline for Milvus and the tests were not passing due to a problem unrelated to this PR. 

Because the CI/CD pipeline would not succeed we couldn't merge this PR.

2024-06-03 09:31 UTC, chenraoCR commented
@migruiz4 now seems okay, plz check and merge, thanks

2024-06-06 07:40 UTC, migruiz4 approved these changes

2024-06-06 07:40 UTC, merged