[bitnami/superset] Add chart
bitnami/charts pull request #26713
Opened 2024-06-04 15:53 UTC by migruiz4

### Description of the change

Adds the bitnami/superset chart to the catalog.

2024-06-28 14:00 UTC, juan131 requested changes
Thanks for this great contribution! Please check my comments when you have a chance.

2024-06-28 14:00 UTC, juan131 commented on bitnami/superset/values.yaml
> +##
```suggestion
```

2024-10-29 19:39 UTC, LucasRakotomalala commented
Hello there,
I would like to know when this PR will be merged?

Kind regards,
Lucas.

2025-01-17 12:00 UTC, migruiz4 commented on .vib/superset/runtime-parameters.yaml
> +  enabled: true
I do not think there is an easy way to test them. 
See https://superset.apache.org/docs/configuration/async-queries-celery/ for more context.

Locally, I was able to enable 'Asynchronous Query Execution' and see that indeed Celery is handling the requests by monitoring it in the Flower UI:
![image](https://github.com/user-attachments/assets/c1a17734-1f15-4206-8ac8-2ee4ec95567d)

Not sure if it would be possible to perform that check using Cypress.

2025-01-17 14:50 UTC, migruiz4 commented on bitnami/superset/templates/web/service.yaml
> +      {{- end }}
As far a I know Apache superset does not have metrics.

2025-01-17 14:51 UTC, migruiz4 commented on bitnami/superset/README.md
> +The [Bitnami Superset](https://github.com/bitnami/containers/tree/main/bitnami/superset) image stores the Superset data and configurations at the `/bitnami` path of the container. Persistent Volume C
Actually, Superset does not have persistence, settings are stored in Redis/Postgresql.

2025-01-21 12:29 UTC, migruiz4 commented on bitnami/superset/templates/flower/networkpolicy.yaml
> +      {{- end }}
Updated using the latest version of `template/CHART_NAME/templates/networkpolicy.yaml` as reference.

2025-01-21 12:31 UTC, migruiz4 commented on bitnami/superset/templates/_helpers.tpl
> +{{- end -}}
Fixed the indent.

Both helpers are used, the first one is used inside the `superset.configure.common` helper.

The second one was missing the feature that allows overriding the configuration but is now used in all the deployments.

2025-01-23 10:18 UTC, juan131 requested changes

2025-01-23 10:18 UTC, juan131 commented on .vib/spark/vib-verify.json
> +          "path": "/bitnami/airflow"
I think you included these changes by mistake

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/Chart.yaml
> +icon: https://bitnami.com/assets/stacks/superset/img/superset-stack-220x234.png
Still missing icon

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/Chart.yaml
> +  licenses: Apache-2.0
I'm missing the "image" annotation listing the images included in the chart.

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/templates/NOTES.txt
> +  /opt/bitnami/scripts/superset/entrypoint.sh /opt/bitnami/scripts/superset/run.sh
Please double-check this is correct (some containers' initialization isn't based on bash logic)

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/README.md
> +- ReadWriteMany volumes for deployment scaling
This chart doesn't have a "persistence" section and the sub-charts (Redis and PostgreSQL) use StatefulSets with PVC Claim Templates, hence I don't think RWX is a requirement:
```suggestion
```

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/README.md
> +See <https://github.com/bitnami/readme-generator-for-helm> to create the table
Leftover:
```suggestion
```

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/README.md
> +The above command sets the Superset administrator account username and password to `admin` and `password` respectively. Additionally, it sets the MariaDB `root` user password to `secretpassword`.
Typo:
```suggestion
The above command sets the Superset administrator account username and password to `admin` and `password` respectively. Additionally, it sets the PostgreSQL user password to `secretpassword`.
```

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/templates/_helpers.tpl
> +{{- end -}}
Simpler:
```suggestion
{{ default (include "common.names.fullname" .) (tpl .Values.existingSecret .) -}}
```

2025-01-23 10:18 UTC, juan131 commented on bitnami/superset/templates/_helpers.tpl
> +{{- end -}}
Similar to previous comment:
```suggestion
{{ default (printf "%s-configuration" (include "common.names.fullname" .)) (tpl .Values.existingConfigmap .) -}}
```

2025-01-23 10:22 UTC, juan131 commented on bitnami/superset/templates/beat/pdb.yaml
> +  maxUnavailable: {{ .Values.beat.pdb.maxUnavailable }}
This doesn't follow the template:
```suggestion
  maxUnavailable: {{ .Values.beat.pdb.maxUnavailable | default 1 }}
```
Check other PDBs

2025-01-23 11:22 UTC, migruiz4 commented on bitnami/superset/Chart.yaml
> +  licenses: Apache-2.0
Isn't that added during the first automatic release?

2025-01-23 11:24 UTC, migruiz4 commented on bitnami/superset/templates/NOTES.txt
> +  /opt/bitnami/scripts/superset/entrypoint.sh /opt/bitnami/scripts/superset/run.sh
All containers are started with the command `/opt/bitnami/scripts/superset/entrypoint.sh /opt/bitnami/scripts/superset/run.sh`.

The environment variable `SUPERSET_ROLE` determines what command is executed at `run.sh`

2025-01-23 11:36 UTC, migruiz4 commented on bitnami/superset/Chart.yaml
> +icon: https://bitnami.com/assets/stacks/superset/img/superset-stack-220x234.png
Not anymore :)

2025-01-24 06:28 UTC, juan131 commented on bitnami/superset/Chart.yaml
> +  licenses: Apache-2.0
Given our "common.errors.insecureImages" helper relies on this information, I'd manually add it to ensure the mechanism works from the very beginning. Then, you can forget about this and rely on the automatic releases to update it.

2025-01-24 06:50 UTC, juan131 requested changes

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/_helpers.tpl
> +{{- end -}}
Ternary + templating:
```suggestion
{{- ternary "redis-password" (tpl .Values.externalRedis.existingSecretPasswordKey .) .Values.redis.enabled -}}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/_helpers.tpl
> +{{- end -}}
Ternary + templating:
```suggestion
{{- ternary "password" (tpl .Values.externalDatabase.existingSecretPasswordKey .) .Values.postgresql.enabled -}}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/_helpers.tpl
> +# it had the binary wait-for-port.
Typo, this init container uses PostgreSQL:
```suggestion
# NOTE: The value postgresql.image is not available unless postgresql.enabled is not set. We could change this to use os-shell if
# it had the binary wait-for-port.
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/_helpers.tpl
> +{{/* Validate values of Appsmith - Postgresql */}}
Typo:
```suggestion
{{/* Validate values of Superset - Postgresql */}}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/_helpers.tpl
> +{{/* Validate values of Appsmith - Redis */}}
Typo:
```suggestion
{{/* Validate values of Superset - Redis */}}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/flower/pdb.yaml
> +  maxUnavailable: {{ .Values.flower.pdb.maxUnavailable }}
You missed to update other PDBs:
```suggestion
  maxUnavailable: {{ .Values.flower.pdb.maxUnavailable | default 1 }}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/web/pdb.yaml
> +  maxUnavailable: {{ .Values.web.pdb.maxUnavailable }}
You missed to update other PDBs:
```suggestion
  maxUnavailable: {{ .Values.web.pdb.maxUnavailable | default 1 }}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/worker/pdb.yaml
> +  maxUnavailable: {{ .Values.worker.pdb.maxUnavailable }}
You missed to update other PDBs:
```suggestion
  maxUnavailable: {{ .Values.worker.pdb.maxUnavailable | default 1 }}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/flower/deployment.yaml
> +              value: "true"
Why is this hardcoded?

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/flower/vpa.yaml
> +    apiVersion: apps/v1
Do not hardcode api version (apply this to other VPAs):
```suggestion
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
```

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/flower/deployment.yaml
> +  name: {{ printf "%s-flower" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
I'd create a "superset.flower.fullname" helper for this (and for other components) so you avoid this piece of code on several places.

2025-01-24 06:50 UTC, juan131 commented on bitnami/superset/templates/secret.yaml
> +  {{- end }}
I don't think you need the if/else block if you use the "length" parameter:
```suggestion
  superset-secret-key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "superset-secret-key" "providedValues" (list "auth.secretKey") "length" 42 "context" $) }}

2025-01-27 09:56 UTC, javsalgar commented on bitnami/superset/templates/_helpers.tpl
> +    {{- default .Values.postgresql.primary.service.ports.postgresql ((((.Values.global).postgresql).service).ports).postgresql -}}
I would add `postgresql.primary.service.ports.postgresql` and `redis.master.service.ports.redis` to the values.yaml file.

2025-01-27 10:01 UTC, javsalgar commented on .vib/superset/goss/goss.yaml
> +  http://superset-web:80/health:
In other charts we also test the container port, using a different port from the default and doing http://127.0.0.1:{{vars.containerPorts.http}}

2025-01-27 10:02 UTC, javsalgar commented on bitnami/superset/templates/beat/deployment.yaml
> +  name: {{ printf "%s-beat" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
In other charts we create a macro like superset.beat.fullname for simplicity. The same wit the other componens

2025-01-27 10:04 UTC, javsalgar commented on bitnami/superset/templates/flower/deployment.yaml
> +        {{- if .Values.waitForDB.enabled }}
In newer charts we started creating a scetion called defaultInitContainers where we group all these init containers. You can check dremio for example.

2025-01-28 07:05 UTC, juan131 commented on bitnami/superset/templates/flower/deployment.yaml
> +              value: "true"
No answer

2025-01-28 07:06 UTC, juan131 commented on bitnami/superset/Chart.yaml
> +  licenses: Apache-2.0
Unresolved topic

2025-01-28 09:05 UTC, migruiz4 commented on bitnami/superset/templates/flower/deployment.yaml
> +              value: "true"
I didn't forget about this one. Main issue with flower auth is that it only support authentication via command line:
```
$ celery flower --basic-auth=user:pswd
```

If we added Flower user/password to the chart, it could be potentially exposed with `ps aux`.

Because of that, I would say the recommended method to add authentication if flower wants to be exposed publicly, should be using an additional reverse-proxy with HTTP basic auth.

2025-01-28 09:07 UTC, migruiz4 commented on bitnami/superset/templates/flower/deployment.yaml
> +              value: "true"
Nevermind, let me test a couple of alternatives first and will implement a solution that does not expose any credentials.

2025-01-28 15:27 UTC, javsalgar approved these changes

2025-01-28 15:31 UTC, merged