[bitnami/supabase] Do not render any resources for disabled components
bitnami/charts pull request #27580
Opened 2024-06-28 09:20 UTC by frittentheke

Skip rendering resources like network policies, services, secrets or even pvc for components 
(auth, meta, realtime, rest, storage, studio) which are disabled.

Resolves: #27540

### Description of the change

Add condition for a supabase component (auth, meta, realtime, rest, storage, studio) to be enabled, prior to rendering ayn resource for it.

### Benefits

No dangling and unused resources in Kubernetes.

### Possible drawbacks

I believe there are none 

### Applicable issues
- fixes #27540

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-07-03 11:13 UTC, jotamartos requested changes
Thanks for taking the time to create this PR. Please take a look at my suggestions

2024-07-03 11:13 UTC, jotamartos commented on bitnami/supabase/templates/studio/tls-secret.yaml
> +{{- if and .Values.studio.enabled .Values.studio.ingress.enabled }}
If you make this change, you need to remove the extra `{{- end}}` later in the code

2024-07-03 11:13 UTC, jotamartos commented on bitnami/supabase/templates/realtime/networkpolicy.yaml
> +{{- if and .Values.realtime.enabled.Values.realtime.networkPolicy.enabled }}
```suggestion
{{- if and .Values.realtime.enabled .Values.realtime.networkPolicy.enabled }}
```

2024-07-03 12:37 UTC, frittentheke commented
> Thanks for taking the time to create this PR. Please take a look at my suggestions
Thanks @jotamartos for your thorough review! 

I tried to fix all your findings, PTAL.

2024-07-03 12:37 UTC, frittentheke commented
> Thanks for taking the time to create this PR. Please take a look at my suggestions

Thanks @jotamartos for your thorough review! 
I tried to fix all your findings, PTAL.

2024-07-04 14:16 UTC, frittentheke commented on bitnami/supabase/Chart.yaml
> +version: 5.2.8
@jotamartos  Thanks for your patience - PTAL.

2024-07-04 15:08 UTC, jotamartos commented on bitnami/supabase/Chart.yaml
> +version: 5.2.8
You are completely right. I saw the "red line" on the left and thought you were removing the line. Everything is clear now.

2024-07-04 15:08 UTC, jotamartos commented
Thanks for your contribution

2024-07-04 15:08 UTC, merged