[bitnami/gitea] Update externaldb-secret logic
bitnami/charts pull request #27596
Opened 2024-06-29 14:30 UTC by speedythesnail

### Description of the change

Changes the logic in the creation of the externaldb-secrets.yaml, so the secret is not created if you are specifying an exisitng secret.

### Benefits

An unused blank-secret will not be created, contributing to reducing junk files.

### Possible drawbacks

None that I know of.

### Applicable issues

- fixes #27595

### Additional information

The chart is using the specified externaldb secret and key in the values.yaml, however it still creates an externaldb-secret, with no password. This fixes that.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-07-05 09:32 UTC, rafariossaa approved these changes
LGTM

2024-07-05 09:33 UTC, rafariossaa requested changes
Sorry for the delay,
Do you mind rebasing your changes ?

2024-07-09 09:34 UTC, rafariossaa commented
Yes, sometimes it happens to be a bunch of updates and this kind of issues appears.

Try deleting the Changelog and bumping the version in Chart.yaml.
The changelog should be autogenerated.

2024-07-10 08:52 UTC, carrodher commented
Bumping again the chart version in the _Chart.yaml_ to `2.3.12` should make the trick

2024-07-10 10:42 UTC, speedythesnail reviewed
Concur with chart version bump.

2024-07-10 10:46 UTC, speedythesnail commented
> Sorry for the delay, Do you mind rebasing your changes ?

Looks like @carrodher  bumped the chart versions, does this work for you?

2024-07-17 09:15 UTC, rafariossaa commented
Sorry, you need to rebase your change from `main` branch and bump chart version.
The changelog will be autogenerated, so you don't need to take care of it.

2024-08-08 19:53 UTC, gitmonster commented
Can we expect any progress on this?

2024-08-09 12:49 UTC, andresbono reviewed
Please, check my suggestion. If you agree, let's apply it and we can then resolve the conflicts and bump the chart version again.

Thank you!

2024-08-09 12:49 UTC, andresbono commented on bitnami/gitea/templates/externaldb-secrets.yaml
> +{{- if and (not .Values.postgresql.enabled) (and (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password) }}
I suggest this simpler version, there is no need to evaluate `.Values.externalDatabase.password` in this condition:

```suggestion
{{- if not (or .Values.postgresql.enabled .Values.externalDatabase.existingSecret) }}
```

2024-08-26 09:44 UTC, gitmonster commented
So please commit this feature. Storing credentials in a secret is essential if you intend to use a external database.

2024-09-02 07:47 UTC, carrodher commented
Please note a new version was released in the meantime, you need to bump the chart version in the _Chart.yaml_ again

2024-09-11 17:32 UTC, andresbono commented on bitnami/gitea/templates/externaldb-secrets.yaml
> +{{- if and (not .Values.postgresql.enabled) (and (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password) }}
Applied myself

2024-09-11 17:34 UTC, andresbono approved these changes
LGTM after applying a minor suggestion. Thank you!

2024-09-11 17:47 UTC, merged