[bitnami/logstash] Add extra inputs and ports to pod and svc
bitnami/charts pull request #27763
Opened 2024-07-04 13:49 UTC by maxnitze

### Description of the change

Add parameters for extra inputs and extra ports to Pods and Service.

### Benefits

Add extra ports for extra inputs without overwriting the default ones.

### Possible drawbacks

%

### Applicable issues

%

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-07-15 14:35 UTC, maxnitze commented
I have no idea why the VIB Verify check failed. Tried to check the logs, but cannot figure out what went wrong there...

2024-07-23 07:36 UTC, maxnitze commented on bitnami/logstash/Chart.yaml
> +  - https://github.com/bitnami/charts/tree/main/bitnami/logstash
Ah! I did not notice that. Sorry for that. Thanks for the fix!

2024-08-01 07:46 UTC, juan131 requested changes
@maxnitze could you please apply the changes below:
```
diff --git a/.vib/logstash/runtime-parameters.yaml b/.vib/logstash/runtime-parameters.yaml
index 8c4de9c57e..09161ddbbc 100644
--- a/.vib/logstash/runtime-parameters.yaml
+++ b/.vib/logstash/runtime-parameters.yaml
@@ -25,9 +25,6 @@ containerPorts:
   - name: http
     containerPort: 8081
     protocol: TCP
-  - name: monitoring
-    containerPort: 9600
-    protocol: TCP
 replicaCount: 1
 podSecurityContext:
   enabled: true
@@ -41,10 +38,11 @@ service:
       port: 8081
       targetPort: http
       protocol: TCP
+  extraPorts:
     - name: monitoring
       port: 80
       targetPort: monitoring
       protocol: TCP
   type: LoadBalancer
 persistence:
-  mountPath: /bitnami/logstash/data
\ No newline at end of file
+  mountPath: /bitnami/logstash/data
```
They'll be required given your changes for the CI to succeed

2024-08-01 13:45 UTC, juan131 approved these changes

2024-08-01 13:45 UTC, merged