[bitnami/minio]: Option to use a secret.
bitnami/charts pull request #27837
Opened 2024-07-08 11:27 UTC by ed382

### Description of the change

In some environments, Kubernetes secrets are not allowed and credentials are mounted using some other mechanism (i.e. Vault sidecar injector). 

### Benefits

This offers the option to operate without a Kubernetes secret.

### Possible drawbacks

n/a

### Applicable issues

n/a

### Additional information

n/a

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-07-08 12:21 UTC, carrodher commented
Thank you for initiating this pull request. We appreciate your effort.
There is automation in charge of automatically updating the README, CRDs and CHANGELOG, to be able to do that, it should commit to the branch from where the PR is created.

Usually, forks allow those commits by default, if there is any restriction in place you need to add @bitnami-bot as a collaborator in the [kubeshop/bitnami-charts](https://github.com/kubeshop/bitnami-charts/') repo

2024-07-23 07:23 UTC, alemorcuq requested changes

2024-07-23 07:23 UTC, alemorcuq commented on bitnami/minio/templates/standalone/deployment.yaml
> -            - name: minio-credentials
I think this is a typo.

2024-07-31 16:58 UTC, carrodher commented
Sorry for the late response, some conflicts need to be resolved before proceeding. Could you please rebase from the `main` branch? Thanks

2024-08-12 11:59 UTC, jotamartos submitted a review, later dismissed

2024-08-12 12:02 UTC, jotamartos commented
Changes look good to me but can you rebase your branch?

2024-08-12 15:33 UTC, jotamartos approved these changes
Thanks for your contribution.

2024-08-12 15:33 UTC, merged