[bitnami/harbor] Dont set redis DB if Sentinel is enabled
bitnami/charts pull request #27977
Opened 2024-07-15 13:42 UTC by MaxRink

### Description of the change

This removes the DB setting from the registry config if you are running with redis sentinel
### Benefits
 The current config does not allow setting an DB with sentinel enabled, as this happens
`[harbor-registry-7f6579568-slz9t] time="2024-07-15T13:41:40.380848854Z" level=error msg="redis: error connecting: ERR unknown command 'SELECT', with args beginning with: '2' " go.version=go1.22.5 instance.id=779d36f5-ca6e-431a-bbc1-e0e4f481b7d3 redis.connect.duration=2.407059ms service=registry version=v2.8.3`

Removing the DBkey fixes redis caching for the registry
### Possible drawbacks

none
### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-07-16 09:36 UTC, dgomezleon approved these changes
LGTM. Thanks for contributing!

2024-07-16 11:17 UTC, dgomezleon requested changes
Just a minor typo, but it breaks our tests. Could you please apply the change?

2024-07-16 11:17 UTC, dgomezleon commented on bitnami/harbor/templates/registry/registry-cm.yaml
> +      {{- if and (eq .Values.externalRedis.sentinel.enabled false) (eq .Values.redis.sentinel.enabled false) -}}
```suggestion
      {{- if and (eq .Values.externalRedis.sentinel.enabled false) (eq .Values.redis.sentinel.enabled false) }}
```

2024-07-16 14:30 UTC, dgomezleon approved these changes

2024-07-16 14:30 UTC, merged

2025-07-01 14:11 UTC, nasseredine commented
@MaxRink I'm experiencing what appears to be a regression related to this change. Could you please clarify the rationale behind completely removing the db parameter when using Redis Sentinel?