bitnami/kafka Fix pem auth with custom encrypted private key
bitnami/charts pull request #28618
Opened 2024-08-01 10:48 UTC by Voldemat

### Description of the change

Also fixed and error with openssl when using pem auth with custom key. Just provided necessary password from env

### Benefits

Allows to use pem authentication with custom encrypted private key

### Possible drawbacks

None to my knowledge

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-08-08 10:24 UTC, migruiz4 requested changes
Thank you for your contribution @Voldemat, but I'm afraid I cannot accept this contribution as it is.

While this may fix an issue when using password-protected PEM keys, it will then cause failures when non password-protected PEM keys are used.

I have suggested a small change that would fix this issue while preserving the both use cases.

2024-08-08 10:24 UTC, migruiz4 commented on bitnami/kafka/templates/scripts-configmap.yaml
> +          openssl pkcs8 -topk8 -nocrypt -passin pass:"${KAFKA_TLS_PEM_KEY_PASSWORD}" -in "/mounted-certs/kafka-${POD_ROLE}-${POD_ID}.key" > /certs/tls.key
```suggestion
          openssl pkcs8 -topk8 -nocrypt -passin pass:"${KAFKA_TLS_PEM_KEY_PASSWORD:-}" -in "/mounted-certs/kafka-${POD_ROLE}-${POD_ID}.key" > /certs/tls.key
```

2024-08-08 10:24 UTC, migruiz4 commented on bitnami/kafka/templates/scripts-configmap.yaml
> +          openssl pkcs8 -topk8 -passin pass:"${KAFKA_TLS_PEM_KEY_PASSWORD}" -nocrypt -in "/mounted-certs/kafka.key" > /certs/tls.key
```suggestion
          openssl pkcs8 -topk8 -passin pass:"${KAFKA_TLS_PEM_KEY_PASSWORD:-}" -nocrypt -in "/mounted-certs/kafka.key" > /certs/tls.key
```

2024-08-08 10:24 UTC, migruiz4 commented on bitnami/kafka/templates/scripts-configmap.yaml
> +          openssl pkcs8 -topk8 -passin pass:"${KAFKA_TLS_PEM_KEY_PASSWORD}" -nocrypt -in "/mounted-certs/tls.key" > /certs/tls.key
```suggestion
          openssl pkcs8 -topk8 -passin pass:"${KAFKA_TLS_PEM_KEY_PASSWORD:-}" -nocrypt -in "/mounted-certs/tls.key" > /certs/tls.key
```

2024-08-20 20:00 UTC, Voldemat commented
@migruiz4 Added request changes and merged upstream.

2024-08-23 09:23 UTC, migruiz4 approved these changes
Thank you for applying the suggestions @Voldemat, looks good to me!

2024-08-23 09:30 UTC, merged