[bitnami/nginx] stream server blocks
bitnami/charts pull request #29491
Opened 2024-09-18 07:00 UTC by TrueGameover

### Description of the change

Configuration allowed for stream server blocks in nginx container.

### Benefits

Can configure stream server blocks.

### Possible drawbacks

no

### Applicable issues

### Additional information

https://github.com/bitnami/containers/pull/72353

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-09-19 11:01 UTC, jotamartos submitted a review, later dismissed
Changes LGTM, just a minor suggestion

2024-09-19 11:02 UTC, jotamartos requested changes
Please bump the version of the Chart, there was a new release in the meantime.

2024-09-20 04:34 UTC, TrueGameover commented on bitnami/nginx/templates/deployment.yaml
> +            {{- end }}
ok, I changed it

2024-09-20 08:42 UTC, jotamartos commented on bitnami/nginx/Chart.yaml
> +version: 18.1.16
As you are adding new parameters, we need to use a new minor version

```suggestion
version: 18.2.0
```

2024-09-20 08:47 UTC, jotamartos approved these changes

2024-09-20 08:54 UTC, merged