[bitnami/mlflow] Adding missing Azure Storage configuration in the Helm Chart
bitnami/charts pull request #29626
Opened 2024-09-26 14:46 UTC by eriadam

### Description of the change

The PR adds the missing configuration options for the Azure Storage Account in the MLFlow helm chart.

### Benefits

As explained in the ticket #28569, Azure Storage is supported by MLFlow, but it is not currently possible to configure it via the Helm chart. With this change Azure Blob Storage can be configured to store the artefacts of MLFlow.

### Possible drawbacks

### Applicable issues

- fixes #28569

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-10-17 08:00 UTC, eriadam commented
@carrodher could you please have a look at this?

2024-10-18 12:36 UTC, carrodher commented
Sorry, we didn't take a look because it is in Draft state:
```
This pull request is still a work in progress
Draft pull requests cannot be merged.
```

If you think it is ready, could you please mark it as _Ready for review_?

2024-10-18 15:05 UTC, eriadam commented
@carrodher Thanks, it was a draft because of the last open question in here: https://github.com/bitnami/charts/issues/28569#issuecomment-2377198138

Any feedback on that is much appreciated!

2024-10-18 15:28 UTC, carrodher commented
Thanks! To review it in the proper status, could you please rebase from the latest changes? Apart from that, please note it's needed to grant permissions to @bitnami-bot to update your fork so it can automatically update the README, CRDs, and CHANGELOG

2024-10-18 15:51 UTC, eriadam commented
OK, I think both are done!

2024-10-24 06:59 UTC, eriadam commented
@carrodher I did both. I added bitnami bot as a member, is that OK?

2024-10-25 14:46 UTC, jotamartos requested changes
Changes LGTM but you need to rebase your branch with the latest changes in stable due to there was a new version of MLflow and there are conflicts.

2024-11-08 11:55 UTC, eriadam commented
@jotamartos Could you please have a look?

2024-11-14 09:26 UTC, jotamartos requested changes

2024-11-14 09:26 UTC, jotamartos commented on bitnami/mlflow/Chart.yaml
> +version: 2.1.1
```suggestion
version: 2.2.0
```

2024-11-14 09:26 UTC, jotamartos commented on bitnami/mlflow/templates/tracking/deployment.yaml
> +
```suggestion
```

2024-11-14 09:26 UTC, jotamartos commented on bitnami/mlflow/templates/tracking/deployment.yaml
> +
```suggestion
```

2024-11-14 09:26 UTC, jotamartos commented on bitnami/mlflow/templates/tracking/deployment.yaml
> +
```suggestion
```

2024-11-14 09:27 UTC, jotamartos commented on bitnami/mlflow/Chart.yaml
> +version: 2.1.1
Please bump the chart to a new minor as you are adding new parameters

2024-11-14 12:59 UTC, eriadam commented
@ jotamartos Thank you, I added the changes.

2024-11-15 10:58 UTC, jotamartos approved these changes

2024-11-15 12:21 UTC, merged