[bitnami/kibana] set base host to 0.0.0.0
bitnami/charts pull request #30023
Opened 2024-10-21 15:05 UTC by mike12806

### Description of the change

This change defaults the host value to 0.0.0.0 instead of `::` in the configmap because unless folks have ipv6 enabled, :: causes Kibana to fail on startup. 

### Benefits

The majority of the world is using IPV4 and this is a more sane default. If needed, folks can update for IPV6 compatability manually. 

### Possible drawbacks

### Applicable issues

- fixes #17375

### Additional information

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-10-28 07:52 UTC, jotamartos requested changes
Thank you for taking the time to contribute to this project. Please take a look at my comments

2024-10-28 18:26 UTC, mike12806 commented on bitnami/kibana/templates/configmap.yaml
> +    server.host: "0.0.0.0"
Yeah I could do that - so you're thinking have it be a parameter under configuration.server, maybe with a default value of "0.0.0.0"? I like that

2024-10-29 07:02 UTC, jotamartos requested changes
Please take a look at the minor suggestion I added and fix the DCO issue

2024-10-29 07:02 UTC, jotamartos commented on bitnami/kibana/templates/configmap.yaml
> +    server.host: {{ .Values.configuration.server.host }}
```suggestion
    server.host: {{ .Values.configuration.server.host | quote }}
```

2024-10-30 01:57 UTC, mike12806 commented
@jotamartos I'll bring these changes into a new PR / branch in a few days as my re-base here got a bit messy trying to fix the DCO issue.

2024-10-30 02:09 UTC, mike12806 commented
Closing in favor of https://github.com/bitnami/charts/pull/30131

2024-10-30 02:09 UTC, closed without merging