[bitnami/redis] fix: update JSON schema to allow string values for values passed to tpl
bitnami/charts pull request #30526
Opened 2024-11-19 14:05 UTC by piccit

### Description of the change

Updates all properties in values.schema.json that are directly passed to `tpl` to also allow for string fields.

### Benefits

Fixes schema to allow passing strings to `tpl` for all values that are template-able

### Possible drawbacks

None

### Applicable issues

- fixes #29451

### Additional information

None

### Checklist

- [x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-11-26 12:44 UTC, jotamartos requested changes
Thank you for taking the time to contribute but I can approve this change, sorry. There are many parameters from there that do not support a simple string to configure them (hostAliases, customLivenessProbe, customRedinessProbe, extraEnvVars, ...). As you can see, those are objects/arrays that you need to define in the values.yaml file when deploying the solution.

2024-12-21 01:33 UTC, piccit commented
Bump @jotamartos, please re-open and re-review per the linked issues and pr

2025-01-14 14:42 UTC, jotamartos commented
Sorry for the late reply here. I've checked the issues you shared and you are completely right. It's important to take into account what @migruiz4 mentioned in https://github.com/bitnami/charts/pull/27441 but all in all this PR is completely legit. Please bump the branch and update the version so I merge the changes.

2025-01-14 14:44 UTC, jotamartos commented
Update: I could resolve the conflicts using the UI and the changelog will be automatically generated soon. If tests pass, I'll merge the changes

2025-01-14 15:00 UTC, jotamartos approved these changes

2025-01-14 15:07 UTC, merged

2025-01-28 20:19 UTC, Stevenpc3 commented
I had this issue and planned to fix a while ago but it appeared there would be way to many things to update https://github.com/bitnami/charts/issues/29952