[bitnami/mariadb] feat: :sparkles: Add TLS support
bitnami/charts pull request #30629
Opened 2024-11-26 15:52 UTC by javsalgar

Signed-off-by: Javier J. Salmerón García <javier.salmeron@broadcom.com>

### Description of the change

This PR adds the `tls` section in MariaDB. Just like in other charts, we allow using autogenerated helm values and integration with cert-manager. 

### Benefits

Better security

### Possible drawbacks

n/a

### Applicable issues

- fixes #

### Additional information

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-11-26 16:04 UTC, dgomezleon commented on bitnami/mariadb/templates/_helpers.tpl
> +Return the MariaDB TLS credentials secret
```suggestion
Return the MariaDB TLS CA credentials secret
```

2024-11-26 16:09 UTC, juan131 requested changes

2024-11-26 16:11 UTC, javsalgar commented on bitnami/mariadb/templates/cert.yaml
> +      - "ScyllaDB"
Fixed

2024-11-26 16:13 UTC, javsalgar commented on bitnami/mariadb/templates/tls-secret.yaml
> +{{- end }}
Actually this solution does not differentiate between client and server encryption, se we could delete the client certificate

2024-11-26 16:20 UTC, juan131 commented on bitnami/mariadb/templates/primary/statefulset.yaml
> +              mountPath: /bitnami/mariadb/ca
it makes sense to me since it's nothing we persist

2024-11-26 16:24 UTC, javsalgar commented on bitnami/mariadb/values.yaml
> +  existingCASecret: ""
Done

2024-11-26 16:45 UTC, juan131 requested changes

2024-11-26 16:45 UTC, juan131 commented on bitnami/mariadb/README.md
> +It is necessary to create a secret containing the TLS certificates and pass it to the chart via the `tls.existingSecret` parameter. Every secret should contain a `tls.crt` and `tls.key` keys includin
```suggestion
It is necessary to create a secret containing the TLS certificates and pass it to the chart via the `tls.existingSecret` parameter. Every secret should contain a `tls.crt` and `tls.key` keys including the certificate and key files respectively and, optionally, a `ca.crt` key including the CA certificate. For example: create the secret with the certificates files:

2024-11-26 16:45 UTC, juan131 commented on bitnami/mariadb/templates/_helpers.tpl
> +{{- end -}}
Remove this, not needed

2024-11-26 16:45 UTC, juan131 commented on bitnami/mariadb/templates/primary/statefulset.yaml
> +            {{- end }}
Is this mandatory? could be the ca optional? Some CertManager issuers don't include the CA in the secret.

2024-11-26 16:45 UTC, juan131 commented on bitnami/mariadb/templates/primary/statefulset.yaml
> +            defaultMode: 256
Remove this block

2024-11-26 16:45 UTC, juan131 commented on bitnami/mariadb/templates/primary/statefulset.yaml
> +              mountPath: /opt/bitnami/mariadb/ca
Remove this block

2024-11-26 16:45 UTC, juan131 commented on bitnami/mariadb/values.yaml
> +    ssl_ca=/opt/bitnami/mariadb/ca/{{ .Values.tls.certCAFilename }}
```suggestion
    ssl_ca=/opt/bitnami/mariadb/cert/{{ .Values.tls.certCAFilename }}
```

2024-11-26 16:45 UTC, juan131 commented on bitnami/mariadb/values.yaml
> +    ssl_ca=/opt/bitnami/mariadb/ca/{{ .Values.tls.certCAFilename }}
```suggestion
    ssl_ca=/opt/bitnami/mariadb/cert/{{ .Values.tls.certCAFilename }}
```

2024-11-26 16:57 UTC, juan131 requested changes

2024-11-26 17:12 UTC, juan131 approved these changes
Great! LGTM

2024-11-27 07:20 UTC, juan131 approved these changes

2024-11-27 07:20 UTC, merged