[bitnami/kibana] template server.publicBaseUrl in all variants
bitnami/charts pull request #30807
Opened 2024-12-05 17:00 UTC by jplitza

### Description of the change

Previously, if `.Values.extraConfiguration."server.publicBaseUrl"` was specified (with a dot in the key), that key was inserted into the configmap twice, causing Kibana to error out.

Furthermore, since the introduction of the fallback to the ingress hostname, this setting couldn't be templated anymore (which was possible before).

This commit allows the templating as well as specifying it with the dot notation.

### Benefits

Upgrades from old chart versions that specified the dotted extraConfiguration won't break the deployment.

Also, templating the publicBaseUrl is possible again.

### Possible drawbacks

None.

### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2025-01-09 14:35 UTC, jplitza commented
Wow, auto-closing due to staleness over the holidays... thanks.

@carrodher @gongomgra Do you have the permissions to "reopen" this PR, as suggested? Because I don't.

2025-01-21 15:17 UTC, gongomgra requested changes
Thanks for your contribution! I have added a couple of comments to your changes.

2025-01-21 15:17 UTC, gongomgra commented on bitnami/kibana/templates/configmap.yaml
> +    {{- if or .Values.configuration.server.publicBaseUrl ( get .Values.configuration "server.publicBaseUrl" ) .Values.ingress.enabled }}
Please use the `coalesce` method here

2025-01-21 15:17 UTC, gongomgra commented on bitnami/kibana/templates/configmap.yaml
> +    server.publicBaseUrl: {{ include "common.tplvalues.render" ( dict "value" ( or .Values.configuration.server.publicBaseUrl ( get .Values.configuration "server.publicBaseUrl" ) .Values.ingress.host
Not sure if we should accept `"server.publicBaseUrl"` as a valid value. We would have to accept it (or even add it) for all other parameters in our charts. Can you provide us with more details on why do you need that format to be available? My understanding is that the format of the current `values.yaml` file is simple enough.

```
## @param configuration [object] Kibana configuration
##
configuration:
  server:
    basePath: ""
    host: "0.0.0.0"
    publicBaseUrl: ""
    rewriteBasePath: false
```

2025-01-23 09:09 UTC, carrodher commented
Thank you for initiating this pull request. We appreciate your effort. This is just a friendly reminder that signing your commits is important. Your signature certifies that you either authored the patch or have the necessary rights to contribute to the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

2025-02-11 08:40 UTC, gongomgra commented on bitnami/kibana/templates/configmap.yaml
> +    server.publicBaseUrl: {{ include "common.tplvalues.render" ( dict "value" ( or .Values.configuration.server.publicBaseUrl ( get .Values.configuration "server.publicBaseUrl" ) .Values.ingress.host
I've been checking this with a teammate and he has some concerns on these changes. He wonders if there would be a value collision in case `server.publicUrl` is also set in extraConfig. @javsalgar can you provide further details?

2025-02-19 09:33 UTC, gongomgra commented on bitnami/kibana/templates/configmap.yaml
> +    server.publicBaseUrl: {{ include "common.tplvalues.render" ( dict "value" ( or .Values.configuration.server.publicBaseUrl ( get .Values.configuration "server.publicBaseUrl" ) .Values.ingress.host
@jplitza can you check my comment when you have a chance?

2025-02-19 09:58 UTC, jplitza commented on bitnami/kibana/templates/configmap.yaml
> +    server.publicBaseUrl: {{ include "common.tplvalues.render" ( dict "value" ( or .Values.configuration.server.publicBaseUrl ( get .Values.configuration "server.publicBaseUrl" ) .Values.ingress.host
@gongomgra I didn't understand the comment last week. But while writing this comment, I think I understood the problem: While we use the correct Helm value here if it's specified in `extraConfiguration`,  it will still be pasted twice into the `kibana.yml`. I will remove the coalesce here.

IMO, when you add new keys to the `kibana.yml` that someone could have specified in `extraConfiguration` before (like `server.publicBaseUrl` here), you should increase the major version of this chart. I tried to make that change backwards compatible with this PR, but that's simply not possible.

2025-02-20 10:33 UTC, gongomgra commented
@jplitza it looks like your changes are failing for the `helm lint` action, while it doesn't fail in `main` branch. Can you check it?

```
$ gh pr checkout https://github.com/bitnami/charts/pull/30807
$ helm lint .
==> Linting .
[ERROR] templates/: parse error at (kibana/templates/configmap.yaml:23): unexpected right paren

Error: 1 chart(s) linted, 1 chart(s) failed
```

2025-02-20 11:00 UTC, jplitza commented
Sorry, there indeed was a spurious `)`. Removed it.

2025-02-24 13:26 UTC, gongomgra approved these changes
Thanks for your contribution!

2025-02-24 13:26 UTC, merged