[bitnami/grafana-tempo] support new deployment mode: scaling-monolithic
bitnami/charts pull request #31028
Opened 2024-12-13 02:52 UTC by rim99

### Description of the change

This change provide a new way of deployment: `scaling-monolithic`.

If toggle `.Values.tempo.deploymentMode`, which is "microservices" by default, is set as "scalingMonolithic", single statefulset will be created. Each pod conatins all functions of components: distributor, ingester, query-frontend, querier, metrics-generator and compactor.

### Benefits

 It helps to to maintain a reasonable size of cluster handling small to medium volumes of incoming traces.

### Possible drawbacks

### Applicable issues

- fixes #30855

---

### Additional information

- [Official Doc](https://grafana.com/docs/tempo/latest/setup/deployment/#scaling-monolithic-mode)

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-12-13 07:41 UTC, carrodher commented
Thank you for this significant contribution, @rim99! The PR is currently in draft status. Please inform us when it's ready for testing and review. Thanks once more!

2024-12-13 08:08 UTC, rim99 commented
Hi @jotamartos @migruiz4 , I've tested my changes with minikube locally. New statefulset works fine as a cluster.

Regarding the VIB test, how to achieve 2 different sets of env for testing?

Since it should test both cases: 
- tempo.deploymentMode=microservices 
- tempo.deploymentMode=scalingMonolithic

2024-12-29 02:58 UTC, rim99 commented
Hello, just a reminder that this PR is ready for review
@jotamartos @migruiz4 @carrodher

2025-01-14 15:22 UTC, jotamartos commented
Hi @rim99,

Thanks for your contribution and sorry for the delay in getting back to you. We are going to start reviewing the changes and will provide feedback as soon as possible.

2025-01-15 09:30 UTC, jotamartos requested changes
Please take a look at my suggestions

2025-01-15 09:30 UTC, jotamartos commented on bitnami/grafana-tempo/templates/scaling-monolithic/headless-service.yaml
> +    ## From here we use non-configurable, standard ports
I'm not sure about having all these ports here. As far as I understand, the headless service should only have the Query Frontend's service ports as we currently have in the `templates/query-frontend/headless-service.yaml` file. Are the rest of ports needed?

2025-01-19 02:32 UTC, rim99 commented on bitnami/grafana-tempo/templates/NOTES.txt
>  {{- include "grafana-tempo.validateValues" . }}
done

2025-01-19 02:32 UTC, rim99 commented on bitnami/grafana-tempo/templates/compactor/deployment.yaml
>  {{- if .Values.compactor.enabled }}
done

2025-01-19 02:32 UTC, rim99 commented on bitnami/grafana-tempo/templates/scaling-monolithic/headless-service.yaml
> +  namespace: {{ .Release.Namespace | quote }}
done

2025-01-19 02:36 UTC, rim99 commented on bitnami/grafana-tempo/templates/scaling-monolithic/headless-service.yaml
> +    ## From here we use non-configurable, standard ports
That was to keep align with the ClusterIP service, so `extraPorts` can affect both  the ClusterIP service and the headless service.
I changed this, to keep minimal required ports. And added new variable in `values.yaml`, to allow to set extra ports for headless service specifically

2025-02-16 01:37 UTC, rim99 commented
Any progress?

2025-03-27 03:13 UTC, closed without merging