[bitnami/mongodb] Enable publishNotReadyAddresses for ClusterIP services
bitnami/charts pull request #31145
Opened 2024-12-23 10:26 UTC by janvotava

### Description of the change

When MongoDB replicaset hosts configuration points to services (rather than pods on headless service) for inter-cluster communication (through tunnel for example), a deadlock can occur when majority Pods fail at once since services won't publish addresses until pods are ready.

This change prevents deadlocks by allowing MongoDB instances to discover each other during startup and keeps it similar to NodePort/Loadbalancer logic in external mode.

### Benefits

Makes ClusterIP external replicaset mode more resilient.

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-12-23 18:42 UTC, carrodher commented
Thank you for initiating this pull request. We appreciate your effort. This is just a friendly reminder that signing your commits is important. Your signature certifies that you either authored the patch or have the necessary rights to contribute to the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

2024-12-23 18:44 UTC, janvotava commented
> Thank you for initiating this pull request. We appreciate your effort. This is just a friendly reminder that signing your commits is important. Your signature certifies that you either authored the patch or have the necessary rights to contribute to the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).
> 
> Feel free to reach out if you have any questions or need assistance with the signing process.

There's no correct sign-off?

2024-12-23 18:49 UTC, carrodher commented
[Here](https://github.com/bitnami/charts/pull/31145/checks?check_run_id=34791016255) you can see the failing GH Action and some tips about how to remediate it

2024-12-23 18:53 UTC, janvotava commented
Sorry, wrong email. 🫣 Should be fixed now.

2025-01-08 06:23 UTC, janvotava commented
Please don't close this PR.

2025-01-23 11:45 UTC, gongomgra requested changes

2025-01-23 11:45 UTC, gongomgra commented on bitnami/mongodb/templates/replicaset/svc.yaml
> +  publishNotReadyAddresses: true
Instead of always setting the parameter to true, can you parameterize it (with default to `false`)? This way we maintain the current behavior and it can be set in an easy way when required.

2025-01-23 11:52 UTC, janvotava commented on bitnami/mongodb/templates/replicaset/svc.yaml
> +  publishNotReadyAddresses: true
I can do that. But I wonder, what's the use case for the current behavior - could changing the default false -> true potentially be a breaking change?

2025-01-23 16:59 UTC, gongomgra commented on bitnami/mongodb/templates/replicaset/svc.yaml
> +  publishNotReadyAddresses: true
The thing is that we have not being reported with any issue related to current setup, so to be on the safe side I think it is worth it to keep it this way for now yet allowing users to customize it.

2025-02-08 09:15 UTC, janvotava commented
The flag to configure `publishNotReady` for SVC should be there. Given rest of the service configuration, I did not nest it under the `external` property and I did also add it to standalone SVC config to keep it consistent. Do I need to add something to `values.schema.json` file too?

2025-02-11 09:24 UTC, gongomgra commented
Please rebase your branch with `main` and fix the conflicts so we can merge your contribution. There's no need to update the `values.schema.json` file.

2025-02-19 08:52 UTC, gongomgra approved these changes

2025-02-19 08:53 UTC, merged