[bitnami/etcd] Add pre-upgrade hook
bitnami/charts pull request #31161
Opened 2024-12-26 04:49 UTC by pckhoi

### Description of the change

- Add a pre-upgrade hook that removes obsolete members when scaling down the cluster. It runs `preupgrade.sh` - a new script added in https://github.com/bitnami/containers/pull/75906
- Remove pre-stop hook
- Remove `removeMemberOnContainerTermination` parameter
- Remove `initialClusterState` parameter

### Benefits

Benefits are described more extensively in https://github.com/bitnami/containers/pull/75906 but here are the main points:

- Removing members in pre-upgrade hook is more reliable and with fewer edge cases than in pre-stop hook
- It is far safer to query other members to know whether the cluster is new than to rely on `initialClusterState` parameter

### Possible drawbacks

- If during initialization, the member cannot connect to other members because of a network outage then it will think that it is starting a new cluster. However, I don't think there is any good solution there except manual recovery.

### Applicable issues

- fixes #16069 

### Additional information

⚠️ It's needed to cut a new bitnami/common release and use it in this chart, see https://github.com/bitnami/charts/pull/31164

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

2024-12-26 08:07 UTC, carrodher commented
Thanks for your contribution!! Just so you know, to run our test suite, separate PRs per chart must be created. In this case, two different PRs are required: one for common and another one for etcd.

2024-12-26 08:39 UTC, pckhoi commented
Sure, I have just created this one: https://github.com/bitnami/charts/pull/31164

2024-12-30 09:53 UTC, juan131 commented
Thanks so much for this great contribution! I added some comments in the associated PR for the container.

2025-01-13 09:38 UTC, juan131 requested changes
Thanks for the PR! Please check my comments

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: {{ printf "%s-pre-upgrade" (include "common.names.fullname" .) | quote }}
I don't think these env. vars are required to execute the `preupgrade.sh` script, right?

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: "/bitnami/etcd/data"
Same here, I don't think they're required.

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: {{ ternary "yes" "no" (and (not (or .Values.auth.rbac.create .Values.auth.rbac.enabled)) .Values.auth.rbac.allowNoneAuthentication) | quote }}
Also unrequired

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: {{ .Values.initialClusterToken | quote }}
Unrequired too

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +            {{- end }}
Please ensure only TLS env. vars required for etcd client are set

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +            {{- end }}
Unrequired

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +        {{- end }}
Unrequired

2025-01-13 09:38 UTC, juan131 commented on bitnami/etcd/README.md
> +- Remove `removeMemberOnContainerTermination` which was unreliable at removing stale members during replica count updates. Instead, a pre-upgrade hook is added to check and remove stale members.
Add a comment warning users that scaling is no longer supported via `kubectl` or autoscaler, similar to what you did in the container PR:

```
Upgrading of any kind including increasing replica count must also be done with `helm upgrade` exclusively. CD automation tools that respect Helm hooks such as ArgoCD can also be used.
```

2025-01-14 13:14 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: "/bitnami/etcd/data"
`ETCD_DATA_DIR` is needed to support `autoTLS`

2025-01-14 13:14 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: {{ printf "%s-pre-upgrade" (include "common.names.fullname" .) | quote }}
agreed

2025-01-14 13:15 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: {{ ternary "yes" "no" (and (not (or .Values.auth.rbac.create .Values.auth.rbac.enabled)) .Values.auth.rbac.allowNoneAuthentication) | quote }}
agreed

2025-01-14 13:15 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +              value: {{ .Values.initialClusterToken | quote }}
agreed

2025-01-14 13:15 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +            {{- end }}
I have removed all unrequired env vars I think

2025-01-14 13:16 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +        {{- end }}
agreed

2025-01-14 15:20 UTC, juan131 reviewed
A few extra minor comments. I'll start doing some tests to double-check we're ready to merge both PRs

2025-01-14 15:20 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +      name: {{ include "common.names.fullname" . }}-pre-upgrade
Redundant field (you're using the same name used for the job):
```suggestion
```

2025-01-14 15:20 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +    "context" $) | nindent 4 }}
Please use the alternative below:
```suggestion
  {{- $defaultAnnotations := dict "helm.sh/hook" "pre-upgrade" "helm.sh/hook-delete-policy" "hook-succeeded" }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonAnnotations $defaultAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
```
Please note I switched the delete policy given I don't think the job is required after it succeeds.

2025-01-14 15:20 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +        {{- $etcdClientProtocol := include "etcd.clientProtocol" . }}
This variable isn't used"
```suggestion
```

2025-01-15 01:17 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +    "context" $) | nindent 4 }}
[Argo CD docs](https://argo-cd.readthedocs.io/en/latest/user-guide/helm/#hook-tips) recommend setting this value to `before-hook-creation` to make sure it runs on every sync. I think it's a sensible default. Perhaps, we should allow customization via Helm values?

2025-01-15 07:40 UTC, juan131 commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +    "context" $) | nindent 4 }}
Feel free to keep it with `before-hook-creation`. Actually, it's good to keep the "completed" pods to inspect the logs under certain circumstances.
Please apply the other suggestion for using `common.tplvalues.merge` to merge annotations.

2025-01-16 02:31 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +        {{- $etcdClientProtocol := include "etcd.clientProtocol" . }}
Removed

2025-01-16 02:32 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +    "context" $) | nindent 4 }}
Suggestion applied ;)

2025-01-16 02:32 UTC, pckhoi commented on bitnami/etcd/templates/preupgrade-hook-job.yaml
> +      name: {{ include "common.names.fullname" . }}-pre-upgrade
Removed

2025-01-16 07:15 UTC, juan131 approved these changes
LGTM! Thanks so much for applying the feedback.

We won't merge this PR until we release a new container revision including the changes at https://github.com/anchore/vunnel/pull/512 and we update `image.tag` in the values.

2025-01-20 08:44 UTC, juan131 commented
@pckhoi could you update the image tags below so we use the `r4` image revision? Thanks in advance

- https://github.com/bitnami/charts/blob/main/bitnami/etcd/values.yaml#L89
- https://github.com/bitnami/charts/blob/main/bitnami/etcd/Chart.yaml#L9

2025-01-20 10:09 UTC, merged

2025-01-20 11:19 UTC, juan131 commented
@pckhoi finally the etcd chart version `11.0.0` was released! Thanks so much for this awesome contribution

2025-01-20 11:22 UTC, pckhoi commented
Awesome! Couldn't have done it without you 🎉

On Mon, Jan 20, 2025, 6:19 PM Juan Ariza Toledano ***@***.***>
wrote:

> @pckhoi <https://github.com/pckhoi> finally the etcd chart version 11.0.0
> was released! Thanks so much for this awesome contribution
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bitnami/charts/pull/31161#issuecomment-2602151080>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC2RBCPC2XP57VVNTOGIIL2LTLUTAVCNFSM6AAAAABUGWAKV2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMBSGE2TCMBYGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>