Allow pod annotations for Airflow workers
bitnami/charts pull request #3514
Opened 2020-08-25 13:50 UTC by pankajkoti

Currently pod annotations cannot be given to Airflow workers. This is a PR to facilitate this use case

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-08-25 14:55 UTC, pankajkoti commented
looks like the test is failing in the pipeline as resources cannot connect to Postgres. Can someone please review this? Thank you!

2020-08-26 08:07 UTC, miguelaeh requested changes
Thank you very much for the PR!!
Please take a look at my comment.

2020-08-26 08:07 UTC, miguelaeh commented on bitnami/airflow/templates/statefulset-worker.yaml
> +      annotations: {{- toYaml .Values.airflow.worker.podAnnotations | nindent 8 }}
Please consider using the following:
```suggestion
      annotations: {{- include "airflow.tplValue" (dict "value" .Values.airflow.worker.podAnnotations "context" $) | nindent 8 }}
```

2020-08-26 08:12 UTC, miguelaeh approved these changes
LGTM!

2020-08-26 08:14 UTC, pankajkoti commented
@miguelaeh can you please check if the Chart version is correct? And if yes, can you please also merge my request? I can use this chart in my code then. Thank you!

2020-08-26 08:19 UTC, miguelaeh commented
Sure! I was waiting for the test to be passed.

2020-08-26 08:19 UTC, merged

2020-08-26 08:25 UTC, pankajkoti commented
@miguelaeh Thanks for approving. Is it possible to make a release? or it would automatically in some time? Can I get some idea on how much time it would take approx. Thank you!

2020-08-26 08:36 UTC, pankajkoti commented
I see bitnami/bot is creating releases. Hope it makes one soon :))

2020-08-27 06:27 UTC, miguelaeh commented
Hi @pankajkoti ,
it is an automatic process. I can see the `6.4.0` version has been already released.
Regards.