[bitnami/mariadb] Fix annotation for replica statefulset
bitnami/charts pull request #3569
Opened 2020-08-31 16:37 UTC by bergemalm

**Description of the change**

Currently annotations are treated differently in the master vs slave statefulset template. This also causes issues with generating slave manifest when having annotations not using strict key: value format.

**Benefits**
No discrepancy in templating slave annotations vs master statefulsets and generating slave manifest works when for example using multi-line value.

**Possible drawbacks**

**Applicable issues**
**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2020-09-01 08:24 UTC, miguelaeh requested changes
Thank you very much for the PR!!
I think it would be nice if you apply the sugestions to use our standard way, also, it would be nice if you ould make the proper change for the master too.
You can check this: https://github.com/bitnami/charts/blob/4e3eefc450b111a70b1ac9a58da0a1ff75a65c38/bitnami/mariadb-galera/templates/statefulset.yaml#L20
that will render whatever is put at podAnnotations: https://github.com/bitnami/charts/blob/4e3eefc450b111a70b1ac9a58da0a1ff75a65c38/bitnami/mariadb-galera/values.yaml#L401

2020-09-01 08:24 UTC, miguelaeh commented on bitnami/mariadb/templates/slave-statefulset.yaml
> +      {{- with .Values.slave.annotations }}
```suggestion
      {{- if .Values.slave.annotations }}
```

2020-09-01 08:24 UTC, miguelaeh commented on bitnami/mariadb/templates/slave-statefulset.yaml
> +        {{- toYaml . | nindent 8 }}
```suggestion
        annotations: {{- include "mariadb.tplValue" (dict "value" .Values.slave.annotations "context" $) | nindent 8 }}
```

2020-09-01 11:12 UTC, bergemalm commented
Hi @miguelaeh, sure I can do that and the same for master _but_ this means that you have to declare annotation as string literal when using for example Vault and secret templating.

Example before change (and only worked for master statefulset before this PR):
```
vault.hashicorp.com/agent-inject-template-my-password: |
      {{- with secret "my/path/to/password" -}}
        {{ .Data.data.password }}
      {{- end }}
```
after change:
```
vault.hashicorp.com/agent-inject-template-my-password: |
      {{`{{- with secret "my/path/to/password" -}}
        {{ .Data.data.password }}
      {{- end }}`}}
```

are we ok with that?

2020-09-01 11:26 UTC, bergemalm commented
PR updated!

2020-09-02 07:50 UTC, miguelaeh commented
Hi @bergemalm ,
How are you using the secret in your previous comment? Is
```
vault.hashicorp.com/agent-inject-template-my-password: |
      {{- with secret "my/path/to/password" -}}
        {{ .Data.data.password }}
      {{- end }}
```
part of your `values.yaml`?

Was that properly rendered before, I thought if you pass that in the values.yaml it will not be templatized in the statefulset due to the toYaml

2020-09-02 09:22 UTC, bergemalm commented
Yes part of `values.yaml` and `toYaml` works without issues. @miguelaeh

2020-09-03 07:36 UTC, miguelaeh approved these changes
Thank you for addressing the changes.
LGTM!

2020-09-03 07:36 UTC, merged