[bitnami/metallb] Fixed the PrometheusRule creation issue
bitnami/charts pull request #3609
Opened 2020-09-04 15:53 UTC by utkudarilmaz

The error fixed that cause of PrometheusRule definition creations. One of two condition deleted that is controlling the PrometheusRule creation. The reason for this .Values.prometheus.enabled not defined on values.yaml and not using on rest of charts.

**Benefits**
PrometheusRules can be deployable anymore.

**Possible drawbacks**
N/A

**Applicable issues**
N/A

**Additional information**
N/A

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2020-09-07 10:15 UTC, dani8art commented
Hi @utkudarilmaz why do you need to remove `prometheus.enabled`? if you want to use these prometheus features you just need to add `--set prometheus.enabled=true` to your deploy command.

2020-09-07 12:03 UTC, utkudarilmaz commented
Hi @dani8art, yes i know we can pass this attributes with --set or custom writed x but fresh users don't know this value when firstly downloaded charts. 

When users installing charts they will see PrometheusRules didn't created. The users have to look up the charts to understand why PromethuesRules didn't created. 

So we have two options for fix this issue. First one is adding the .Value.prometheus.enabled value to values.yaml. Second option is deleting the if condition from PrometheusRule chart. In my opinion, second option more simple and elegance than first one.

2020-09-08 10:14 UTC, dani8art commented
Yes, I agree with adding it to the `values.yaml` so the users can understand how to use it

2020-09-08 11:58 UTC, dani8art requested changes
Thanks! Please take a look at my suggestions.

2020-09-08 11:58 UTC, dani8art commented on bitnami/metallb/README.md
> +| `prometheus.enabled`                                  | Enable for Prometheus alertmanager basic alerts.                                                     | `true`
We should keep it disabled by default as we have it now.

```suggestion
| `prometheus.enabled`                                  | Enable for Prometheus alertmanager basic alerts.                                                     | `false`                                                  |
```

2020-09-08 11:58 UTC, dani8art commented on bitnami/metallb/values.yaml
> +  enabled: true
```suggestion
  enabled: false
```

2020-09-09 09:24 UTC, dani8art approved these changes
Thank you so much! LGTM

2020-09-09 09:25 UTC, dani8art commented
Please, could you fix the linter errors?

2020-09-09 10:58 UTC, utkudarilmaz commented
@dani8art Thanks, best regards.

2020-09-09 14:21 UTC, merged