[bitnami/consul] Add configurable service session affinity
bitnami/charts pull request #3640
Opened 2020-09-09 10:50 UTC by rasmus

**Description of the change**

Be able to control the service `sessionAffinity` setting.

**Benefits**

Be able to control the service `sessionAffinity` setting.

**Possible drawbacks**

None known

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-09-10 08:00 UTC, miguelaeh requested changes
Thank you very much for the PR!!!
Please take a look at my comments

2020-09-10 08:00 UTC, miguelaeh commented on bitnami/consul/values.yaml
> +  sessionAffinity: "None"
Please add this change to the `values-production.yaml` too

2020-09-10 08:00 UTC, miguelaeh commented on bitnami/consul/templates/consul-service.yaml
> +  sessionAffinity: {{.Values.service.sessionAffinity}}
```suggestion
  sessionAffinity: {{ .Values.service.sessionAffinity }}
```

2020-09-10 10:45 UTC, rasmus commented
@miguelaeh I have updated the PR with the changes. I aligned the use of spaces to match your comment as there was a mixture of the the in the file

2020-09-11 08:02 UTC, miguelaeh approved these changes
Thank you very much for addressing the changes!!!
LGTM!!!

2020-09-11 08:02 UTC, merged