[bitnami/postgresql] Added labels for volumeClaimTemplates
bitnami/charts pull request #3768
Opened 2020-09-24 15:46 UTC by rahulsadanandan

**Description of the change**

Added labels for volumeClaimTemplates

**Benefits**

If we want to delete a pvc using a label release. 
for eg:
kubectl delete pvc -l release=xxx

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-09-25 13:53 UTC, dani8art requested changes
Hi @rahulsadanandan thank you for the PR.

Could you take a look at my comment?

2020-09-25 13:53 UTC, dani8art commented on bitnami/postgresql/templates/statefulset.yaml
> +          component: master
We should use labels convention

```suggestion
        labels: {{- include "common.labels.standard" . | nindent 10 }}
          app.kubernetes.io/component: master    
```

2020-09-25 14:00 UTC, rahulsadanandan commented
Updated the pr

2020-09-25 14:04 UTC, merged

2020-09-29 14:39 UTC, marcosbc commented
Hi, unfortunately we've had to revert this PR. It causes chart upgrades to fail due to changing an immutable field. There is also other stuff like we should be using matchLabels, and not setting `common.labels.standard`. Feel free to re-open a new PR with a new approach to these changes.