[bitnami/discourse] Update strategy added
bitnami/charts pull request #3865
Opened 2020-10-02 12:03 UTC by utkudarilmaz

**Description of the change**

Deployment update strategy added.

**Benefits**

With flexible update strategy users can change their deployment strategies about own benefits.

**Possible drawbacks**

There is no drawbacks.

**Applicable issues**

**Additional information**

When users using RWO PV's and default strategy (RollingUpdate), the deploy process is stucking because the old pod never release PVC before new Pod becaming healthy. So if users can change update strategy to **Recreate** stucking issue will fixed.

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2020-10-05 11:38 UTC, dani8art requested changes
Hi @utkudarilmaz thank you so much for the PR. Please, take a look at my comments.

2020-10-05 11:38 UTC, dani8art commented on bitnami/discourse/Chart.yaml
> +version: 0.5.1
It would be:

```suggestion
version: 0.5.0
```

2020-10-05 11:38 UTC, dani8art commented on bitnami/discourse/README.md
> +| `updateStrategy`                     | Update strategy of deployment                                                              | `{}`                                                         |
We should add a default value for `updateStrategy`, maybe the simplest one.

2020-10-06 13:06 UTC, dani8art approved these changes
LGTM

2020-10-06 13:06 UTC, merged

2020-10-06 13:41 UTC, utkudarilmaz commented
@dani8art thanks, best regards!