[bitnami/zookeeper] allow for overriding namespace in zookeeper helm chart
bitnami/charts pull request #3881
Opened 2020-10-03 18:35 UTC by monicaruttle

**Description of the change**

Allow for overriding the namespace that the ZooKeeper helm chart resources use.

**Benefits**

When ZooKeeper is included as a dependency of another helm chart, the preferred behaviour may be for it to be released into a different namespace than the parent. This change will allow for the parent chart values to override the namespace.

**Possible drawbacks**

Unknown

**Applicable issues**

  - addresses #3864

**Additional information**

By default behaviour will not change from taking the Release.Namespace value for the namespace.

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2020-10-04 08:12 UTC, glothriel commented
@juan131 I think you may be interested in this one :-)

Personally I like the idea, with some changes:
* I've seen somewhere (charts/stable?) similar approach, but the field there was named `namespaceOverride`, for some reason I like it more
* I'd extract this logic to a template

2020-10-05 07:20 UTC, miguelaeh requested changes
Hi @monicaruttle ,
Thank you very much for the PR!
Please take a look at the files carefully, there are some places where the namespace is used that also need to be changed.
Apart from that, I agree with @glothriel in use `namespaceOverride` and a template to select the namespace instead of repeating the logic in all the files.

2020-10-05 07:20 UTC, miguelaeh commented on bitnami/zookeeper/templates/statefulset.yaml
>    name: {{ template "zookeeper.fullname" . }}
Line 142 needs to be changed too

2020-10-06 13:08 UTC, dani8art requested changes
Hi @monicaruttle thanks for applying the changes. 

Please, take a look at my comments.

2020-10-07 08:05 UTC, dani8art approved these changes
LGTM

2020-10-07 13:40 UTC, merged