Updated README files for Apache, MySQL and WordPress charts
bitnami/charts pull request #4155
Opened 2020-10-29 14:03 UTC by vikram-bitnami

**Description of the change**

Updates the README files with additional links and condenses duplicate content

**Benefits**

Smaller, more compact README

**Possible drawbacks**

None

**Applicable issues**

None

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-11-03 11:32 UTC, marcosbc reviewed
These changes LGTM but I would also like to check the published docs before merging this PR. I would also like to get @juan131's point of view regarding these changes.

2020-11-03 12:07 UTC, beltran-rubo requested changes

2020-11-03 12:22 UTC, juan131 commented
I have my concerns about removing sections from the chart’s README(s) to add links to https:///docs.bitnami.com.

There are two reasons for not doing so:

- GitHub users contribute to these README.md(s) enriching them and this model is currently working very well. However, they can't contribute if the docs are at https://docs.bitnami.com
- We currently have everything (docs and charts) in a single repo. This simplifies everything.

I agree we have duplicated docs, but this is not the right solution IMHO. If we want https://docs.bitnami.com to be synced with https://github.com/bitnami/charts, then let's create a `docs/` folder and generate https://docs.bitnami.com helm sections based on markdown files at this folder. This way, uses can contribute and the docs are also open-sourced.

@javsalgar @carrodher I'd like to hear your opinion

2020-11-12 14:53 UTC, carrodher commented
I agree with Juan's comment, it is nice to see users contributing and improving the docs and it is something we should keep.
In the same way, changing the context from GitHub to docs.bitnami.com is not a good UX, I think it's better to maintain all the documentation in the same place. With "the same place" I mean the GitHub repository, not necessary in the same README.

As per the above comments, we can discuss the implementation of a system like the one shown in the below picture:

<img width="312" alt="Screenshot 2020-11-12 at 15 49 11" src="https://user-images.githubusercontent.com/13216600/98954928-9ed53c80-24fe-11eb-8fc6-b5cb102a7d3a.png">

In the `bitnami/chartX/` folder we have the regular _README.md_, containing the basic information such as how to deploy, most important parameters & configurations, changelog. That means we should remove information from the current _README.md_ and point to the new markdown files placed in the docs folder.

Then there is a new `docs/` folder that can contain several subfolders but, at least, a `charts/` folder containing a subfolder for every Helm Chart.
In that per chart folder, we can place those sections previously removed from the regular _README.md_ including information about 2nd-day operations such as TLS, LDAP configuration, differences between architectures, etc.

Apart from that, at the same level as the charts folder, we can create other subfolders for different kind of docs, such as `troubleshooting/`, `common/`, etc. in order to add other content that is interesting but that is not specific to a particular chart, like security guidelines, rolling VS immutable tags, etc.

That is just an idea, let's discuss the different options properly with a meeting.

2021-01-12 08:15 UTC, closed without merging