[bitnami/fluentd] Add missing features from stable/fluentd [WIP]
bitnami/charts pull request #4215
Opened 2020-11-04 16:54 UTC by alemorcuq

**Description of the change**
The goal of this PR is to add the missing features from the `stable/fluentd` chart for a smoother transition from that chart. See this thread for a discussion on this: https://github.com/helm/charts/issues/21235#issuecomment-721561451

Missing features:
- [ ] Install plugins at container launch.
- [x] Allow Fluentd configuration without having to use an external ConfigMap.
- [x] Use a HPA for the StatefulSet (interesting in aggregator-only deployments).
- [ ] Add an Ingress (for the aggregator alone? for the forwarder as well?).

This is a WIP, but feel free to add your thoughts @scottrigby @carrodher @davidkarlsen @Miouge1

**Checklist**
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2021-01-14 11:21 UTC, alemorcuq commented
Sorry for the delay, this is ready for review now.

2021-01-14 16:41 UTC, FraPazGal requested changes
Thank for the PR, these are good additions to make the migration easier! Could you please take a look at my comments?

2021-01-14 16:41 UTC, FraPazGal commented on bitnami/fluentd/README.md
> +| `aggregator.ingress.path`                       | Default path for the ingress resource                                                                          | `/`
Probably a typo, you forgot to add the parameter `aggregator.ingress.pathType` here.

2021-01-14 16:41 UTC, FraPazGal commented on bitnami/fluentd/values-production.yaml
> +    ##
I think there is some configuration missing. You are not creating the secrets from this input.

2021-01-15 16:16 UTC, FraPazGal approved these changes
LGTM!

2021-01-15 16:25 UTC, merged