[bitnami/thanos] fix: add tls switch to enable TLS with cert-manager for querier and bucketweb ingress
bitnami/charts pull request #4218
Opened 2020-11-05 09:03 UTC by janlud

The querier.ingress.tls conditional was removed in previous releases which enabled cert-manager to work with `cert-manager.io/cluster-issuer: nameOfClusterIssuer` annotation.

**Description of the change**
Add back a `querier.ingress.tls` and `bucketweb.ingress.tls`which was removed. This switch is important for cert-manager provisioning of certificates.
When `tls: true` a tls: part of ingress manifest is rendered. For this also `cert-manager.io/cluster-issuer: nameOfClusterIssuer` annotation must be set. That is already supported by using annotations
Example of what should be created is [here](https://cert-manager.io/docs/usage/ingress/#how-it-works)

**Benefits**

Enabled use of cert-manager cert provisioning for querier and bucketweb ingresses.

**Possible drawbacks**

**Applicable issues**

  - fixes #4127

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-11-06 08:49 UTC, miguelaeh requested changes
Thank you very much for the PR!
Please take a look at my comments

2020-11-06 08:49 UTC, miguelaeh commented on bitnami/thanos/Chart.yaml
> +version: 2.5.4
You are adding a new parameter this should be a minor bump

2020-11-06 08:49 UTC, miguelaeh commented on bitnami/thanos/values-production.yaml
> +    ## When specifying cert-manager.io/cluster-issuer: nameOfClusterIssuer annotation, enable tls for ingress
I would separate this from the previous section. Please add a space before, and the same in the rest of the changes like this one

2020-11-06 15:09 UTC, janlud commented
@miguelaeh I made the required changes. Made some mess in git history and took me a while to figure it out (sorry, still learning!). I see I have commits here from my other change I did couple days ago to thanos chart but I don't see those changes in diff (The PR was merged so it's in master). Can you merge it like this with squashing commits or do I need to somehow get those commits out?

2020-11-11 12:15 UTC, dani8art approved these changes
LGTM

2020-11-11 12:15 UTC, merged