[bitnami/wordpress] - Add back previously removed _helper functions to unbreak post-init configmap
bitnami/charts pull request #4487
Opened 2020-11-25 13:54 UTC by pestebogdan

**Description of the change**

This PR: https://github.com/bitnami/charts/pull/4373 , which brings new functionality from versions >=9.10.0, requires the declaration of 2 helper scripts, which were removed from **_helpers.tpl** as of version 10.0.0, specifically:
  - wordpress.fullname
  - wordpress.tplValue

This PR is meant to ammend the changes of https://github.com/bitnami/charts/pull/3850, specifically adding back these 2 helper functions, as without them, whenever the `customPostInitScripts` variable is populated, helm chart installation fails.

**Possible drawbacks**

None that I can see

2020-11-26 07:29 UTC, pestebogdan commented
/retest

2020-11-26 07:31 UTC, pestebogdan commented
/recheck

2020-11-26 10:16 UTC, miguelaeh requested changes
Hi @pestebogdan ,
Instead of adding those functions back we should be using the following:
For the fullname:
```
{{ include "common.names.fullname" . }}
```

For the tplvalue, something like the following changing the value:
```
{{- include "common.tplvalues.render" (dict "value" .Values.metrics.serviceMonitor.additionalLabels "context" $) | nindent 4 }}
```

The tplValue needs to be changed in once at `templates/configmap.yaml` and twice at `templates/tls-secrets.yaml`. And the fullname needs to be changed once at `templates/configmap.yaml`.

Thank you for reporting the issue!!

2020-11-26 15:13 UTC, pestebogdan commented
> Hi @pestebogdan ,
> Instead of adding those functions back we should be using the following:
> For the fullname:
> 
> ```
> {{ include "common.names.fullname" . }}
> ```
> 
> For the tplvalue, something like the following changing the value:
> 
> ```
> {{- include "common.tplvalues.render" (dict "value" .Values.metrics.serviceMonitor.additionalLabels "context" $) | nindent 4 }}
> ```
> 
> The tplValue needs to be changed in once at `templates/configmap.yaml` and twice at `templates/tls-secrets.yaml`. And the fullname needs to be changed once at `templates/configmap.yaml`.
> 
> Thank you for reporting the issue!!

Thanks for the tip @miguelaeh ! I updated the changes with the correct values.

2020-11-27 10:10 UTC, pestebogdan reviewed
Changes updated

2020-11-27 12:34 UTC, miguelaeh approved these changes
Thank you very much!!!!
LGTM!

2020-11-27 12:42 UTC, miguelaeh commented
Could you check errors with the testing please?

2020-11-28 08:35 UTC, pestebogdan commented
Hmm, not really sure why it is failing (some warning regarding a connection to DB) , not sure if it is related to this particular change. Is it possible to run the same test on the master branch to make sure the master is not broken ?

2020-12-01 15:43 UTC, andresbono commented
Hi @pestebogdan, thanks for checking the GitHub action. As you mention, master is not passing the tests: See https://github.com/bitnami/charts/pull/4567.

We will merge this PR as it is working properly and we will investigate the issue with the GitHub action.

Thanks for your contribution!

2020-12-01 15:43 UTC, merged