[bitnami/metrics-server] Fix wrong template helper usage
bitnami/charts pull request #4551
Opened 2020-12-01 07:14 UTC by rocketspacer

**Description of the change**

#4529 introduced wrong usages of template helpers. This PR fixes them.

**Benefits**

Fix broken template

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-12-01 14:23 UTC, dani8art requested changes
Hi thanks for the PR, please take a look at my comment.

2020-12-01 14:23 UTC, dani8art commented on bitnami/metrics-server/templates/pdb.yaml
> +  name: {{ template "common.names.fullname" . }}
Could we use `include`?

```suggestion
  name: {{ include "common.names.fullname" . }}
```

2020-12-02 02:01 UTC, rocketspacer commented on bitnami/metrics-server/templates/pdb.yaml
> +  name: {{ template "common.names.fullname" . }}
Fixed

2020-12-02 17:14 UTC, dani8art approved these changes
LGTM, Thanks!

2020-12-02 17:14 UTC, merged