[bitnami/influxdb] Fix affinity template function call
bitnami/charts pull request #4579
Opened 2020-12-02 14:25 UTC by Antiarchitect

Signed-off-by: Andrey Voronkov <voronkovaa@gmail.com>

**Description of the change**

Bugfix. Chart install fails on actually setting affinities templates

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-12-03 11:48 UTC, dani8art requested changes
Hi @Antiarchitect, thanks for the fix. Just a minor comment, could you use `common.tplvalues.render`, please?

2020-12-03 11:58 UTC, Antiarchitect commented
@dani8art Done, not sure how this works. Copy-paseted from bitnami/consul.

2020-12-03 12:06 UTC, dani8art approved these changes
Cool! LGTM

2020-12-03 12:29 UTC, merged

2020-12-03 12:45 UTC, Antiarchitect commented
@dani8art Could you please update it in the bitnami repo. I still see chart 1.0.0 version.

2020-12-04 06:58 UTC, dani8art commented
Yes, sure. Our pipeline is having some issues but once they are fixed the chart will appear in the repo. Sorry for the inconvenience.

2020-12-04 12:31 UTC, Antiarchitect commented
Bet this is dockerhub related - hard night for me :)