[bitnami/postgresql] Fix password when using existingSecret
bitnami/charts pull request #4659
Opened 2020-12-09 12:34 UTC by miguelaeh

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #4655

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-12-09 12:46 UTC, kirschem reviewed
Looks valid to me, however I don't have time atm to do a test run with values.

2020-12-16 09:33 UTC, juan131 requested changes

2020-12-16 09:33 UTC, juan131 commented on bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
> +            {{- if or .Values.postgresql.existingSecret (and .Values.postgresql.postgresPassword (not (eq .Values.postgresql.username "postgres"))) }}
This assumes that you're using a user different from "postgres" when an existing secret is used to store the credentials.

2020-12-16 09:39 UTC, juan131 requested changes

2020-12-16 09:39 UTC, juan131 commented on bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
> +            {{- if and (or .Values.postgresql.existingSecret .Values.postgresql.postgresPassword) (not (eq .Values.postgresql.username "postgres")) }}
Better.. But we still have a problem.. This is not considered "global" values.
```suggestion
            {{- if and (or (include "postgresql-ha.postgresqlCreateSecret" .) (include "postgresql-ha.postgresqlPostgresPassword" .)) (not (eq (include "postgresql-ha.postgresqlUsername" .) "postgres")) }}
```

2021-01-08 15:43 UTC, juan131 approved these changes
LGTM

2021-01-08 15:47 UTC, merged