[bitnami/mongodb] Add custom CA support
bitnami/charts pull request #4690
Opened 2020-12-10 20:52 UTC by deveshk0

Description of the change

Added a `tls.caCert` and `tls.caKey` to customise the `ca-clients`

Benefits

Allows to use own CA 

Possible drawbacks

Backwards compatibile, so no obvious issues beyond the minor increase in complexity

Applicable issues

NA - can raise one if there's some discussion needed?

Additional information

NA

Checklist

 Chart version bumped in Chart.yaml according to semver.
 Variables are documented in the README.md
 Title of the PR starts with chart name (e.g. [bitnami/chart])
 If the chart contains a values-production.yaml apart from values.yaml, ensure that you implement the changes in both files

2020-12-11 07:18 UTC, juan131 requested changes
Thanks for you contribution! We really appreciate
Only a small detail, and I'll accept it.

2020-12-11 07:18 UTC, juan131 commented on bitnami/mongodb/Chart.yaml
> +version: 10.1.5
Please bump minor version instead

2020-12-11 07:25 UTC, deveshk0 commented on bitnami/mongodb/Chart.yaml
> +version: 10.1.5
10.2.0 right?

2020-12-11 08:04 UTC, deveshk0 commented on bitnami/mongodb/Chart.yaml
> +version: 10.1.5
Done

2020-12-11 14:17 UTC, juan131 reviewed
A couple of requests more

2020-12-11 14:17 UTC, juan131 commented on bitnami/mongodb/Chart.yaml
> +
Remove extra empty line

2020-12-11 14:17 UTC, juan131 commented on bitnami/mongodb/templates/secrets-ca.yaml
> +{{- end -}}
Please fix the "No newline after at end of file" error

2020-12-11 14:19 UTC, juan131 commented
Please also rebase from master your PR since https://github.com/bitnami/charts/pull/4690 was just merged

2020-12-14 09:21 UTC, juan131 approved these changes
LGTM! Thanks for implementing the suggestions!

2020-12-14 09:21 UTC, merged