[bitnami/external-dns] Add secretAnnotations value
bitnami/charts pull request #4745
Opened 2020-12-16 11:26 UTC by AntonioAlfrz

**Description of the change**
This PR adds the value secretAnnotations to allow to add annotations to the secret

**Benefits**

- More customization
- Be able to integrate it with other tools like [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets#managing-existing-secrets)

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 
- [ X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ X] Variables are documented in the README.md
- [ X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-12-17 08:59 UTC, miguelaeh requested changes
Thank you very much for the PR!
Please take a look at my comments

2020-12-17 08:59 UTC, miguelaeh commented on bitnami/external-dns/README.md
> +| `secretAnnotations`                    | Additional annotations to apply to the secret | `{}`
Could you please add the same format as the rest of the rows?

2020-12-17 08:59 UTC, miguelaeh commented on bitnami/external-dns/templates/secret.yaml
> +  annotations: {{ toYaml .Values.secretAnnotations | nindent 4 }}
```suggestion
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.secretAnnotations "context" $) | nindent 4 }}
```

2020-12-18 15:06 UTC, dani8art approved these changes
Thanks for your PR, LGTM!

2020-12-18 15:06 UTC, merged