[bitnami/rabbitmq] Refine probes
bitnami/charts pull request #4747
Opened 2020-12-16 12:21 UTC by jBouyoud

**Description of the change**

Correct probes implementation according to #4731 discussion.
And add availability to define startupProbe for users who wants to.

**Benefits**

- Better readiness management in rabbitmq cluster (especially on pod movements)
- Availability to use startup probe

**Possible drawbacks**

- Possible extra cpu consummation due to `check_local_arlarms` addition in readiness probe (not tested).

**Applicable issues**

  - fixes #4731

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2020-12-17 15:22 UTC, alemorcuq requested changes
Thanks for the PR!

2020-12-17 15:22 UTC, alemorcuq commented on bitnami/rabbitmq/values.yaml
> +customStartupProbe: ~
Can you set the default to `{}` as with the others?

2020-12-17 17:02 UTC, orirawlings approved these changes
I'm just a bystander who was thinking of upgrading my chart version today and noticed this pending fix. But FWIW, this LGTM (aside from a likely comment typo).

2020-12-17 17:02 UTC, orirawlings commented on bitnami/rabbitmq/values.yaml
> +## Custom Startup prove
Typo? `probe`

2020-12-18 06:40 UTC, jBouyoud commented on bitnami/rabbitmq/values.yaml
> +## Custom Startup prove
Fix

2020-12-18 09:16 UTC, alemorcuq approved these changes
LGTM!

2020-12-18 09:17 UTC, merged