[bitnami/spring-cloud-dataflow] Update SCDF metrics configuration for…
bitnami/charts pull request #4752
Opened 2020-12-16 18:12 UTC by tzolov

… 2.7+

**Description of the change**

Adjust the Spring Cloud Data Flow metrics configuration to reflect the latest (2.7.0) breaking changes. 
 - replaces the grafanaInfo.url by metricsDasboard.url property. (Update the README) 
 - Provide metrics configuration for the SCDF and Skipper servers themself. 
 - Remove the per-application and per-task metrics configurations as with 2.7.0 those are automatically configured by replicating the SCDF's own metrics configuration.  

**Benefits**

- Resolves a metrics configuration, breaking change. 
- Removes redundant conf.
- Streamline the documentation. 

**Possible drawbacks**

none

**Applicable issues**

  - fixes #4751

**Checklist** 
- [x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ x] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2020-12-16 23:24 UTC, marcosbc requested changes
Thanks for the contribution! I have no concerns over the approach, but I've added some requests for small changes.

2020-12-16 23:24 UTC, marcosbc commented on bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
>            {{- end }}
Wouldn't it be problematic if both `grafanaInfo` and `metricsDashboard` options are set at once? Maybe we could rely on an `if`-`else if` logic instead (and re-ordering the blocks).

2020-12-16 23:24 UTC, marcosbc commented on bitnami/spring-cloud-dataflow/Chart.yaml
> +version: 2.3.1
Could we increase this to 2.4.0? Since it includes important changes to the actual configuration of the app.

2020-12-17 09:46 UTC, tzolov commented
thanks for the review @marcosbc ! 
I've just pushed a commit (d508f9d32ec9bd486e556cc0818f1c9551c72e9c) to address  the above recommendations.

2020-12-17 09:53 UTC, marcosbc reviewed
LGTM, thanks!!!

2020-12-17 09:54 UTC, marcosbc approved these changes

2020-12-17 09:54 UTC, merged