[bitnami/logstash] Adding tls-secrets.yaml #4768
bitnami/charts pull request #4769
Opened 2020-12-17 13:21 UTC by ikus060

**Description of the change**

Adding tls-secrets.yml to logstash chart

**Benefits**

?

**Possible drawbacks**

unknown

**Applicable issues**

  - fixes #4768

**Additional information**

NA

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2020-12-18 09:34 UTC, FraPazGal requested changes
Thanks for the PR @ikus060! Could you please take a look at my comment?

2020-12-18 09:34 UTC, FraPazGal commented on bitnami/logstash/templates/tls-secret.yaml
> +{{- $ca := genCA "aspnet-core-ca" 365 }}
```suggestion
{{- $ca := genCA "logstash-ca" 365 }}
```

2020-12-21 16:07 UTC, ikus060 commented on bitnami/logstash/templates/tls-secret.yaml
> +{{- $ca := genCA "aspnet-core-ca" 365 }}
Fixed

2020-12-22 08:59 UTC, FraPazGal approved these changes
LGTM!

2020-12-22 09:00 UTC, merged