[bitnami/zookeeper] Fix zookeeper.tplValue
bitnami/charts pull request #4779
Opened 2020-12-17 16:34 UTC by adrianchifor

Using tolerations, affinity or nodeSelector in the zookeeper fails with:
```
template: zookeeper/templates/statefulset.yaml:63:23: executing "zookeeper/templates/statefulset.yaml" at <include "apache.tplValue" (dict "value" .Values.tolerations "context" $)>: error calling include: template: no template "apache.tplValue" associated with template "gotpl"
```

Looks like a bad copy-paste from apache chart:
https://github.com/bitnami/charts/blob/785a386678793aad1de50b4ab9e0b8b8d1b066fc/bitnami/zookeeper/templates/statefulset.yaml#L63

**Checklist**
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

2020-12-17 16:43 UTC, juan131 requested changes

2020-12-17 16:43 UTC, juan131 commented on bitnami/zookeeper/templates/_helpers.tpl
> +{{- end -}}
Not necessary

2020-12-17 16:43 UTC, juan131 commented on bitnami/zookeeper/templates/statefulset.yaml
> +      affinity: {{- include "zookeeper.tplValue" (dict "value" .Values.affinity "context" $) | nindent 8 }}
Use `common.tplvalues.render` instead:
```suggestion
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
```

2020-12-17 16:43 UTC, juan131 commented on bitnami/zookeeper/templates/statefulset.yaml
> +      nodeSelector: {{- include "zookeeper.tplValue" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
Use `common.tplvalues.render` instead:
```suggestion
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
```

2020-12-17 16:43 UTC, juan131 commented on bitnami/zookeeper/templates/statefulset.yaml
> +      tolerations: {{- include "zookeeper.tplValue" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
Use `common.tplvalues.render` instead:
```suggestion
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
```

2020-12-17 16:43 UTC, juan131 commented
Thanks so much for the PR

2020-12-17 16:48 UTC, adrianchifor commented
Nice one, thanks for the suggestions, all applied.

2020-12-18 07:55 UTC, juan131 approved these changes
LGTM

2020-12-18 07:55 UTC, merged

2020-12-18 12:58 UTC, adrianchifor commented
@juan131 thanks for merging, is the chart release automatic?

2020-12-18 14:19 UTC, juan131 commented
As explained in the [Contributing Guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md), our CI/CD system automatically release the new version.

That said, there might be a slight difference between the appearance of the code in GitHub and the chart in the registry. It should be published in a couple of hours.

2020-12-18 14:41 UTC, adrianchifor commented
Ok cool, thank you :)