[bitnami/fluentd] add means to configurate liveness and readiness end…
bitnami/charts pull request #4952
Opened 2021-01-12 07:36 UTC by ekrucio

…points for forwarder and aggregator

**Description of the change**

Added means to additionally configure the path and port for liveness and readiness probe in both aggregator and forwarder

**Benefits**

Before this change there were no ways to configure the endpoints to which the probes should run. This was unnecessary difficult to work with if you're trying to add fluentd to an already existing monitoring setup. The default values should preserve the current behaiviour.

**Possible drawbacks**

None for what I know.

**Applicable issues**

None

**Additional information**

This change has been tested with https://hub.docker.com/r/bitnami/fluentd/latest and no issues were encountered.

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-01-12 09:46 UTC, alemorcuq requested changes
Thanks for the PR, @ekrucio, it's a nice addition. I've added some minor comments to the PR.

2021-01-12 09:46 UTC, alemorcuq commented on bitnami/fluentd/Chart.yaml
> +version: 3.2.3
```suggestion
version: 3.3.0
```

2021-01-12 09:46 UTC, alemorcuq commented on bitnami/fluentd/values-production.yaml
>      enabled: true
Please, let `enabled: true` be the first setting (this applies to all blocks)

2021-01-12 16:32 UTC, ekrucio commented
@alemorcuq I've fixed the comments you mentioned. It's better this way, I can agree. 👍

2021-01-13 08:12 UTC, alemorcuq approved these changes
Thanks!

2021-01-13 08:13 UTC, merged