Redis slave volume init fix
bitnami/charts pull request #5059
Opened 2021-01-16 15:27 UTC by leozilla

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-01-18 17:14 UTC, dani8art requested changes
Hi @leozilla, thanks for the PR! 

Could we keep as `-c` to be aligned with the master init container?

2021-01-18 18:51 UTC, leozilla commented
Hi @dani8art 

Yeah sure I can change it to `-c`. I used `-cx` cos it was also used for the master initContainer command (https://github.com/bitnami/charts/blob/11432868f44e258cd95d06214f92ac0966b4f46f/bitnami/redis/templates/redis-master-statefulset.yaml#L252) but I see that all other `/bin/sh` executions dont use `-x`.

2021-01-18 21:06 UTC, leozilla commented
Do u want to have it consistent for all commands? Then I suggest to also remove the `-x` from the master initContainer.

2021-01-19 11:25 UTC, dani8art commented
> Do u want to have it consistent for all commands? Then I suggest to also remove the `-x` from the master initContainer.

Yes, could we replace all the instances in those init containers for `-ec`, please?

2021-01-19 11:40 UTC, leozilla commented
@dani8art 
Good idea. See https://github.com/bitnami/charts/pull/5059/commits/57454a0a288cd419369dba6665da4b0b552cba62

2021-01-19 12:26 UTC, leozilla commented
Seems that the test failure is a false positive, cos I already pumped the version.

2021-01-19 19:58 UTC, leozilla commented
Ok I just saw there was a version bump in the meantime in master. I merged master into this branch and again bumped the PATCH version of the chart.

2021-01-20 09:41 UTC, dani8art reviewed
Just a minor comment

2021-01-20 09:41 UTC, dani8art commented on bitnami/redis/templates/redis-master-statefulset.yaml
>            - /bin/sh
could we use `/bin/bash` for both too?

2021-01-21 15:44 UTC, dani8art approved these changes
LGTM!

2021-01-21 15:44 UTC, merged