Created a PR adding the bitnami/keycloak-config-cli helm chart to bitnami
bitnami/charts pull request #5167
Opened 2021-01-20 21:01 UTC by iamaverrick

**Description of the change**

**Benefits**
added bitnami/keycloak-config-cli Helm Chart so bitnami/keycloak can use it as a dependency. 
things to do 

1. The chart should use Bitnami based container images. If they don't exist like in this case, the Bitnami team will need to create them. As it is an internal process, we will need to be evaluated and prioritized in conjunction with the rest of the team's tasks.
2. Follow the same structure/patterns that the rest of the Bitnami charts (you can find a basic scaffolding in the template directory) and the Best Practices for Creating Production-Ready Helm charts guide.
3. Use an OSI-approved license for all the software.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-01-22 17:51 UTC, migruiz4 commented
Hi @imaverrick,

Thank you very much for your contribution.

After discussing it with the team, we consider it would be more appropriate for `keycloak-config-cli` to be integrated with the `keycloak` chart instead of as an independent chart.

This could be done by moving your templates into the Keycloak chart adding `{{- if .Values.configCli.enabled }}` at the beginning.

For the values, they would be moved into `bitnami/keycloak/values.yml` under `configCli` as follows:

```yaml
configCli:
  enabled: false
  #keycloak-config-cli values
  ...
```

If you have any questions don't hesitate to let us know.

2021-01-22 22:06 UTC, iamaverrick commented
His @migruiz4 ,

this sounds good and i can get started i was just following what i was told by @carrodher at [Issue](https://github.com/bitnami/charts/issues/5146)

2021-01-23 00:04 UTC, carrodher commented
Yes, this is the process to add any Helm Chart to the Bitnami catalog; but after taking a look at this PR, we think it is better the approach suggested by @migruiz4.

The chart in this PR doesn't meet the requirements above mentioned (chart using BitNami scaffolding and guidelines, container image in the catalog, etc) so once we reviewed the PR, it seems more easy to add the templates directly inside the keycloak chart than support a different chart to be used as a subchart. As it is an already existing chart that was just copied here it is not close to follow the same standards than the rest of Bitnami charts.

In the same way, we think the solution add more value as a feature bundled in the keycloak chart than as a separate chart

2021-01-23 00:22 UTC, iamaverrick commented
@carrodher thank you for your prompt response and clarifications. i totally agree with you im extremely excited to see this feature implemented. 

thank you

2021-02-12 09:42 UTC, javsalgar reviewed
Please check my comments

2021-02-12 09:42 UTC, javsalgar commented on bitnami/keycloak/templates/job.yaml
> +          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag $ }}"
This should reference the .Values.KcCasc.image section. Could you create a helper just like we do with statefulset.yaml?

2021-02-12 09:42 UTC, javsalgar commented on bitnami/keycloak/templates/job.yaml
> +          {{- with .Values.resources }}
Use the .Values.KcCasc section. Apply to the rest of the yaml

2021-02-12 09:42 UTC, javsalgar commented on bitnami/keycloak/templates/job.yaml
> +apiVersion: batch/v1
Could you try adding the same type of standard values that we can see in statefulset.yaml?

2021-02-12 09:42 UTC, javsalgar commented on bitnami/keycloak/templates/realms.yaml
> +  {{ $name }}.json: "{{ tpl ($.Files.Get $config.file) $ | b64enc }}"
We try not using the Files function as it caused issues in the past. We prefer using either the inline, the existingConfig or the extraDeploy value.

2021-02-19 16:20 UTC, andresbono commented on bitnami/keycloak/values.yaml
> +KcCasC:
What do you think about using a more descriptive name and following camel-case style? `keycloakConfigAsCode` maybe?

2021-02-19 16:20 UTC, andresbono commented on bitnami/keycloak/values.yaml
> +    tag: "v{{ .Chart.AppVersion }}-11.0.3"
We have released the bitnami/keycloak-config-cli container image, please update the values and test that image on your side. Let us know about the results.

```suggestion
  ## Bitnami keycloak-config-cli image version
  ## ref: https://hub.docker.com/r/bitnami/keycloak-config-cli/tags/
  ##
  image:
    registry: docker.io
    repository: bitnami/keycloak-config-cli
    tag: 3.1.0-debian-10-r0
```

2021-03-03 15:44 UTC, andresbono commented
Hi @iamaverrick, we are going test and push the changes that we consider necessary to have this PR merged. You allowed maintainers to edit this PR, so it shouldn't be any issue for us to include new commits.

2021-03-03 18:21 UTC, iamaverrick commented
@andresbono yes of course, I’m sorry I had a lot of free time before but became busy with some projects. Some ideas to include because I have used the keycloak config chart is to use the environment variables provided by the main chart in the sub chart as most of the variables will be used anyways. We should only have to provide the configuration files to the subchart. Another thing worth noting is that the sub chart is forcing only json format. We need to be able to provide either json or yml. If you look at the secrets.yml it explicitly says json.

2021-03-05 12:17 UTC, andresbono commented
Thanks for the suggestions, @iamaverrick.

> to use the environment variables provided by the main chart in the sub chart as most of the variables will be used anyways. We should only have to provide the configuration files to the subchart.

Correct, that is how this is implemented. 👍 

> Another thing worth noting is that the sub chart is forcing only json format. We need to be able to provide either json or yml. If you look at the secrets.yml it explicitly says json.

Done, see the example in the `values.yaml`: https://github.com/bitnami/charts/blob/a87c6fd8d96d247c00543662cd32d14d6cf4d0ee/bitnami/keycloak/values.yaml#L847-L861

2021-03-05 12:48 UTC, juan131 requested changes
Wow, great PR! We really appreciate it.

Please check my suggestions when you have a chance

2021-03-05 12:48 UTC, juan131 commented on bitnami/keycloak/values.yaml
> +  config: {}
Use `configuration` for consistency with the already existing parameter. You'll have to update the job and README.md accordingly.
```suggestion
  ## configuration:
  ##   realm1.json: |
  ##     {
  ##       "realm": "realm1",
  ##       "clients": []
  ##     }
  ##   files/realm2.yaml:
  ##   realm3.yaml: |
  ##     realm: realm3
  ##     clients: []
  ##
  configuration: {}
```

2021-03-05 12:48 UTC, juan131 commented on bitnami/keycloak/values.yaml
> +  ## NOTE: This will override keycloakConfigCli.config
Following the previous suggestion:
```suggestion
  ## NOTE: This will override keycloakConfigCli.configuration
```

2021-03-05 12:48 UTC, juan131 commented on bitnami/keycloak/values.yaml
> +    #   - myRegistryKeySecretName
```suggestion
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
```

2021-03-05 12:48 UTC, juan131 commented on bitnami/keycloak/templates/_helpers.tpl
> +
I'dd a macro such as the one below:

```
{{/*
Return true if a configmap object should be created for keycloak-config-cli
*/}}
{{- define "keycloak.keycloakConfigCli.createConfigmap" -}}
{{- if and .Values.keycloakConfigCli.enabled .Values.keycloakConfigCli.configuration (not .Values.keycloakConfigCli.existingConfigmap)
    {{- true -}}
{{- end -}}
{{- end -}}
```

Then you can use later in the **keycloak-config-cli-configmap.yaml** and **keycloak-config-cli-job.yaml**

2021-03-05 12:48 UTC, juan131 commented on bitnami/keycloak/templates/keycloak-config-cli-configmap.yaml
> +{{- if and .Values.keycloakConfigCli.enabled .Values.keycloakConfigCli.config (not .Values.keycloakConfigCli.existingConfigmap) }}
Following the previous suggestion:
```suggestion
{{- if (include "keycloak. keycloakConfigCli .createConfigmap" .) }}
```

2021-03-05 12:48 UTC, juan131 commented on bitnami/keycloak/templates/keycloak-config-cli-job.yaml
> +      {{- end }}
Add the checksum to ensure the job is updated in the configuration changes
```suggestion
      annotations:
        {{- if (include "keycloak. keycloakConfigCli.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/keycloak-config-cli-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.keycloakConfigCli.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.keycloakConfigCli.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
```

2021-03-05 13:01 UTC, andresbono commented
# Manual testing done

### Simple realms

```console
$ mkdir -p files && echo '{"realm":"realm2", "clients": []}' >files/realm2.json
$ cat <<EOF | helm install keycloak . -f -
keycloakConfigCli:
  enabled: true

  config:
    realm1.json: |
      {
        "realm": "realm1",
        "clients": []
      }
    files/realm2.json:
    realm3.yaml: |
      realm: realm3
      clients: []
EOF
```
`/auth/admin/master/console/#/realms`
![image](https://user-images.githubusercontent.com/1057973/110118038-0b2fc080-7dba-11eb-8fc8-db4460005c30.png)

## Testing realm from upstream [moped.json](https://github.com/adorsys/keycloak-config-cli/blob/main/contrib/example-config/moped.json)

```console
$ cat <<EOF | helm install keycloak . -f -
keycloakConfigCli:
  enabled: true

  extraEnvVars:
    - name: IMPORT_PATH
      value: "https://raw.githubusercontent.com/adorsys/keycloak-config-cli/v3.1.0/contrib/example-config/moped.json"
EOF
```

`/auth/admin/master/console/#/realms`

![image](https://user-images.githubusercontent.com/1057973/110118698-0c152200-7dbb-11eb-9fd2-34a7270b9218.png)

2021-03-05 14:07 UTC, juan131 approved these changes
Thanks for addressing all the suggestions! LGTM

2021-03-05 14:44 UTC, migruiz4 approved these changes
Super cool feature!
LGTM, thank you very much for the contribution!

2021-03-08 11:46 UTC, merged