remove strange mongo validation between replicacount and loadBalancerIPs
bitnami/charts pull request #5393
Opened 2021-02-04 11:12 UTC by israelshenkar

why mongo .Values.externalAccess.service.loadBalancerIPs needs to be the same as .Values.replicaCount ?

getting an error when trying to create replicaset:

Error: template: mongodb/templates/NOTES.txt:171:4: executing "mongodb/templates/NOTES.txt" at <include "mongodb.validateValues" .>: error calling include: template: mongodb/templates/_helpers.tpl:213:51: executing "mongodb.validateValues" at <fail>: error calling fail: 
VALUES VALIDATION:
mongodb: .Values.externalAccess.service.loadBalancerIPs
    Number of replicas and loadBalancerIPs array length must be the same.
    

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-02-04 11:19 UTC, mosheavni commented
I agree, it makes no sense.

2021-02-05 12:12 UTC, Mauraza reviewed
Hi @brew,
thanks for the contribution, could you do a rebase the master?

2021-02-05 12:22 UTC, brew commented on bitnami/mongodb/Chart.yaml
> +version: 10.6.2
I don't think you mean to mention me :D

2021-02-05 12:33 UTC, juan131 requested changes
That's only the case when external access is enabled and you're not using auto-discovery. 

The reason:

A LoadBalancer service is created per MongoDB replica. Therefore, if you have 5 replicas, 5 services will be created.
When not configuring auto-discovery, you need to provide the list of IPs in advanced for al these services and hence, the validation.

2021-02-10 14:04 UTC, israelshenkar commented on bitnami/mongodb/Chart.yaml
> +version: 10.6.2
updated to 10.6.5 as master is on 10.6.4 :-)

2021-02-11 08:48 UTC, Mauraza commented
Hi @israelshenkar,

we can't remove that part, as @juan131 commented there is a case that needs it. 
Could you open an issue with the problem? we will be happy to help you to solve it.

2021-04-21 01:24 UTC, closed without merging