[bitnami/solr] Adds support for TLS
bitnami/charts pull request #5515
Opened 2021-02-16 16:51 UTC by rafariossaa

**Description of the change**

Adds support for SSL in solr.
Needs a new docker solr image that supports SSL to be released.

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-02-17 09:00 UTC, miguelaeh requested changes
Thank you very much for the PR!
Please take a look at the comments.
Also, please add documentation to the README about how to use SSL

2021-02-17 13:57 UTC, rafariossaa commented
I moved back the liveness/readiness check to use internal httpGet.

2021-02-18 09:52 UTC, miguelaeh approved these changes
LGTM!
Delete the empy line first

2021-02-18 09:52 UTC, miguelaeh commented on bitnami/solr/README.md
> +
```suggestion
```

2021-02-18 11:36 UTC, rafariossaa commented
Do not merge until the new container image is released.

2021-02-19 08:02 UTC, merged