[bitnami/postgresql-ha] Add serviceAccount
bitnami/charts pull request #5606
Opened 2021-02-24 14:44 UTC by erpel

**Description of the change**

This change ports the mechanism to create a serviceAccount or use an existing serviceAccount from the bitnami/postgres chart.

**Benefits**

The postgresql-ha chart can be equipped with a dedicated serviceAccount, enabling the use of serviceAccounts with the required imagePullSecrets, permissions to use PodSecurityPolicies and other reasons to use serviceAccounts other than the default one.

**Possible drawbacks**

Since the feature is disabled by default and copies the already proven mechanism of the related bitnami/postgresql chart, the risk of introducing breaking changes with this is low.

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

2021-02-25 09:30 UTC, miguelaeh requested changes
Thank you very much for the PR!!!
Please take a look to some minor comments I left.

2021-02-25 09:30 UTC, miguelaeh commented on bitnami/postgresql-ha/templates/serviceaccount.yaml
> +  {{- include "common.labels.standard" . | nindent 4 }}
```suggestion
  labels:  {{- include "common.labels.standard" . | nindent 4 }}
```

2021-02-25 09:30 UTC, miguelaeh commented on bitnami/postgresql-ha/templates/serviceaccount.yaml
> +  name: {{ template "common.names.fullname" . }}
```suggestion
  name: {{ include "common.names.fullname" . }}
```

2021-02-25 09:30 UTC, miguelaeh commented on bitnami/postgresql-ha/templates/serviceaccount.yaml
> +  namespace: {{ .Release.Namespace }}
```suggestion
  namespace: {{ .Release.Namespace | quote }}
```

The quote is needed for certain characters on the namespace

2021-02-25 11:20 UTC, erpel commented
Should I just apply these changes to the bitnami/postgresql chart in this PR as well? It seems like a good thing to keep them in sync.

2021-02-26 12:16 UTC, miguelaeh commented
Hi @erpel ,
I would create a different one and reference this one. Just to have one PR per chart. It is easier to review and to find the thread in case we need it in the future

2021-02-26 12:19 UTC, miguelaeh approved these changes
LGTM!

2021-02-26 12:19 UTC, merged