bitnami/kafka: Add affinity, tolerations, nodeSelector for kafka-exporter deployment
bitnami/charts pull request #5704
Opened 2021-03-05 16:32 UTC by srntqn

**Description of the change**

This PR adds ability to configure affinity, tolerations and nodeSelector for kafka-exporter.

**Benefits**

More flexible scheduling of the kafka-exporter in a cluster.

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

2021-03-08 16:19 UTC, rafariossaa requested changes
Hi,
  Thank you very much for this PR.
  Could you take a look to my comments ?

2021-03-08 16:19 UTC, rafariossaa commented on bitnami/kafka/README.md
> +| `metrics.kafka.tolerations`               | Tolerations for Kafka Exporter pod assignment                                                            | `[]`
There is a missing `|` at the end

2021-03-08 16:19 UTC, rafariossaa commented on bitnami/kafka/README.md
> +| `metrics.kafka.affinity`     | Affinity for Kafka Exporter pod assignment                                                                                       | `{}`
There is a missing `|` at the end

2021-03-08 16:19 UTC, rafariossaa commented on bitnami/kafka/README.md
> +| `metrics.kafka.resources.limits`       | Kafka Exporter container resource limits                                                                                         | `{}`
There is a missing `|` at the end

2021-03-08 18:50 UTC, srntqn commented on bitnami/kafka/README.md
> +| `metrics.kafka.tolerations`               | Tolerations for Kafka Exporter pod assignment                                                            | `[]`
@rafariossaa fixed! Please take a look.

2021-03-08 18:50 UTC, srntqn commented on bitnami/kafka/README.md
> +| `metrics.kafka.affinity`     | Affinity for Kafka Exporter pod assignment                                                                                       | `{}`
Fixed! Please take a look.

2021-03-08 18:50 UTC, srntqn commented on bitnami/kafka/README.md
> +| `metrics.kafka.resources.limits`       | Kafka Exporter container resource limits                                                                                         | `{}`
@rafariossaa fixed! Please take a look.

2021-03-09 16:43 UTC, rafariossaa commented
Hi,
  Could you take a look to the README merge conflict ?

2021-03-10 17:56 UTC, srntqn commented
@rafariossaa sorry, i didn't notice this conflict. 
I've resolved it.

2021-03-11 16:51 UTC, rafariossaa approved these changes
LGTM
Thanks !

2021-03-11 16:51 UTC, merged