[bitnami/spark] Added hostNetwork in the spark charts
bitnami/charts pull request #5705
Opened 2021-03-05 16:47 UTC by a-nldisr

Signed-off-by: Rogier Dikkes <1867776+a-nldisr@users.noreply.github.com>

**Description of the change**

The change adds hostNetwork to the spark worker and master. Gives people the ability to enable hostNetwork if they require host networking to connect to their workloads. 

**Benefits**

Enables hostNetwork in the bitnami spark chart. 

**Possible drawbacks**

The option to not use hostNetwork stays intact and therefore should have no impact. 

**Applicable issues**

None (yet), I can create an issue if requested. 

**Additional information**

The reason why I want to add this feature is that we are currently migrating from DCOS to Kubernetes. We use Spark to connect to various internal datastores which are reachable inside the DCOS cluster. In DCOS there is an ipvs based load balancer that offers internal URI's to connect from spark to the databases. While we are migrating our Spark workloads to Kubernetes we need to keep using the datastores. We therefore made an ipvs load balancer setup that bridges the Kubernetes cluster via IPVS to DCOS we however need to enable hostNetwork in all the pods that need to connect to the DCOS cluster. This feature was missing in the bitnami spark charts. 

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-03-08 08:56 UTC, miguelaeh requested changes
Thank you very much for the PR!

2021-03-08 08:56 UTC, miguelaeh commented on bitnami/spark/Chart.yaml
> +version: 5.2.4
```suggestion
version: 5.3.0
```

2021-03-08 15:30 UTC, a-nldisr commented on bitnami/spark/Chart.yaml
> +version: 5.2.4
Updated the version as requested.

2021-03-09 08:07 UTC, miguelaeh approved these changes
LGTM!

2021-03-09 08:07 UTC, merged