[bitnami/harbor] update harbor images
bitnami/charts pull request #5708
Opened 2021-03-06 13:50 UTC by lusu007

**Description of the change**

Update all Harbor images to their latest version. To provide Harbor 2.2.0.

**Benefits**

Harbor is up to date.

**Possible drawbacks**

None

**Applicable issues**

None

**Additional information**

None

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-03-08 08:38 UTC, javsalgar requested changes
Hi,

Thanks for the PR! Normally this kind of changes is done automatically by our pipeline. Let me trigger a build so this is not necessary.

2021-03-08 08:38 UTC, javsalgar commented on bitnami/harbor/Chart.yaml
> +version: 10.0.0
Hi,

I see that it is updating a minor version, so I don't see a strong reason for bumping the major version.

2021-03-08 08:39 UTC, javsalgar commented
I checked with the team and found some issues with the new Harbor version, we are working on it and we will automatically update the chart once we ensure it works without issues.

2021-03-08 10:05 UTC, lusu007 commented
Do you have a rough ETA for it? We need the new robot account features in the new version. 😅
If you need help with testing please contact me.

2021-03-09 08:53 UTC, javsalgar commented
Hi,

We expect to have it between this week and the next. Thanks for offering your help. When we have it ready we will ping you.

2021-03-13 11:08 UTC, lusu007 commented
I clone this pullrequest because harbor is now updated to Version 2.2.0

2021-03-13 11:08 UTC, closed without merging