[bitnami/kubewatch] Add priorityClassName support
bitnami/charts pull request #5720
Opened 2021-03-08 12:14 UTC by bugok

**Description of the change**

This adds the ability to set the `priorityClassName` property to the kubewatch pods.
This is copied from the memcached chart.

**Benefits**
This will enable to give a higher priority to the kubewatch pods.

**Possible drawbacks**
Can't think about any - as it's backwards compatible.

**Additional information**

Testing was done like so:
```
helm dependency build kubewatch
helm package kubewatch
helm upgrade -i kubewatch ~/sources/charts-1/bitnami/kubewatch-3.1.4.tgz -f ~/tmp/kubewatch.yaml -n monitoring
```

which contains this:
```
priorityClassName: 'system-cluster-critical'
```

See that the change took effect:
```
$ kubectl get pods -n monitoring | grep kubewatch
kubewatch-758c5b9745-4rwl8                                        1/1     Running   0          8m34s
```

See that the spec matches:
```
$ kubectl get pod kubewatch-758c5b9745-4rwl8 -n monitoring -o template --template={{.spec.priorityClassName}}'
system-cluster-critical
kubectl get pod kubewatch-758c5b9745-4rwl8 -n monitoring -o template --template={{.spec.priority}}
2000000000
```

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

2021-03-09 08:54 UTC, javsalgar requested changes
Thanks for the PR! Small change

2021-03-09 08:54 UTC, javsalgar commented on bitnami/kubewatch/Chart.yaml
> +version: 3.1.4
As it is adding a non-breaking feature, could you bump the minor version?

2021-03-09 15:12 UTC, bugok commented
I might have messed my branch here. Although the changed files look OK.

2021-03-10 08:25 UTC, javsalgar approved these changes
LGTM! Thanks

2021-03-10 08:25 UTC, merged