[bitnami/kafka] Usage of Host IPs for external service without autodiscovery
bitnami/charts pull request #5963
Opened 2021-03-30 11:48 UTC by sveba

Description of the change

HOST_IP environment variable is dependent from externalAccess.autoDiscovery.enabled This is not right. This is fix for that issue.

Benefits

Fix the issue

Possible drawbacks

Applicable issues

Additional information

Checklist

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-03-30 11:55 UTC, sveba commented
this is a result of the discussion for CR https://github.com/bitnami/charts/pull/5963

2021-03-31 08:03 UTC, sveba commented
We need this rather quick. Can someone pls review this PR.

2021-03-31 09:48 UTC, alemorcuq commented
> this is a result of the discussion from CR #5963

Thanks for the PR, @sveba! This links seems to be invalid (it points to this PR). Can I get a link to the discussion to have more context about this change?

2021-03-31 09:50 UTC, sveba commented
@alemorcuq sorry, I fixed the link

2021-03-31 10:12 UTC, alemorcuq requested changes
Thanks for the PR! Looks good, but I have one minor request.

2021-03-31 10:12 UTC, alemorcuq commented on bitnami/kafka/templates/statefulset.yaml
>                    fieldPath: status.hostIP
Let's keep this as it was before: only if the service type is NodePort.

2021-03-31 11:03 UTC, sveba commented
@alemorcuq done

2021-03-31 11:05 UTC, alemorcuq requested changes

2021-03-31 11:05 UTC, alemorcuq commented on bitnami/kafka/templates/statefulset.yaml
> +            {{- if eq .Values.externalAccess.service.useHostIPs "NodePort" }}
```suggestion
            {{- if eq .Values.externalAccess.service.type "NodePort" }}
```

2021-03-31 11:13 UTC, alemorcuq approved these changes

2021-03-31 11:13 UTC, merged