[bitnami/contour] Add the possibility to set HostIP
bitnami/charts pull request #6000
Opened 2021-04-03 12:13 UTC by bokysan

**Description of the change**

The cart does not allow setting the `hostIP` parameter on the
Envoy `DeamonSet`. This is useful in certain cases (e.g. with `k3s`
and single-node deployments) and should be possible.

This commit simply adds the possibility to set the `hostIP` on ports
exposed by Envoy.

**Benefits**

It's now able to run two Contour servers on the same host and same
ports with different IP addresses (e.g. for public and private IPs).

**Possible drawbacks**

None

**Applicable issues**

N/A

**Additional information**

N/A

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

2021-04-05 08:58 UTC, alemorcuq requested changes
Thanks for the PR! Please, see my suggestions below.

2021-04-05 08:58 UTC, alemorcuq commented on bitnami/contour/README.md
> +| `envoy.useHostIP`                          | Enable/disable `hostIP`
```suggestion
| `envoy.useHostIP`                          | Enable/disable `hostIP`                                                                                                                                                             | `false`                                                  |
```

2021-04-05 08:58 UTC, alemorcuq commented on bitnami/contour/templates/envoy/daemonset.yaml
> +              hostIP: {{ .Values.envoy.hostIPs.http }}
```suggestion
              hostIP: {{ .Values.envoy.hostIPs.https }}
```

2021-04-05 08:58 UTC, alemorcuq commented on bitnami/contour/values.yaml
> +  ## HTTP and HTTPS ports
```suggestion
  ## HTTP and HTTPS IPs
```

2021-04-08 16:46 UTC, bokysan commented
Changes accepted. Branch rebased.

2021-04-12 13:13 UTC, alemorcuq approved these changes
Thanks

2021-04-12 13:23 UTC, merged