[bitnami/dataplatform-bp2] Bump Elasticsearch version to latest major
bitnami/charts pull request #6062
Opened 2021-04-09 12:21 UTC by miguelaeh

**Description of the change**
Bump the ES version to the latest major. Since this chart was published yesterday afternoon for first time, we are going to skip the major version bump. Also, the new ES version only includes a license change so there will be no issues.

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-04-09 13:16 UTC, migruiz4 approved these changes
LGTM!

2021-04-09 13:37 UTC, migruiz4 requested changes
Sorry, I just noticed that the Elasticsearch chart 15.x.x hasn't been released yet in the helm repository.

```
> helm search repo bitnami/elasticsearch             
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
bitnami/elasticsearch   14.5.3          7.10.2          A highly scalable open-source full-text search ...
```

Also, I think this PR requires updating the dependencies so the Elasticsearch chart version is updated inside the `Chart.lock`

2021-04-22 13:12 UTC, migruiz4 commented
Elasticsearch 15.x.x has been released so you should be able to update the chart dependencies now

2021-04-23 08:09 UTC, carrodher approved these changes

2021-04-23 08:10 UTC, merged