[bitnami/kafka] Fix wrong type for listeners and advertisedListeners vars
bitnami/charts pull request #6069
Opened 2021-04-11 18:05 UTC by Jasstkn

Signed-off-by: Maria Kotlyarevskaya <jasssstkn@yahoo.com>

**Description of the change**

Fix wrong type of listeners and advertisedListeners. They are used as a string variables but in `values.yaml` and `README.md` they are declared as list

**Benefits**

Chart is deployed without errors.

**Possible drawbacks**

N/A

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-04-11 18:06 UTC, Jasstkn commented
> Great PR! Please pay attention to the following items before merging:
> 
> **Files matching `bitnami/*/values.yaml`:**
> 
> * [ ]  Is the PR adding a new container? Please reviewer, add it to the models (internal process)
> * [ ]  Is the PR adding a new parameter? Please, ensure it’s documented in the README.md
> 
> This is an automatically generated QA checklist based on modified files

Nothing from that list.

2021-04-12 07:45 UTC, juan131 approved these changes
Thanks for this contribution!

As you mentioned the Kafka image is expecting a "comma separated" string with the list of listeners or advertised listeners. See:

- https://github.com/bitnami/bitnami-docker-kafka#accessing-kafka-with-internal-and-external-clients

2021-04-12 07:52 UTC, juan131 requested changes
Thinking it twice... I think we should maintain the array format since it's more appropriate for this setting. Then, we can do sth like this in the `statefulset.yaml` to adapt the array to a comma separated string:
```yaml
            - name: KAFKA_CFG_LISTENERS
              {{- if .Values.listeners }}
              value: {{ join "," .Values.listeners }}
            ...
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              {{- if .Values.advertisedListeners }}
              value: {{ join "," .Values.advertisedListeners }}
```

2021-04-12 07:55 UTC, Jasstkn commented
> Thinking it twice... I think we should maintain the array format since it's more appropriate for this setting. Then, we can do sth like this in the `statefulset.yaml` to adapt the array to a comma separated string:
> 
> ```yaml
>             - name: KAFKA_CFG_LISTENERS
>               {{- if .Values.listeners }}
>               value: {{ join "," .Values.listeners }}
>             ...
>             - name: KAFKA_CFG_ADVERTISED_LISTENERS
>               {{- if .Values.advertisedListeners }}
>               value: {{ join "," .Values.advertisedListeners }}
> ```

Are you sure? Default value isn't formatted this way. I think it could be even more confusing.

2021-04-12 08:54 UTC, juan131 commented
> Are you sure?

IMHO, we should use arrays for this kind of settings. This is the native YAML way to deal with lists.

> Default value isn't formatted this way. I think it could be even more confusing.

What do you mean with "default value"?

2021-04-12 08:57 UTC, Jasstkn commented
> > Are you sure?
> 
> IMHO, we should use arrays for this kind of settings. This is the native YAML way to deal with lists.
> 
> > Default value isn't formatted this way. I think it could be even more confusing.
> 
> What do you mean with "default value"?

here: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L177-L184

2021-04-12 09:40 UTC, juan131 commented
> here: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L177-L184

That's the value for the environment variable, but that's different from the "chart value"

2021-04-12 09:44 UTC, Jasstkn commented
> > here: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L177-L184
> 
> That's the value for the environment variable, but that's different from the "chart value"

Ok, I got your point. I'll make required changes then.

2021-04-13 07:17 UTC, juan131 commented
Thanks @Jasstkn !!

2021-04-13 16:35 UTC, Jasstkn commented
> Thanks @Jasstkn !!

Added. Please, review

2021-04-14 06:44 UTC, juan131 requested changes
Thanks for the applying the suggestions! Please check my comments!
Also, you'll have to rebase your branch from master since other contributions also bumped the chart version.

2021-04-14 06:44 UTC, juan131 commented on bitnami/kafka/templates/statefulset.yaml
> +              value: {{ include "kafka.advertisedListeners" . }}
You'll also have to adapt the line below in the **scripts-configmap.yaml**:

- https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L110

2021-04-14 06:44 UTC, juan131 commented on bitnami/kafka/templates/statefulset.yaml
> +              value: {{ include "kafka.listeners" . }}
I'd directly used "join" here and avoid adding new macros to `_helpers.tpl`:
```suggestion
              value: {{ join "," .Values.listeners }}
```

2021-04-14 06:44 UTC, juan131 commented on bitnami/kafka/templates/statefulset.yaml
> +              value: {{ include "kafka.advertisedListeners" . }}
Same concern about avoiding new macros.

2021-04-14 07:43 UTC, juan131 approved these changes
LGTM

2021-04-14 07:44 UTC, Jasstkn commented
> Thanks for the applying the suggestions! Please check my comments!
> Also, you'll have to rebase your branch from master since other contributions also bumped the chart version.

Thank you for your review. I've dropped templates and move join to the statefulset and configmap. If you have any other feedback, I'll be glad to get it.

2021-04-14 08:11 UTC, merged