[bitnami/postgres-ha] Enable init-chmod-data when using extendedConf
bitnami/charts pull request #6206
Opened 2021-04-24 10:18 UTC by Librazy

**Description of the change**

Fix https://github.com/bitnami/charts/issues/6197 by enabling init-chmod-data initContainer when `postgresql.extendedConf` is not empty.

**Benefits**

`postgresql.extendedConf` works out of box and won't fails surprisingly with `'/bitnami/postgresql/conf/postgresql.conf': Permission denied` 

**Possible drawbacks**

An initContainer increase startup time and may requires a extra image. I don't know whether there is a better way to fix #1961 without initContainers.

**Applicable issues**

  - fixes #6197

**Additional information**

N/A

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-04-26 09:31 UTC, juan131 requested changes
I don't see any reason to enable the init container when using the "extended configuration" feature". 

This feature mounts a ConfigMap (read only) at `/bitnami/postgresql/conf/conf.d/`. Then, the configuration file (**postgresql.conf**) includes the directive below to include the extended configuration:

```
include_dir = 'conf.d'
```

See the volume mount points:

```
          volumeMounts:
            - name: postgresql-extended-config
              mountPath: /bitnami/postgresql/conf/conf.d/
            - name: data
              mountPath: /bitnami/postgresql
```

If you're installing the chart in a cluster with support for Security Context(s), the default securityContext should adapt the permissions in the data directory, and you shouldn't find any permissions issue. See:

```
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1001
```

2021-04-26 14:05 UTC, Librazy commented
This is how https://github.com/bitnami/charts/issues/1961 was fixed by @marcosbc 's https://github.com/bitnami/charts/pull/2140

2021-04-27 10:27 UTC, Mauraza commented
Hi @Librazy, 

Could you please test if the solution proposed by @juan131 works?

2021-04-28 05:59 UTC, Librazy commented
You can take a look at https://github.com/bitnami/charts/pull/2140 for reference.

My cluster supports fsGroup:
```yaml
# kubectl version -o yaml
clientVersion:
  buildDate: "2020-06-17T11:41:22Z"
  compiler: gc
  gitCommit: c96aede7b5205121079932896c4ad89bb93260af
  gitTreeState: clean
  gitVersion: v1.18.4
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-11-12T09:11:15Z"
  compiler: gc
  gitCommit: 7cd5e9086de8ae25d6a1514d0c87bac67ca4a481
  gitTreeState: clean
  gitVersion: v1.18.12
  goVersion: go1.13.15
  major: "1"
  minor: "18"
  platform: linux/amd64
```
## Let's install with extendedConf and disabled volumePermissions container
```yaml
# cat values.yml 
postgresql:
  extendedConf: |
    shared_buffers = 256MB
# volumePermissions:
#   enabled: true
```
```
# helm install pg ./postgresql-ha-6.9.1.tgz -f values.yml 
NAME: pg
LAST DEPLOYED: Wed Apr 28 05:25:12 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

PostgreSQL can be accessed through Pgpool via port 5432 on the following DNS name from within your cluster:

    pg-postgresql-ha-pgpool.default.svc.cluster.local

Pgpool acts as a load balancer for PostgreSQL and forward read/write connections to the primary node while read-only connections are forwarded to standby nodes.

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default pg-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To get the password for "repmgr" run:

    export REPMGR_PASSWORD=$(kubectl get secret --namespace default pg-postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run pg-postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:11.11.0-debian-10-r58 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h pg-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/pg-postgresql-ha-pgpool 5432:5432 &
    psql -h 127.0.0.1 -p 5432 -U postgres -d postgres
# kubectl logs -f pg-postgresql-ha-postgresql-0
postgresql-repmgr 05:25:29.39 
postgresql-repmgr 05:25:29.40 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 05:25:29.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 05:25:29.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 05:25:29.40 
postgresql-repmgr 05:25:29.42 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 05:25:29.44 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 05:25:29.45 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 05:25:29.45 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 05:25:29.53 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 05:25:29.53 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 05:25:29.54 INFO  ==> postgresql.conf file not detected. Generating it...
cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied
# kubectl logs -f pg-postgresql-ha-postgresql-1
postgresql-repmgr 05:25:28.96 
postgresql-repmgr 05:25:28.96 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 05:25:28.96 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 05:25:28.96 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 05:25:28.96 
postgresql-repmgr 05:25:28.98 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 05:25:29.00 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 05:25:29.01 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 05:25:29.01 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 05:25:29.05 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 05:25:29.06 INFO  ==> postgresql.conf file not detected. Generating it...
cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied
```
## When we enable volumePermissions container, it works fine.
```yaml
# cat values.yml 
postgresql:
  extendedConf: |
    shared_buffers = 256MB
volumePermissions:
  enabled: true
```
```
# helm install pg ./postgresql-ha-6.9.1.tgz -f values.yml 
# kubectl logs -f pg-postgresql-ha-postgresql-0
postgresql-repmgr 05:30:53.12 
postgresql-repmgr 05:30:53.12 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 05:30:53.12 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 05:30:53.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 05:30:53.13 
postgresql-repmgr 05:30:53.14 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 05:30:53.17 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 05:30:53.17 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 05:30:53.17 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 05:30:53.21 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 05:30:53.22 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 05:30:53.22 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 05:30:53.32 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 05:30:53.32 INFO  ==> Initializing Repmgr...
postgresql-repmgr 05:30:53.33 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 05:30:53.34 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 05:30:53.34 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 05:30:54.94 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 05:30:55.07 INFO  ==> Changing password of postgres
postgresql-repmgr 05:30:55.09 INFO  ==> Creating replication user repmgr
postgresql-repmgr 05:30:55.12 INFO  ==> Configuring replication parameters
postgresql-repmgr 05:30:55.15 INFO  ==> Configuring fsync
postgresql-repmgr 05:30:55.16 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 05:30:55.17 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 05:30:55.21 INFO  ==> Creating repmgr database: repmgr
postgresql-repmgr 05:30:55.62 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 05:30:55.83 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 05:30:55.95 INFO  ==> Registering Primary...
postgresql-repmgr 05:30:56.09 INFO  ==> Loading custom scripts...
postgresql-repmgr 05:30:56.10 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 05:30:56.31 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 05:30:56.34 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-04-28 05:30:56.382 GMT [257] LOG:  pgaudit extension initialized
2021-04-28 05:30:56.382 GMT [257] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-04-28 05:30:56.382 GMT [257] LOG:  listening on IPv6 address "::", port 5432
2021-04-28 05:30:56.387 GMT [257] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-04-28 05:30:56.429 GMT [257] L [...]

2021-04-29 07:55 UTC, juan131 reviewed
I understands what happens here...

The `/bitnami/postgresql/conf` directory exists by default in the image with the right permissions. See:

```console
$ docker run --rm -it bitnami/postgresql-repmgr:11 ls -la /bitnami/postgresql
total 12
drwxrwxr-x 3 0 postgres 4096 Apr 29 00:33 .
drwxr-xr-x 3 0 postgres 4096 Apr 29 00:33 ..
drwxrwxr-x 3 0 postgres 4096 Apr 29 00:33 conf
```

That said, when mounting the data volume (which is empty by default) at `/bitnami/postgresl` it's removed. Then, when mounting the "extendedConf" ConfigMap at `/bitnami/postgresl/conf/conf.d` it's created **BUT without writing permissions for the "group".**

As a consequence, the permissions **must** be adapted using the init container.

2021-04-29 07:55 UTC, juan131 commented on bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
> +      {{- if and .Values.persistence.enabled (or (or (not (empty .Values.postgresql.extendedConf)) (not (empty .Values.postgresql.extendedConfCM)) ) .Values.volumePermissions.enabled) }}
We can make this simpler. Please Try with:
```suggestion
      {{- if and .Values.persistence.enabled (or (or .Values.postgresql.extendedConf .Values.postgresql.extendedConfCM) .Values.volumePermissions.enabled) }}
```

2021-04-30 08:24 UTC, juan131 approved these changes
LGTM

2021-04-30 08:35 UTC, Mauraza reviewed
Hi @Librazy,

could you update the version?

2021-04-30 08:35 UTC, Mauraza commented on bitnami/postgresql-ha/Chart.yaml
> +version: 7.1.0
change the version to 7.2.0

2021-05-02 07:35 UTC, Librazy commented
Sorry for the delay and chart version is now updated

2021-05-03 06:37 UTC, merged

2022-01-14 13:03 UTC, acourouppe commented
Hi @Librazy, 
Why it is it required to enable persistence to be able to use extendedConf?
I mean, I'd like to use the extend conf but in dev we don't want to enable data persistence. With the current implementation, it looks like I'm forced to enable the persistence in order  for .Values.volumePermissions.enabled to be taken into account and the init-chmod-data container to be run.  Here is the condition. 

`{{- if and .Values.persistence.enabled (or (or (not (empty .Values.postgresql.extendedConf)) (not (empty .Values.postgresql.extendedConfCM)) ) .Values.volumePermissions.enabled) }}`

2022-01-17 07:18 UTC, juan131 commented
Hi @acourouppe 

AFAIK the init-chmod container isn't required if you're disabling persistence since the scenario I explained in [this comment](https://github.com/bitnami/charts/pull/6206#pullrequestreview-647910293) shouldn't be reproduced.

Could you please share the **values.yaml** you're using so I can reproduce the issue on my side? Please also share the chart version you're using.

2022-01-17 13:08 UTC, acourouppe commented
Hi @juan131 
I'm using Helm chart 8.1.3 with postgresqlImage docker image overridden to 13.5.0-debian-10-r35.

Actually from my observations: 
* extendedConf + volumePermissions=disabled +  persistence=disabled => exception - cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied
* extendedConf + volumePermissions=enabled +  persistence=disabled =>  exception -cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied
* extendedConf + volumePermissions=enabled + persistence=enabled => works
* extendedConf + volumePermissions=disabled + persistence=enabled => works as well...

My values file looks like this: 
```
postgresql-ha:
  enabled: true
  metrics:
    enabled:
      true
  persistence:
    enabled: true
  volumePermissions:
    enabled: true
  pgpool:
    replicaCount: 1
    customUsers:
      usernames: opf16_0_postgres
      passwords: password
  postgresql:
    password: password
    repmgrPassword: password
    database: bph
    replicaCount: 1
    initContainers:
      - name: bph-custom-init-scripts
        image: opf-docker.coastguard.clear2pay.com/test/postgres-test-opf:${project.version}
        command: ["/bin/sh", "-c", "unzip /tmp/bph-dbscripts.zip -d /tmp/${docker-postgres-schema} && chown -R 1001 /tmp/${docker-postgres-schema}"]
        volumeMounts:
          - name: bph-custom-init-scripts
            mountPath: /tmp/${docker-postgres-schema}
    extraVolumeMounts:
      - name: bph-custom-init-scripts
        mountPath: /tmp/${docker-postgres-schema}
      - name: bph-custom-init-scripts
        mountPath: /docker-entrypoint-initdb.d/startUpdateDb.sh
        subPath: startUpdateDb.sh
    extraVolumes:
      - name: bph-custom-init-scripts
        emptyDir: {}
    extraEnvVars:
      - name: "DB_UPDATE_OPTS"
        value: "-t"
    extendedConf: |-
      listen_addresses = '*'
      max_prepared_transactions = 400
      max_connections = 400
```

Here is the exception I get
```
postgresql postgresql-repmgr 12:53:59.50 DEBUG ==> Skipping: failed to get primary from the node 'ci-postgresql-ha-postgresql-0.ci-postgresql-ha-postgresql-headless.opf.svc.cluster.local │
│ postgresql postgresql-repmgr 12:53:59.51 INFO  ==> There are no nodes with primary role. Assuming the primary role...                                                                      │
│ postgresql postgresql-repmgr 12:53:59.54 INFO  ==> Preparing PostgreSQL configuration...                                                                                                   │
│ postgresql postgresql-repmgr 12:53:59.56 DEBUG ==> Injecting a new postgresql.conf file...                                                                                                 │
│ postgresql postgresql-repmgr 12:53:59.56 INFO  ==> postgresql.conf file not detected. Generating it...                                                                                     │
│ postgresql cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied 
```

2022-01-18 07:31 UTC, juan131 commented
Thanks for providing all this useful information, I really appreciate it!

Could you please give a try to the PR I just sent trying to fix this? Thanks in advance.