[bitnami/thanos] Adding sidecars to services with ingress
bitnami/charts pull request #6259
Opened 2021-04-29 22:29 UTC by pburgisser

**Description of the change**

Adding the possibility to add a sidecar container for each services that can be exposed with an ingress, so this services can be running behind a proxy like oAuth or a simple nginx proxy so access can be authenticated.

**Benefits**

Thanos components can be secured
**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

N/A

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-04-30 08:25 UTC, miguelaeh requested changes
Hi @pburgisser ,
Thank you very much for the PR!
Please check the suggestions I added

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/templates/bucketweb/deployment.yaml
> +{{ toYaml .Values.bucketweb.extraContainers | indent 8 }}
```suggestion
      {{ toYaml .Values.bucketweb.extraContainers | nindent 8 }}
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/templates/bucketweb/deployment.yaml
> +{{ toYaml .Values.bucketweb.extraContainers | indent 8 }}
You can also use the tplvalue function from common

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/templates/query-frontend/deployment.yaml
> +{{ toYaml .Values.queryFrontend.extraContainers | indent 8 }}
```suggestion
      {{ toYaml .Values.queryFrontend.extraContainers | nindent 8 }}
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/templates/query/deployment.yaml
> +{{ toYaml $query.extraContainers | indent 8 }}
```suggestion
      {{ toYaml $query.extraContainers | nindent 8 }}
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/templates/receive/statefulset.yaml
> +{{ toYaml .Values.receive.extraContainers | indent 8 }}
```suggestion
      {{ toYaml .Values.receive.extraContainers | nindent 8 }}
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/templates/ruler/statefulset.yaml
> +{{ toYaml .Values.ruler.extraContainers | indent 8 }}
```suggestion
      {{ toYaml .Values.ruler.extraContainers | nindent 8 }}
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  ## Optional additional containers (sidecar)
```suggestion
  ## Optional additional containers (sidecar)
  ##
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  extraContainers: []
```suggestion
  extraContainers: []
  ## Example:
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  ## Optional additional containers (sidecar)
```suggestion
  ## Optional additional containers (sidecar)
  ##
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  extraContainers: []
```suggestion
  extraContainers: []
  ## Example:
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  ## Optional additional containers (sidecar)
```suggestion
  ## Optional additional containers (sidecar)
  ##
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  extraContainers: []
```suggestion
  extraContainers: []
  ## Example:
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  ## Optional additional containers (sidecar)
```suggestion
  ## Optional additional containers (sidecar)
  ##
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  extraContainers: []
```suggestion
  extraContainers: []
  ## Example:
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  ## Optional additional containers (sidecar)
```suggestion
  ## Optional additional containers (sidecar)
  ##
```

2021-04-30 08:25 UTC, miguelaeh commented on bitnami/thanos/values.yaml
> +  extraContainers: []
```suggestion
  extraContainers: []
  ## Example:
```

2021-04-30 08:34 UTC, pburgisser commented
Hi @miguelaeh,

Thanks for the suggestions, they all have been integrated into the code!

Cheers

2021-05-03 08:27 UTC, miguelaeh requested changes
Hi @pburgisser ,
The `toYaml` lines are still not properly indented, could you please put them at the same indent level as the `if` line?
Also, it would be nice if you can use the `common.tplvalues` function instead of `toYaml`

2021-05-03 08:36 UTC, pburgisser commented
Hi @miguelaeh,
No problem!
Thanks

2021-05-04 07:54 UTC, miguelaeh approved these changes
Thank you very much for applying the changes!
LGTM!

2021-05-04 07:57 UTC, miguelaeh commented
Hi @pburgisser ,
It seems the linter complains about trailing spaces in the lines you added to the values.yaml, could you take a look? https://github.com/bitnami/charts/pull/6259/checks?check_run_id=2498630267

2021-05-04 07:58 UTC, pburgisser commented
Hi @miguelaeh,

Yep, I've just fix them 

Thanks!

2021-05-05 07:50 UTC, merged