[bitnami/postgresql-ha] - Added session affinity support in pgpool service
bitnami/charts pull request #6267
Opened 2021-04-30 22:54 UTC by adam-prohack

# Description of the change
When I run lots of microservics instances which connects to same database and same login, pgpool-II coulnd't properly cache session when runs in more than one pod. When pgpool runs in more than one pod, default service load balancing mechanism multiply frontend sessions and in the result multiply backend sessions. 

# Benefits
Better database resources protection and properly fronend session caching.

2021-05-03 08:05 UTC, carrodher requested changes
Thanks for your contribution, I just added some inline comments to follow the same approach used in other charts. Apart from that, it's needed to add the parameter in the values.yaml, under the `service:` block:
```yaml
   ## Control where client requests go, to the same pod or round-robin
   ## Values: ClientIP or None
   ## ref: https://kubernetes.io/docs/user-guide/services/
   ##
   sessionAffinity: "None"
```

2021-05-03 08:05 UTC, carrodher commented on bitnami/postgresql-ha/Chart.yaml
> +version: 7.1.1
As it's a feature addition, we should bump the minor version:
```suggestion
version: 7.2.0
```

2021-05-03 08:07 UTC, carrodher commented on bitnami/postgresql-ha/Chart.yaml
>  version: 7.2.0
A new version appeared in the meantime
```suggestion
version: 7.3.0
```

2021-05-04 06:38 UTC, adam-prohack commented
@carrodher thanks for your comments. All things are fixed. I am waiting for merge PR

2021-05-04 07:11 UTC, carrodher approved these changes
LGTM

2021-05-04 07:11 UTC, merged