[bitnami/external-dns] Update CRDs api version
bitnami/charts pull request #6294
Opened 2021-05-05 07:52 UTC by miguelaeh

**Description of the change**
Update CRD API version

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #4723

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

2021-05-05 16:00 UTC, marcosbc approved these changes
LGTM

2021-05-06 07:45 UTC, juan131 requested changes
Please document the upgrade path in the **README.md**.
I guess that users will have to delete the old CRDs when upgrading from `4.x.x` to `5.x.x`, so we should document that.

2021-05-06 09:17 UTC, juan131 approved these changes
LGTM with suggestion to improve the README.md

2021-05-06 09:17 UTC, juan131 commented on bitnami/external-dns/README.md
> +The CRD API version has changed. If you deployed the Helm Chart using `crd.create=true` you need to manually delete the old CRD before upgrading the release.
```suggestion
The CRD were updated according to the latest changes in the upstream project. As a consequence, the CRD API version was moved from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`.

If you deployed the Helm Chart using `crd.create=true` you need to manually delete the old CRD before upgrading the release as shown below:
```

2021-05-06 09:44 UTC, merged