[bitnami/mysql] add parameter to set up my_custom.cnf
bitnami/charts pull request #6424
Opened 2021-05-20 07:58 UTC by serg-bs

**Description of the change**
I need add to replica some additional config 
```replicate-ignore-table=logtable```
or on master 
```
[mysqld]
max_allowed_packet=32M
```
like describe 
https://github.com/bitnami/bitnami-docker-mysql#step-1-write-your-my_customcnf-file-with-the-following-content

**Applicable issues**

  - fixes #6423

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

2021-05-21 07:18 UTC, alemorcuq commented
Hi, @serg-bs. Thanks for the PR. I can see the chart already has two configuration sections: `primary.configuration`, where you can set all the configuration options you want in your `my.cnf` file, and a `primary.existingConfiguration` value where you can set a ConfigMap that holds your full configuration. They are also available for the secondary pods. Isn't this enough for you?

2021-05-24 05:36 UTC, serg-bs commented
Yes this section is optional, in my case developer don't want to know about all configuration esspecialy about directory structure. In postgres chart we have postgresqlExtendedConf, and it look quite convinient.

2021-05-27 08:04 UTC, alemorcuq requested changes
Could you also add support for an existing ConfigMap like in the PostgreSQL chart?

2021-05-28 10:38 UTC, serg-bs commented on bitnami/mysql/templates/secondary/configmap.yaml
> +  my.cnf: |+
That is most important changes. Whithout this changes config not work.
trailing newline is important in my.cnf
`!include /opt/bitnami/mysql/conf/bitnami/my_custom.cnf` after this one should be newline

2021-06-18 01:24 UTC, closed without merging