[bitnami/kibana] Add Kibana-server SSL and Elasticsearch SSL
bitnami/charts pull request #6487
Opened 2021-05-27 13:20 UTC by migruiz4

**Description of the change**

Adds support for Elasticsearch X-Pack security features (Basic authentication and encrypted REST API).

Additionally, the Kibana Web server can now be configured with TLS certificates to serve clients via HTTPS (`server.ssl` settings). It is not related to X-Pack Security and does not need Elasticsearch to be configured with SSL

**Benefits**

Additional options to communicate with Elasticsearch.
- Adds Elasticsearch SSL settings:
    - Trusted CAs in PEM or PKCS12 format.
    - Verification mode.
- Adds Kibana credentials to log into Elasticsearch (kibanaUser:kibanaPassword). **Note:** this is the user used by Kibana to manage things such as the `.kibana` index, where it stores visualizations, dashboards, and settings. It is not necessarily the same user used to log into the UI.

Kibana Web server SSL settings.
- The kibana server can be configured using PKCS12 or PEM certificates.
- Adds support for autoGenerated certificates (not recommended for production environments).
 
**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-05-27 13:21 UTC, migruiz4 commented
Pending:
- Add a section documenting the new features and values in the README.md
- Add validations.

2021-05-28 07:54 UTC, alvneiayu requested changes

2021-05-28 07:54 UTC, alvneiayu commented on bitnami/kibana/templates/deployment.yaml
> +      annotations:
If you don't set up podAnnotations and you don't use TLS, I think that annotations will be empty no? Is it works?

2021-05-28 08:04 UTC, alvneiayu approved these changes
LGTM

2021-06-16 09:31 UTC, alvneiayu approved these changes
LGTM

2021-09-01 07:08 UTC, juan131 approved these changes
LGTM

2021-09-02 07:39 UTC, merged