[bitnami/zookeeper] Add selector to pvc
bitnami/charts pull request #6505
Opened 2021-05-29 17:43 UTC by mmenbawy

**Description of the change**

Add selector for Zookeeper data PVC and Zookeeper dataLogDir PVC, aiming to further filter the set of volumes. Only the volumes whose labels match the selector can be bound to the claim.
Inspired from this existing feature in [bitnami/postgres](https://github.com/bitnami/charts/blob/master/bitnami/postgresql) chart.

> <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector>

**Benefits**

Ability to select an existing Persistent Volume using `matchLabels` or `matchExpressions`. 

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-05-31 08:36 UTC, miguelaeh requested changes
Thank you very much for the PT @mmenbawy .

2021-05-31 08:36 UTC, miguelaeh commented on bitnami/zookeeper/values.yaml
> +
```suggestion
    size: 8Gi
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    ## The value is evaluated as a template
    ##
    # existingClaim:

    ## Selector to match an existing PersistentVolume
    ## E.g.
    ## selector:
    ##   matchLabels:
    ##     app: my-app
    ##
    selector: {}

```

2021-05-31 08:36 UTC, miguelaeh commented on bitnami/zookeeper/values.yaml
> +  selector: {}
```suggestion
  ## Selector to match an existing PersistentVolume
  ## E.g.
  ## selector:
  ##   matchLabels:
  ##     app: my-app
  ##
  selector: {}
```

2021-06-01 07:54 UTC, miguelaeh reviewed
Hi @mmenbawy ,
Please take a look at the suggestions too. There are some changes needed yet.

2021-06-07 09:12 UTC, miguelaeh requested changes
Hi @mmenbawy ,
I just noticed there is an extra`-` at the `end` directives, please remove them since it could break the template

2021-06-07 09:12 UTC, miguelaeh commented on bitnami/zookeeper/templates/statefulset.yaml
> +        {{- end -}}
```suggestion
        {{- end }}
```

2021-06-07 09:12 UTC, miguelaeh commented on bitnami/zookeeper/templates/statefulset.yaml
> +        {{- end -}}
```suggestion
        {{- end }}
```

2021-06-07 18:24 UTC, mmenbawy commented
> Hi @mmenbawy ,
> I just noticed there is an extra`-` at the `end` directives, please remove them since it could break the template

It's not an excess dash. This will consume any trailing white space and newline.
It will not make any difference since it is followed by another `{{- end }}`
I have checked it using `helm template test-format -f bitnami/zookeeper/my-value.yml  bitnami/zookeeper/`
**my-value.yml:**
```yaml
dataLogDir: true
persistence:
  selector:
    matchLabels:
      app: my-app
  dataLogDir:
    selector:
      matchLabels:
        app-datalog: my-app
```

2021-06-08 09:48 UTC, miguelaeh approved these changes
Thank you very much @mmenbawy for addressing the changes.
About the trailing `-`, we cannot assume that it will not fail checking the next line since a change can be done that will need to modify the previous line to fix the template, they are usually errors not easy to find, so we like to leave the templates as clean as possible.

2021-06-08 09:49 UTC, merged