[bitnami/minio] Make runAsNonRoot configurable
bitnami/charts pull request #6538
Opened 2021-06-02 07:47 UTC by ckotzbauer

Signed-off-by: Christian Kotzbauer christian.kotzbauer@gmail.com

**Description of the change**
Add "runAsNonRoot" config-option to the securityContext.

**Benefits**
It is possible to set "runAsNonRoot" to "true" now.

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-06-02 12:12 UTC, carrodher requested changes
Thanks for your contribution, please, take a look at my comments

2021-06-02 12:12 UTC, carrodher commented on bitnami/minio/README.md
> +| `securityContext.runAsNonRoot`    | Avoid running as root User                                                                | `false`                        |
Running containers as non root is a best practices in terms of securizing containers, so I think the default approach should be the opposite, by default the security context should be set to use `true` as value for `runAsNonRoot`
```suggestion
| `securityContext.runAsNonRoot`    | Run container as non-root user                                                        | `true`                         |
```

+info: https://docs.bitnami.com/tutorials/work-with-non-root-containers/

2021-06-02 12:12 UTC, carrodher commented on bitnami/minio/values.yaml
> +  runAsNonRoot: false
See above description
```suggestion
  runAsNonRoot: true
```

2021-06-02 12:19 UTC, ckotzbauer commented
@carrodher I addressed your comments.

2021-06-02 15:08 UTC, ckittelmann approved these changes

2021-06-02 21:42 UTC, carrodher approved these changes
LGTM, thanks. I just launched our internal test & release pipeline, if everything works as expected the PR should be automatically closed after some time

2021-06-02 23:58 UTC, merged

2021-06-04 05:24 UTC, ckotzbauer commented
@carrodher  Thanks for your review. Is there any problem in the publish-pipeline? The changes from this PR are still not published.

2021-06-04 06:30 UTC, carrodher commented
Yes, it's true. We test all our charts on top of different k8s clusters such as GKE, AKS, TKG, IKS, etc.

In this case, there is an issue with IKS. It is not related to the PR but the cluster infrastructure itself, once solved, the chart should be automatically released. Sorry for the delay

2021-06-04 07:07 UTC, ckotzbauer commented
Thanks for your fast reply. That's okay, just a bit intransparent for contributors 😄 😉

2021-06-04 07:50 UTC, carrodher commented
You can find more info about this process in the contributing guideline, see https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#pr-approval-and-release-process 😉

2021-06-04 08:16 UTC, carrodher commented
The new version should be available after running `helm repo update`:
```console
$ helm search repo bitnami/minio
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/minio	6.8.0        	2021.5.27  	Bitnami Object Storage based on MinIO(R) is an ...
```

Thanks again for your contribution!