[bitnami/elasticsearch] Elasticsearch hpa
bitnami/charts pull request #6562
Opened 2021-06-04 07:39 UTC by mahgo

**Description of the change**
Added Horizontal Pod Autoscaler to the Elasticsearch chart

**Benefits**
 Being able to enable HPAs when using the chart.

**Applicable issues**

  - fixes #6551

**Additional information**
Let me know if I've missed anything, there was more to do in this chart compared to the other 2 PRs I did adding HPAs (Magento, Redis).

I also tidied up the readme parameters as it was previously one big table.

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-06-04 13:28 UTC, alemorcuq requested changes
Thank you very much for the PR, @mahgo !

2021-06-04 13:28 UTC, alemorcuq commented on bitnami/elasticsearch/templates/master-hpa.yaml
> +    app.kubernetes.io/component: data
```suggestion
    app.kubernetes.io/component: master
```

2021-06-07 00:08 UTC, mahgo commented
Fixed.

2021-06-07 08:26 UTC, alemorcuq approved these changes
Thanks!

2021-06-07 08:27 UTC, merged