[bitnami/discourse] Add SMTP variables
bitnami/charts pull request #6652
Opened 2021-06-14 04:29 UTC by kxesd

**Description of the change**

This PR adds all the SMTP environment variables as values in the helm chart.

**Benefits**

Allows configuring SMTP environment variables in the helm chart.

**Additional information**

Previously `bitnami/discourse/templates/secrets-discourse.yaml` would only ever have a single value, `discourse-password`, however sometimes it may now have both (`discourse-password` and `smtp-password`) or (one of them) or (none at all). I've changed the logic and it seems to handle all of these cases fine.

NOTE: maybe there needs to be warning added around specifying either `discourse.smtp.password` OR `discourse.smtp.existingSecret`. Currently if you specify both `discourse.smtp.existingSecret` will take priority.

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-06-14 15:23 UTC, alemorcuq requested changes
Thanks for the PR, @kxesd. Please, check my comments.

2021-06-14 15:23 UTC, alemorcuq commented on bitnami/discourse/templates/secrets-discourse.yaml
> +  {{- if and (.Values.discourse.smtp.password) (not .Values.discourse.smtp.existingSecret) }}
We should probably check for `smtp.enabled` here as well.

2021-06-14 15:23 UTC, alemorcuq commented on bitnami/discourse/Chart.yaml
> +version: 4.1.3
Version should be a new minor since we are adding a new feature to the chart.

2021-06-15 03:15 UTC, kxesd commented
Thanks @alemorcuq. I've made the changes as per your comments.

2021-06-17 10:03 UTC, alemorcuq approved these changes
Thanks!

2021-06-17 10:04 UTC, merged