[bitnami/mysql] add networkpolicy for primary (#6720)
bitnami/charts pull request #6734
Opened 2021-06-23 01:37 UTC by bynare

**Description of the change**

This changes adds the ability to enable and configure a Network Policy on the primary.

**Benefits**

Better security.

**Possible drawbacks**
n/a

**Applicable issues**

  - fixes #6720

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-06-23 15:06 UTC, migruiz4 requested changes
Hi @bynare,

Thank you very much for your contribution! 

I have suggested some changes, could you please have a look?

2021-06-23 15:06 UTC, migruiz4 commented on bitnami/mysql/templates/networkpolicy.yaml
> +              role: read
The MySQL replicas do not have a label `role: read`. Instead they have `app.kubernetes.io/component: secondary`.

2021-06-23 22:09 UTC, bynare commented
Hey @migruiz4, 

Thanks for the review! :)

I've amended the things you've pointed out - thanks!

2021-06-24 14:44 UTC, migruiz4 commented
Thank you very much for applying the suggestions!

There is one more thing I'd like to discuss with you. Providing a NetworkPolicy that only applies to the primary nodes seems incomplete.

For example, without a Network policy for secondary replicas, metrics wouldn't be accessible for all the pods.

We should cover both the primary node and secondary replicas with a single networkPolicy. Rename `primary.networkPolicy.*` as `networkPolicy.*` and remove "app.kubernetes.io/component: primary" from the networkPolicy podSelector.

Or otherwise, add a networkPolicy for the secondary replicas (`secondary.networkPolicy.*`) and rename the template `networkpolicy.yaml` to `primary/networkpolicy.yaml`.

Both approaches would be fine for me, feel free to let me know what you think.

2021-06-28 02:59 UTC, bynare commented
All good @migruiz4 - I was in two minds initially too: whether to include secondary in this.

> We should cover both the primary node and secondary replicas with a single networkPolicy. Rename primary.networkPolicy.* as networkPolicy.* and remove "app.kubernetes.io/component: primary" from the networkPolicy podSelector.

^ I've made changes to go with this option you suggested ;)

Thanks again for reviewing and bearing with me!

2021-06-28 14:51 UTC, migruiz4 approved these changes
Looks good to me!

Thank you for your contribution!

2021-06-28 14:51 UTC, merged