mongo resources takes namespace from release runtime
bitnami/charts pull request #6836
Opened 2021-07-04 11:31 UTC by korenlev

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-07-05 07:42 UTC, Mauraza commented
Hi @korenlev,

Could you explain a little about your change? Why have you changed the examples?
Please check the last item of the checklist.

2021-07-05 09:24 UTC, korenlev commented
the purpose is to not use a hard-coded namespace, make it dynamic

failure is environment specific (it works in my build cluster):
"1 node(s) had taints that the pod didn't tolerate."

2021-07-06 08:25 UTC, Mauraza requested changes
Hi @korenlev,

Please check the last item of the checklist: 
- Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-07-06 08:25 UTC, Mauraza commented on bitnami/mongodb/values.yaml
> +##       app.kubernetes.io/instance: '{{ .Release.Namespace }}'
app.kubernetes.io/instance is not the '{{ .Release.Namespace }}'

2021-07-06 08:25 UTC, Mauraza commented on bitnami/mongodb/values.yaml
> +##       value: "app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=$(NAMESPACE),app.kubernetes.io/name=mongodb"
could you move this to the original lines?

2021-07-27 01:22 UTC, closed without merging