[bitnami/contour] Update tlscertificatedelegations.projectcontour.io v0.2.9 > v0.5.0
bitnami/charts pull request #6919
Opened 2021-07-12 06:24 UTC by VA-PLE

Update tlscertificatedelegations.projectcontour.io

2021-07-12 07:47 UTC, Mauraza requested changes
Hi @VA-PLE,

Thanks for the PR! 
Could you update the version of the chart?

2021-07-12 07:48 UTC, Mauraza requested changes

2021-07-12 07:48 UTC, Mauraza commented on bitnami/contour/resources/tlscertificatedeligations.yaml
> +          specification. See design/tls-certificate-delegation.md for details.
Could you leave it as it was before?

2021-07-12 07:48 UTC, Mauraza commented on bitnami/contour/resources/tlscertificatedeligations.yaml
> +              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
same here

2021-07-12 07:48 UTC, Mauraza commented on bitnami/contour/resources/tlscertificatedeligations.yaml
> +              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
same
could you leave it as it was before in all the descriptions?

2021-07-13 12:02 UTC, VA-PLE commented
@Mauraza i used data from official contour.yaml https://raw.githubusercontent.com/projectcontour/contour/release-1.17/examples/render/contour.yaml

2021-07-14 06:38 UTC, Mauraza commented
Hi @VA-PLE,

The length of the line is a style parameter, the content will be the same.

2021-07-14 10:29 UTC, closed without merging