[bitnami/postgresql] Add option to create services for each read replica
bitnami/charts pull request #6990
Opened 2021-07-19 02:56 UTC by deefdragon

**Description of the change**
Add option to create services for each read replica (default disabled)
Add option to create a service that connects to all read replicas. (the existing read-replica service, default enabled)

**Benefits**
Allows programs that manage connection to replicas manually to do so.
Also allows for the disabling of the service that connects to all read-replicas if not needed

**Possible drawbacks**
Read-Replica unique services do not have options for LoadBalancers, Node Ports, or Setting ClusterIP.

**Applicable issues**
  - fixes #6954

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-07-19 08:05 UTC, javsalgar commented
Thank you for the PR! We will look into it

2021-07-19 08:37 UTC, deefdragon commented
Overlooked the pattern on the values. Was not aware that was how they were updated. Just Pushed a fix. 
Might be worth denoting the proper way to update the readme on the checklist and the contribution guidelines.

2021-07-20 07:55 UTC, javsalgar requested changes
Thank you! Small change requested

2021-07-20 07:55 UTC, javsalgar commented on bitnami/postgresql/templates/svc-read-set.yaml
> +{{- $serviceLoadBalancerIP := coalesce .Values.readReplicas.service.loadBalancerIP .Values.service.loadBalancerIP -}}
Remove the variables that are not used

2021-07-20 07:59 UTC, deefdragon commented on bitnami/postgresql/templates/svc-read-set.yaml
> +{{- $serviceLoadBalancerIP := coalesce .Values.readReplicas.service.loadBalancerIP .Values.service.loadBalancerIP -}}
resolved

2021-07-20 08:01 UTC, javsalgar approved these changes
Thank you! LGTM

2021-07-20 08:03 UTC, deefdragon commented
I committed a test file, and it looks like I need to merge in anyway. will be fixed shortly.

2021-07-21 07:37 UTC, merged