[bitnami/grafana-operator] extraVolumes, extraVolumeMounts, sidecars
bitnami/charts pull request #7034
Opened 2021-07-23 03:04 UTC by joshuasimon-taulia

**Description of the change**

Add additional extraVolumes & extraVolumeMounts parameters to the grafana deployment. one example use case is running a cloudsql-proxy sidecar

**Benefits**

Users can configure their own volumes.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

mostly copied from the bitnami haproxy chart

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-07-23 07:26 UTC, migruiz4 requested changes
Hi @joshuasimon-taulia,

Thank you very much for your contribution!

Your PR looks good to me, but I left some comments requesting minor changes.  Could you please have a look at them?

2021-07-23 07:26 UTC, migruiz4 commented on bitnami/grafana-operator/values.yaml
> +  ## @param sidecars Add additional sidecar containers to the grafana pod(s)
Could you please add this small change?
```suggestion
  ## @param grafana.extraVolumes Optionally specify extra list of additional volumes for the grafana pod(s)
  ##
  extraVolumes: []
  ## @param grafana.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the grafana container(s)
  ##
  extraVolumeMounts: []
  ## @param grafana.sidecars Add additional sidecar containers to the grafana pod(s)
```

2021-07-23 17:46 UTC, joshuasimon-taulia commented
done

2021-07-26 06:32 UTC, migruiz4 approved these changes
Thanks @joshuasimon-taulia, looks good to me!

2021-07-26 06:33 UTC, merged