Kibana chart should have service account
bitnami/charts pull request #7060
Opened 2021-07-26 23:44 UTC by jeff-hammel-leapyear

**Description of the change**

This allows the specification of a service account for Kibana.  See also https://github.com/bitnami/charts/issues/7059

**Benefits**

You should now be able to specify security contexts to a particular service account, not just defaults.

**Possible drawbacks**

None that I can think of.

**Applicable issues**

  - fixes #7059 

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-08-04 23:34 UTC, jeff-hammel-leapyear commented
I'm not going to have a chance to look at this soon.  Could someone please comment on what needs to be done to get this PR in a state?  Alternately, if someone could shepherd this in, I would be grateful.

2021-08-05 10:42 UTC, miguelaeh requested changes
Hi @jeff-hammel-leapyear ,
Thank you very much for the change.
Please take a look at my comments, also don't forget to bump the chart version. There is a checklist on the PR comment that you should complete.

2021-08-05 10:42 UTC, miguelaeh commented on bitnami/kibana/templates/serviceaccount.yaml
> +{{- end }}
Could you please base on the following service account in order to standardize it please? https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/serviceaccount.yaml

2021-08-05 10:42 UTC, miguelaeh commented on bitnami/kibana/templates/deployment.yaml
> +          serviceAccountName: {{ .Values.serviceAccount.name }}
We use a template in order to render the proper serviceAccount name, you can base on the following: https://github.com/bitnami/charts/blob/c10c7f4015d1ed0bf52ed10f9cd0cc6fb7d94910/bitnami/redis/templates/_helpers.tpl#L141

2021-08-09 20:51 UTC, james-pollard-leapyear commented
@miguelaeh Hi, Jeff's teammate here. He's on vacation for a while and I imagine you can understand that this change isn't a priority for us. Please consider his change a PoC and take lead on shepherding this change through.

Thanks for getting back to us!

2021-08-12 16:02 UTC, Mauraza commented
Hi @james-pollard-leapyear,

I just create a new PR with the change.

2021-08-12 22:17 UTC, james-pollard-leapyear commented
> I just create a new PR with the change.

Excellent - thank you! feel free to close out our PR here

2021-08-19 10:07 UTC, juan131 commented
Implemented at https://github.com/bitnami/charts/pull/7211

2021-08-19 10:07 UTC, closed without merging

2021-08-19 16:15 UTC, james-pollard-leapyear commented
Thanks a bunch!