Support Kubernetes 1.20 - HashiCorp Consul helm Chart
bitnami/charts pull request #7063
Opened 2021-07-27 07:37 UTC by Shahard2

The next flag got deprecated since k8s 1.20:

`service.alpha.kubernetes.io/tolerate-unready-endpoints: true`

so now we need to use:

`publishNotReadyAddresses: true`

if we don't change the flag, the consul pod will be in a crash loop with this errors:

`13:59:59.27 13:59:59.27 Welcome to the Bitnami consul container 13:59:59.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-consul 13:59:59.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-consul/issues 13:59:59.27 13:59:59.28 INFO ==> ** Starting Consul setup ** 13:59:59.30 INFO ==> Validating settings in CONSUL_* env vars.. 13:59:59.37 ERROR ==> The value for CONSUL_RETRY_JOIN_ADDRESS should be an IPv4 address or it must be a resolvable hostname`

2021-07-27 08:03 UTC, javsalgar commented
Hi,

Thank you so much for the PR! Could you bump the patch version of the chart?

2021-07-27 08:07 UTC, Shahard2 commented
> Hi,
> 
> Thank you so much for the PR! Could you bump the patch version of the chart?


Sure,
done mate

2021-07-27 09:14 UTC, javsalgar requested changes

2021-07-27 09:14 UTC, javsalgar commented on bitnami/consul/Chart.yaml
> +- name: common
It seems that you applied an auto-formatter incompatible with our yaml conventions. Could you fix it?

2021-07-28 08:01 UTC, javsalgar requested changes

2021-07-28 08:01 UTC, javsalgar commented on bitnami/consul/Chart.yaml
> +  repository: https://charts.bitnami.com/bitnami
The indentation is incorrect, check the original one

2021-07-29 08:06 UTC, javsalgar approved these changes
Thank you! LGTM

2021-07-29 08:06 UTC, merged