[bitnami/postgresql] Add relabelings / metricRelabelings to ServiceMonitor
bitnami/charts pull request #7082
Opened 2021-07-28 18:02 UTC by pbrissaud

Related #2307 

[ x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
[ x ] Variables are documented in the README.md
[ x ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

2021-07-29 14:26 UTC, alemorcuq requested changes
Thanks!

2021-07-29 14:26 UTC, alemorcuq commented on bitnami/postgresql/README.md
> +| `metrics.serviceMonitor.metriRelabelings`     | ServiceMonitor metricRelabelings. Value is evaluated as a template
```suggestion
| `metrics.serviceMonitor.metricRelabelings`     | ServiceMonitor metricRelabelings. Value is evaluated as a template                                                                                                   | `[]`                                                         |
```

2021-07-29 18:08 UTC, pbrissaud commented on bitnami/postgresql/README.md
> +| `metrics.serviceMonitor.metriRelabelings`     | ServiceMonitor metricRelabelings. Value is evaluated as a template
Thanks !

2021-08-02 10:32 UTC, alemorcuq approved these changes
Thanks!

2021-08-02 10:32 UTC, merged