Zookeeper topology
bitnami/charts pull request #7137
Opened 2021-08-04 10:57 UTC by endika-ravn

Description of the change

This change enhances the chart to support Topology Spread Constraints for assignment pods spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains. This can help to achieve high availability as well as efficient resource utilization.

Benefits

Users have an optional to use Topology Spread Constraints

Possible drawbacks

None

Applicable issues

Additional information

Copied mostly from #6081

Checklist

Chart version bumped in Chart.yaml according to semver.
Variables are documented in the README.md

Title of the PR starts with chart name (e.g. [bitnami/chart])

⚠️ Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the kubeapps repository. This is only a synchronized mirror.

2021-08-05 11:01 UTC, marcosbc requested changes
Thanks for the contribution! Could you have a look at my comments? Apart from that it looks fine.

2021-08-05 11:01 UTC, marcosbc commented on bitnami/zookeeper/Chart.yaml
> +version: 7.2.0
Could you fix the lint error? It is probably happening due to the text editor, if you simply save the file with another one (i.e. `vim` or `emacs`) it should fix the issue.

2021-08-06 19:48 UTC, endika-ravn commented on bitnami/zookeeper/values.yaml
> +## Topology Spread Constraints for pod assignment spread across your cluster among failure-domains. Evaluated as a template
added

2021-08-06 19:48 UTC, endika-ravn commented on bitnami/zookeeper/templates/statefulset.yaml
> +      { { - end } }
the editor auto style tricked me

2021-08-09 08:08 UTC, marcosbc approved these changes
LGTM, thanks for the contribution!

2021-08-09 08:08 UTC, merged