[bitnami/mongodb] Configurable admin/root user name
bitnami/charts pull request #7229
Opened 2021-08-16 08:42 UTC by axdotl

**Description of the change**

With this change, the name becomes configurable for the admin user.

**Benefits**

Some users prefer to name the user `admin` (or completely different) instead of `root`.

**Possible drawbacks**

None known

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-08-17 11:22 UTC, rafariossaa commented
Hi,
  This LGTM but let me bring in other team mate to have a look into it. 
  @juan131 Could you take a look into this ?

2021-09-06 06:37 UTC, juan131 requested changes
Hi @axdotl 

Sorry for the late review, I missed this.

---

Does this PR has an associated PR to modify the [Bitnami MongoDB container](https://github.com/bitnami/bitnami-docker-mongodb)? AFAIK, this container doesn't support any `MONGODB_ROOT_USER` env. variable (see [mongodb-env.sh](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/5.0/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh)) and assumes the user is "root", see:

- https://github.com/bitnami/bitnami-docker-mongodb/blob/master/5.0/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L506

2021-09-06 06:37 UTC, juan131 commented on bitnami/mongodb/values.yaml
> +  rootUser: "root"
Double-quotes aren't necessary.
```suggestion
  rootUser: root
```

2021-09-09 06:17 UTC, ricoberger commented
Hi @juan131, thanks for your feedback. I created a PR in the [bitnami/bitnami-docker-mongodb](https://github.com/bitnami/bitnami-docker-mongodb), which adds the `MONGODB_ROOT_USER` to the Docker images: https://github.com/bitnami/bitnami-docker-mongodb/pull/291.

2021-09-13 13:54 UTC, rafariossaa commented
LGTM.

2021-09-13 13:55 UTC, merged