Update apiVersion of PDB to policy/v1
bitnami/charts pull request #7368
Opened 2021-09-01 11:45 UTC by tomislater

According to https://kubernetes.io/docs/reference/using-api/deprecation-guide/ we can start using `policy/v1` in Kubernetes `1.21.

Without that you can observe such things in logs:

```
W0901 11:28:35.264440      91 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0901 11:28:35.269403      91 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0901 11:28:35.297605      91 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```

2021-09-01 12:05 UTC, tomislater commented
Hmm, maybe I should apply this manifest only on 1.21+ clusters? I think I can do that in Helm.

2021-09-02 08:29 UTC, miguelaeh requested changes
HI @tomislater ,

> Hmm, maybe I should apply this manifest only on 1.21+ clusters? I think I can do that in Helm.

Yes, it should be done in a backwards compatible way. We already a function for that, you can use `"common.capabilities.policy.apiVersion"`. The definition is at https://github.com/bitnami/charts/blob/6ec60956956f243967a5cdfee515c484627a4de3/bitnami/common/templates/_capabilities.tpl#L21

Apart from that, the Chart version bump is missing on the PR

2021-09-03 08:11 UTC, miguelaeh approved these changes
LGTM!

2021-09-03 10:31 UTC, tomislater commented
Hmm, what should I do about `Lint and Test Charts`? 

```
>>> kubectl logs haproxy-esukdd8arv-984949548-wqthr --namespace haproxy-esukdd8arv --container haproxy
Server be_main/web1 is DOWN, reason: Layer4 timeout, check duration: 2003ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
backend be_main has no server available!
Warning:   (1) : Server be_main/web1 is DOWN, reason: Layer4 timeout, check duration: 2003ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Notice:    (1) : haproxy version is 2.4.0-6cbbecf097
Notice:    (1) : path to executable is /opt/bitnami/haproxy/sbin/haproxy
[ALERT]    (1) : backend 'be_main' has no server available!
```

Looks like a problem with defaults? (timeout or retry). But, I did not touch it 🤔

2021-09-03 10:32 UTC, tomislater commented
Ach, every other PR also failed on the same step: https://github.com/bitnami/charts/pulls?q=is%3Apr+haproxy+is%3Aclosed

2021-09-06 08:03 UTC, miguelaeh commented
Hi @tomislater ,
Don't worry about that job, it always fails for this chart due to it cannot be installed in the Kind cluster the job deploys.

2021-09-06 08:03 UTC, merged