[bitnami/postgresql]
bitnami/charts pull request #7555
Opened 2021-09-21 11:10 UTC by bbaudelet

**Description of the change**

Add template render for extraVolumes on sts and for the additionalLabels on the serviceMonitor.

**Benefits**

This modification makes possible to use some variables such as Release.Name on ExtraVolumes part.
as exemple it allows the user to mount configmaps which may have a name linked to  release name.

**Possible drawbacks**
No drawbacks, no impact on current usage. 

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-09-22 10:26 UTC, alvneiayu requested changes
Hi @bbaudelet

First of all, thanks a lot for your PR and your time.

I included several comments in the PR. Moreover, you are having linter errors in your PR. I included a comment inside the code to fix one of them but the other one must be fixed bumping the Zookeeper version as you did in Postgresql. 

Please, could you edit the PR title, right now is showing only "[bitnami/postgresql]". Please, edit it to include more information and the zookeeper chart.

This is a personal suggestion for the future, send two PRs separated in the future (one for Postgresql and one for Zookeeper) but this is a personal opinion. I think that it will be more easy for you for describing the changes with a title and the description with two different PRs.

So, let me know if I can help you with something.

Thanks a lot

Álvaro

2021-09-22 10:26 UTC, alvneiayu commented on bitnami/postgresql/README.md
> +| `primary.extraVolumes`                        | Extra volumes to add to the pods (postgresql primary), the value is evaluated as a template.
I think that you don't need to include this in the Readme. I took a look another charts like Redis and we are not including this information. So, please remove it. Thanks.

2021-09-22 10:26 UTC, alvneiayu commented on bitnami/postgresql/README.md
> +| `readReplicas.extraVolumes`                   | Extra volumes to add to the pods (postgresql readReplicas), the value is evaluated as a template.
I think that you don't need to include this in the Readme. I took a look another charts like Redis and we are not including this information. So, please remove it. Thanks.

2021-09-22 10:26 UTC, alvneiayu commented on bitnami/postgresql/README.md
> +| `metrics.serviceMonitor.additionalLabels`     | Additional labels that can be used so ServiceMonitor will be discovered by Prometheus  , the value is evaluated as a template.
I think that you don't need to include this in the Readme. I took a look another charts like Redis and we are not including this information. So, please remove it. Thanks.

2021-09-22 10:26 UTC, alvneiayu commented on bitnami/zookeeper/README.md
> +| `extraVolumes`                       | Extra volumes  (value evaluated as a template)
I think that you don't need to include this in the Readme. I took a look another charts like Redis and we are not including this information. So, please remove it. Thanks.

2021-09-22 10:26 UTC, alvneiayu commented on bitnami/zookeeper/templates/statefulset.yaml
> +              value: {{ .Values.maxClientCnxns | quote }}
Remove the empty spaces at the end of the line, please

2021-09-22 10:26 UTC, alvneiayu commented on bitnami/zookeeper/values.yaml
> +  ## @param sidecars Extra containers to the pod
Please move the comments before the sidecar key definition (line 447-455 to 445). This must fix the linter Readme fail that you are having.

2021-09-22 18:13 UTC, bbaudelet commented
Thanks a lot for your reviewing, i'm sorry to have send only one PR for postgres and zookeeper it's my bad.
For the next PR i send one by chart.

2021-09-23 07:48 UTC, alvneiayu requested changes
Hi @bbaudelet 

Thanks again for your time including the changes. I requested more changes. Moreover, you are having linter problems. To fix it, you must bump the PostgreSQL Chart.yaml version.

Thanks a lot again

Álvaro

2021-09-23 07:48 UTC, alvneiayu commented on bitnami/zookeeper/values.yaml
> +sidecar: []
The key is sidecars, please change it from sidecar to sidecars.

2021-09-23 07:48 UTC, alvneiayu commented on bitnami/zookeeper/README.md
> +| `extraVolumes`                       | Extra volumes.
this point is not necessary. Please delete it. Please, leave the line as the original one (no changes, please).

2021-09-23 07:48 UTC, alvneiayu commented on bitnami/postgresql/README.md
> +| `metrics.serviceMonitor.additionalLabels`     | Additional labels that can be used so ServiceMonitor will be discovered by Prometheus.
this point is not necessary. Please delete it. Please, leave the line as the original one (no changes, please).

2021-09-23 07:48 UTC, alvneiayu commented on bitnami/postgresql/README.md
> +| `readReplicas.extraVolumes`                   | Extra volumes to add to the pods (postgresql readReplicas).
this point is not necessary. Please delete it. Please, leave the line as the original one (no changes, please).

2021-09-23 07:48 UTC, alvneiayu commented on bitnami/postgresql/README.md
> +| `primary.extraVolumes`                        | Extra volumes to add to the pods (postgresql primary).
this point is not necessary. Please delete it. Please, leave the line as the original one (no changes, please).

2021-09-23 07:48 UTC, alvneiayu commented on bitnami/zookeeper/values.yaml
> +
Remove one new line. This is a cosmetic change.

2021-09-24 11:43 UTC, alvneiayu approved these changes
LGTM

2021-09-24 11:44 UTC, merged