[bitnami/airflow] Support current cert-manager annotations
bitnami/charts pull request #7582
Opened 2021-09-22 13:48 UTC by pablogalegoc

**Description of the change**

We are using the kubernetes.io/tls-acme: "true" annotation to trigger the creation of Certificate resources in our charts.
This annotation comes from kube-lego, which is deprecated. We should instead let the user add the [currently supported annotations](https://cert-manager.io/docs/usage/ingress/#supported-annotations).

**Benefits**

Use of updated cert-manager annotations.

**Possible drawbacks**

We are changing the parameter type from boolean to map. To avoid breaking compatibility a helper is used to decide whether to use the deprecated annotation or the new user-supplied ones.

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-09-22 14:11 UTC, carrodher reviewed
Minor suggestion. I think this is a good solution in order to make the change backward compatible. As discussed, adding it to the common can be the proper solution to reuse the code, I'm sure we can find a "category" to add this template or just create a miscellany one

2021-09-22 14:11 UTC, carrodher commented on bitnami/airflow/templates/_helpers.tpl
> +{{- end -}}
```suggestion
{{- if typeIs "bool" .Values.ingress.certManager }}
    {{- true -}}
{{- end -}}
{{- end -}}
```

2021-09-22 16:26 UTC, pablogalegoc commented
Per @juan131 suggestion I'm going to explore removing the parameter and relying on the default `ingress.annotations` for this. Pros: We don't add new logic to handle backwards compatibility, we treat the `cert-manager` annotations as any other ingress annotation.

2021-09-23 09:34 UTC, pablogalegoc commented
@carrodher done! If you think this is also a valid approach I'll just use this same PR to update the other instances of `ingress.certManager`

2021-09-23 10:02 UTC, carrodher commented
For me it's fine! Just a minor comment, I am not sure if the README was generated by using the `readme-generator-tool` since it seems the table is not properly aligned (in terms of markdown, in the UI it looks fine).

Using the automated tool it should be aligned and you can see if the metadata in the _values.yaml_ was properly set

2021-09-23 10:10 UTC, pablogalegoc commented
Yep! It was modified with `readme-generator`. I think it's the UI in Github's review section that is messing something, in [raw format](https://raw.githubusercontent.com/bitnami/charts/003c086225de52bb46c2b53eb05cb6c9cb585757/bitnami/airflow/README.md) you can see it is aligned

2021-09-24 08:40 UTC, pablogalegoc commented
@carrodher this is a huge PR but basically is just:
- Deprecate `ingress.certManager` by commenting it
- Add a reference to the cert-manager annotations in the `ingress.annotations` documentation
- Add a mention to cert-manager in the `ingress.annotations` metadata so it appears in the README

2021-09-24 13:25 UTC, juan131 requested changes
I'm okay with the changes... That said, these 3 guides from Chart docs should be also updated @pablogalegoc 

- https://github.com/bitnami/charts-docs/blob/main/charts/cert-manager/_secure_ingress_resources.md.erb
- https://github.com/bitnami/charts-docs/blob/main/common/_enable_tls_ingress.md.erb
- https://github.com/bitnami/charts-docs/blob/main/charts/kubeapps/_expose_service.md.erb

I'll block this PR until there's another PR updating the chart docs.

---

Also, I remember from a private conversation that you were planning to create a "named template" to manage an existing condition in the ingress rule related to this `ingress.certManager`  parameter.. This was supposed to be done in the `_helpers.tpl` for Ghost, Kubeapps, Odoo, RabbitMQ and Redmine. Is this happening in other  PR?

2021-09-24 13:34 UTC, pablogalegoc commented
Thanks @juan131! Yes, this is just the first batch of the easier ones. On the JIRA issue I'm keeping track of the progress. I'll open another PR similar to this for the remaining ones and another for Ghost, Kubeapps, Odoo, RabbitMQ and Redmine. This PR is already huge, I didn't want to make it worse 😅

2021-09-29 11:29 UTC, pablogalegoc commented
The `readme-generator` CI check is failing for unrelated reasons, addressed at https://github.com/bitnami/charts/pull/7649

2021-10-01 06:09 UTC, juan131 approved these changes
LGTM

2021-10-01 06:55 UTC, carrodher approved these changes
LGTM

2021-10-01 08:01 UTC, merged

2021-10-04 13:45 UTC, AntonOfTheWoods commented
It looks like I am not getting a certificate request after the update. Should the following be generating a `certificaterequest`? 

```
helm get values harbor -n harbor --all 
...
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  apiVersion: ""
  controller: default
  enabled: true
  hosts:
    core: registry.my.doma.in
    notary: notary.harbor.domain
  pathType: ImplementationSpecific
...
```

If not, can someone point me to some docs that might help out (the `readme` is not explicit enough for me unfortunately)? `cert-manager.io/cluster-issuer: letsencrypt-prod` seems to work in other charts' ingress so I'm a little unclear as to the issue here. Thanks.