[bitnami/opencart] Chart standarized
bitnami/charts pull request #7588
Opened 2021-09-22 16:03 UTC by migruiz4

**Description of the change**

This PR standardizes the bitnami/opencart chart to be in line with the rest of the catalog.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-09-23 10:10 UTC, alvneiayu approved these changes
LGTM

2021-10-05 10:05 UTC, miguelaeh requested changes
Re-check the metadata, modifiers are not needed except for special cases

2021-10-05 10:05 UTC, miguelaeh commented on bitnami/opencart/values.yaml
> +  ## @param persistence.accessModes [array] PVC Access Mode for OpenCart volume
Remove the `[array]` modifier, now arrays are properly parsed

2021-10-05 10:05 UTC, miguelaeh commented on bitnami/opencart/values.yaml
> +## @param resources.limits [object] The resources limits for the container
```suggestion
## @param resources.limits The resources limits for the container
```

2022-01-05 08:14 UTC, carrodher commented on bitnami/opencart/values.yaml
> +  sessionAffinityConfig: {}
```suggestion
  ##     timeoutSeconds: 300
  ##
  sessionAffinityConfig: {}
```

2022-01-05 08:14 UTC, carrodher approved these changes
LGTM

2022-01-05 14:08 UTC, merged