feat: add etcd nodeselctor & toleration on disasterRecovery
bitnami/charts pull request #7984
Opened 2021-10-31 15:12 UTC by cyril-corbon

**Description of the change**
add nodeSelector & tolerations on disasterRecovery cronJob

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-02 09:27 UTC, miguelaeh requested changes
Thank you very much for the PR!
Please take a look at my comments

2021-11-02 09:27 UTC, miguelaeh commented on bitnami/etcd/Chart.yaml
> +appVersion: 3.6.1
Please don't change the `appVersion`

2021-11-02 09:27 UTC, miguelaeh commented on bitnami/etcd/README.md
> +| `disasterRecovery.cronjob.tolerations`                           | Tolerations for cronjob assignment                                                            | `[]`            |
Please use the [Readme Generator For Helm](https://github.com/bitnami-labs/readme-generator-for-helm) to generate this in the proper format

2021-11-02 09:27 UTC, miguelaeh commented on bitnami/etcd/values.yaml
> +    ## @param disasterRecovery.cronjob.tolerations [array] Tolerations for pod assignment
```suggestion
    ## @param disasterRecovery.cronjob.tolerations Tolerations for pod assignment
```

2021-11-02 09:27 UTC, miguelaeh commented on bitnami/etcd/values.yaml
> +    ## @param disasterRecovery.cronjob.nodeSelector [object] Node labels for pod assignment
```suggestion
    ## @param disasterRecovery.cronjob.nodeSelector Node labels for pod assignment
```

2021-11-02 22:47 UTC, cyril-corbon commented
review applied & lint done

2021-11-04 08:55 UTC, miguelaeh approved these changes
LGTM!

2021-11-04 08:55 UTC, merged