[bitnami/elasticsearch] add priority class name for all es sts
bitnami/charts pull request #7985
Opened 2021-10-31 16:33 UTC by cyril-corbon

**Description of the change**
add priority class name on all sts 

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #7702

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-02 08:53 UTC, alemorcuq requested changes
Thanks for the PR! I've left some comments, please check them.

2021-11-02 08:53 UTC, alemorcuq commented on bitnami/elasticsearch/Chart.yaml
> +appVersion: 7.16.1
This is the Elasticsearch version in the container. No need to change it.

2021-11-02 08:53 UTC, alemorcuq commented on bitnami/elasticsearch/Chart.yaml
> +version: 17.2.8
`17.2.0` would be the next minor.

```suggestion
version: 17.2.0
```

2021-11-02 08:53 UTC, alemorcuq commented on bitnami/elasticsearch/templates/coordinating-statefulset.yaml
> +      priorityClassName: {{ .Values.coordinating.priorityClassName | quote }}
This should be wrapped in an if statement to check if `priorityClassName` is set. Like this: 

```suggestion
      {{- if .Values.coordinating.priorityClassName }}
      priorityClassName: {{ .Values.coordinating.priorityClassName | quote }}
      {{- end }}
```

The same applies to the other statefulsets.

2021-11-02 08:53 UTC, alemorcuq commented on bitnami/elasticsearch/values.yaml
> +  ## @param master.priorityClassName Priority Class Name
I would be more specific in the description, like:

```suggestion
  ## @param master.priorityClassName Master pods Priority Class Name
```

The same applies to the rest. Also, please double check the text is the same as in the README file.

2021-11-02 22:23 UTC, cyril-corbon commented
review applied :smile:

2021-11-03 07:56 UTC, alemorcuq approved these changes
Great, thanks!

2021-11-03 08:23 UTC, merged