[bitnami/kubernetes-event-exporter] remove rbac-leader-election RoleBinding n…
bitnami/charts pull request #8019
Opened 2021-11-04 10:51 UTC by jvizier

…amespace monitoring

**Description of the change** 

Remove monitoring namespace from rbac-leader-election.yaml when in custom namespace

**Benefits**

Allow successfully acquired lease.

**Possible drawbacks**

None

**Applicable issues**

**Additional information**

**Checklist** 

- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-05 09:52 UTC, alemorcuq requested changes
Thanks for the PR! Could you please increase the chart version?

2021-11-06 09:59 UTC, jvizier commented
Hi, Done, i update to Chart to 1.2.2 , Best regards

2021-11-08 08:33 UTC, alemorcuq approved these changes

2021-11-08 08:33 UTC, merged

2021-11-08 08:33 UTC, alemorcuq commented
Thanks!