bitnami/dataplatform-bp1: added annotation based discovery feature in wavefront to the chart
bitnami/charts pull request #8061
Opened 2021-11-08 17:31 UTC by sarvani95

**Description of the change**
Updated  wavefront to use auto discovery feature to the Dataplatform chart

**Benefits**
Wavefront will be able to fetch metrics from dataplatform applications/pod automatically using annotation based discovery.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-09 06:58 UTC, gkulkarni32 requested changes
All the comments for bp2 PR are applicable here too (except the app version which is the exporter app version in case of bp1).
https://github.com/bitnami/charts/pull/8064#pullrequestreview-800892104

2021-11-09 06:58 UTC, gkulkarni32 commented on bitnami/dataplatform-bp1/Chart.yaml
> +appVersion: 1.0.0
update this to the dataplatform-exporter version

2021-11-09 08:32 UTC, rafariossaa commented
Hi,
  Thanks for the PR.
  Could you take a look to the linter errors ?

2021-11-09 11:11 UTC, sarvani95 commented
Hi @rafariossaa,

Could you please tell me the linter errors you found, I am not able to run the workflow for Lint and test charts, it says First-time contributors need a maintainer to approve running workflows.

2021-11-10 09:03 UTC, rafariossaa requested changes

2021-11-10 09:03 UTC, rafariossaa commented on bitnami/dataplatform-bp1/values.yaml
> +      #config:
The linter complains about a missing space here:
```suggestion
      # config:
```

2021-11-10 09:04 UTC, rafariossaa commented
Hi,
  This is the log from the linter:
```Linting chart 'dataplatform-bp1 => (version: "9.0.0", path: "bitnami/dataplatform-bp1")'
Checking chart 'dataplatform-bp1 => (version: "9.0.0", path: "bitnami/dataplatform-bp1")' for a version bump...
>>> git cat-file -e origin/master:bitnami/dataplatform-bp1/Chart.yaml
>>> git show origin/master:bitnami/dataplatform-bp1/Chart.yaml
Old chart version: 8.0.2
New chart version: 9.0.0
Chart version ok.
>>> yamale --schema /opt/hostedtoolcache/ct/v3.4.0/x86_64/etc/chart_schema.yaml bitnami/dataplatform-bp1/Chart.yaml
Validating /home/runner/work/charts/charts/bitnami/dataplatform-bp1/Chart.yaml...
Validation success! 👍
>>> yamllint --config-file /opt/hostedtoolcache/ct/v3.4.0/x86_64/etc/lintconf.yaml bitnami/dataplatform-bp1/Chart.yaml
>>> yamllint --config-file /opt/hostedtoolcache/ct/v3.4.0/x86_64/etc/lintconf.yaml bitnami/dataplatform-bp1/values.yaml
Error: [comments] missing starting space in comment
Error: Error linting charts: Error processing charts
```
It is just a missing space in `values.yaml`

2021-11-12 08:07 UTC, rafariossaa commented
Thanks for fixing it.
I am merging the changes.

2021-11-12 08:08 UTC, merged