[bitnami/postgresql] Improvement for network policy
bitnami/charts pull request #8119
Opened 2021-11-12 15:36 UTC by rafariossaa

**Description of the change**

Improvement for network policy

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

DO NOT MERGE.
This PR is to get the changes reviewed.

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-16 16:16 UTC, pablogalegoc reviewed
Thanks @rafariossaa!

I've left some comments below. Also, we will need to update:
- [Network policy](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#networkpolicy) section of the README
- The `NOTES.txt`, since it uses some of the previous parameters ([example](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/NOTES.txt#L56))

2021-11-16 16:16 UTC, pablogalegoc commented on bitnami/postgresql/values.yaml
> +  ## @param networkPolicy.metrics.enabled Enable network policy for metrics (prometheus)
Missing `networkPolicy.enabled`

2021-11-16 16:16 UTC, pablogalegoc commented on bitnami/postgresql/values.yaml
> +  ## @param networkPolicy.ingressRules.primaryAccessOnlyFrom.namespaceSelector [object] Namespace selector label that is allowed to access the primary node. This label will be used to identified the
According to Miña, in these cases where we declare empty objects the `[object]` modifier is redundant, so we should remove it ([source](https://github.com/bitnami/charts/pull/8116#discussion_r749182402))

2021-11-16 16:16 UTC, pablogalegoc commented on bitnami/postgresql/values.yaml
> +    ## Allow access to the primary node only from the indicated:
Nitpick:
```suggestion
    ## Allow access to the primary node only from the indicated:
    ##
```
Check other cases like this below

2021-11-17 14:03 UTC, pablogalegoc approved these changes

2021-11-17 14:04 UTC, pablogalegoc requested changes
Approved but these changes have to be integrated in the next major, so I'm blocking the merge by "requesting changes"

2022-02-01 11:32 UTC, juan131 commented
These changes have been implemented at https://github.com/bitnami/charts/pull/8119

2022-02-01 11:32 UTC, closed without merging