[bitnami/node] Adds service account
bitnami/charts pull request #8216
Opened 2021-11-23 09:09 UTC by rafariossaa

**Description of the change**

Adds service account to the deployment

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #8213

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-23 09:15 UTC, migruiz4 requested changes
Please check my suggestions.

2021-11-23 09:15 UTC, migruiz4 commented on bitnami/node/values.yaml
> +  autoMount: false
Please use `automountServiceAccountToken` not `autoMount` as most of our charts do.

2021-11-23 09:15 UTC, migruiz4 commented on bitnami/node/templates/deployment.yaml
> +      automountServiceAccountToken: {{ .Values.serviceAccount.autoMount }}
Please add `automountServiceAccountToken` in the serviceAccount.yaml, not at pod level.

Adding granular `automountServiceAccountToken` at pod-level would be a different feature we do not support yet.

2021-11-24 07:51 UTC, juan131 approved these changes
LGTM

2021-11-24 07:54 UTC, migruiz4 approved these changes
Thank you for applying the suggested changes!

2021-11-24 08:57 UTC, merged