[bitnami/thanos] Fix autogenerated TLS key values
bitnami/charts pull request #8230
Opened 2021-11-24 10:23 UTC by quadeare

**Description of the change**

This change just fix TLS autogenerated key values on secret files. For now, when we use autogenerated TLS, some pods won't start because TLS key doesn't exist.

**Benefits**

Autogenerated TLS is able to work now.

**Possible drawbacks**

Maybe a new PR is mandatory to fix CA issue : https://github.com/bitnami/charts/issues/8172

**Checklist** 

- [ X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ X] Variables are documented in the README.md
- [ X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-25 08:40 UTC, Mauraza reviewed
Hi  @quadeare,

Thanks for the PR.
The rest of the charts are using `tls.crt`, `tls.key` and `ca.crt`,  could you do the change using these instead of `tls-cert`, `tls-key`, and `ca-cert`?

2021-11-29 14:09 UTC, quadeare commented
Hi @Mauraza,

I just push my latest modifications with `tls.crt`, `tls.key` and `ca.crt` keys.
It seems to be good on my side, can you take a look ?

Than you so much ;)

2021-11-30 10:15 UTC, miguelaeh requested changes
Hi guys,
this change is not so trivial as it seems. This will imply a backward incompatibility for people using `existingSecrets`.
Please reconsider the version bump.
@quadeare  could you please elaborate on why this change is needed?

2021-11-30 12:21 UTC, quadeare commented
Hi @miguelaeh,

Autogenerated TLS isn't working well because `tls-cert`, `tls-key`, and `ca-cert` or not found.
Naively, I thought that by changing all the keys it would work properly.

Since `autogenerated` does not work i use `existingSecrets` and it works well.

2021-12-01 11:02 UTC, miguelaeh commented
Hi @quadeare ,
It seems I was wrong, it is currently implemented in two different ways. It is using `tls-` in the case of `existingSecrets` and `tls.` in the case of autogenerated secret.
But in both cases, the config map is created by the chart, so I think changing it will be automatically upgraded.
Honestly, I think this must be changed to use a single approach in both cases, but I would like to ensure this won't break the `helm upgrade`.

2021-12-23 01:23 UTC, closed without merging