[bitnami/mongodb] Add medium option for non-persisted.
bitnami/charts pull request #8238
Opened 2021-11-25 07:40 UTC by MikaelElkiaer

**Description of the change**
Adds `persistence.medium` and `hidden.persistence.medium` options.

**Benefits**
With the added medium option, it is now possible to set medium to `Memory`, as opposed to defaulting to local fs.

**Possible drawbacks**
None come to mind, as this is completely optional and will keep the default if not set.

**Applicable issues**

  - closes #7382 

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-25 10:18 UTC, miguelaeh requested changes
Thank you for the PR! Please check the comments

2021-11-25 10:18 UTC, miguelaeh commented on bitnami/mongodb/Chart.yaml
> +version: 10.29.5
Adding new features should be a minor bump
```suggestion
version: 10.30.0
```

2021-11-25 10:18 UTC, miguelaeh commented on bitnami/mongodb/templates/hidden/statefulset.yaml
> +          }
```suggestion
          emptyDir:
            medium: {{ .Values.hidden.persistence.medium | quote }}
```

2021-11-25 10:18 UTC, miguelaeh commented on bitnami/mongodb/templates/replicaset/statefulset.yaml
> +          }
```suggestion
          emptyDir:
            medium: {{ .Values.persistence.medium | quote }}
```

2021-11-25 10:18 UTC, miguelaeh commented on bitnami/mongodb/templates/standalone/dep-sts.yaml
> +          }
```suggestion
          emptyDir:
            medium: {{ .Values.persistence.medium | quote }}
```

2021-11-25 11:10 UTC, MikaelElkiaer commented
> Thank you for the PR! Please check the comments

Thanks for the comments.
Obviously a minor, and not a patch, d'oh.

In regards to the yaml style, I actually adopted it from the redis chart.

2021-11-26 09:21 UTC, miguelaeh approved these changes
LGTM!

2021-11-26 09:24 UTC, merged