[bitnami/mediawiki] Fix Mediawiki host when using ingress
bitnami/charts pull request #8239
Opened 2021-11-25 08:48 UTC by migruiz4

**Description of the change**

Modifies the helper `mediawiki.host` adding support for ingress, similar to how it is done for other assets.

**Possible drawbacks**

None known.

**Applicable issues**

  - fixes #8182

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-25 10:24 UTC, miguelaeh requested changes
Thanks for the PR!
Please take a look to the suggestion

2021-11-25 10:24 UTC, miguelaeh commented on bitnami/mediawiki/templates/_helpers.tpl
> +{{- end -}}
```suggestion
{{- $host := index .Values (printf "%sHost" .Chart.Name) | default "" -}}
{{- if .Values.ingress.enabled }}
{{- $host := .Values.ingress.hostname | default "" -}}
{{- end -}}
{{- default (include "mediawiki.serviceIP" .) $host -}}
{{- end -}}
```

2021-11-25 13:14 UTC, migruiz4 commented
Suggestion applied

2021-11-26 09:22 UTC, miguelaeh approved these changes
LGTM!

2021-11-30 08:46 UTC, merged