[bitnami/ghost] Fix host when using ingress with external TLS termination
bitnami/charts pull request #8246
Opened 2021-11-26 11:17 UTC by mwoelk

**Description of the change**

Gives `ghostHost` precedence over `ingress.hostname` when defining the `ghost.host` variable helper.

**Benefits**

This way, the host can be set independently / override the hostname from ingress. 
This is necessary when using external TLS termination. In this case, we need to provide a `https://`-prefix for the host which is not possible through an ingress hostname.

**Possible drawbacks**

none

**Applicable issues**

none

**Additional information**

none

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-26 11:19 UTC, mwoelk commented
Bumped the minor version instead of patch version because the precedence change might require a check to see if `ghostHost` is set correctly if both `ghostHost` and `ingress.hostname` are provided.

2021-11-26 12:04 UTC, mwoelk commented
Problem is that this messes with the live/readiness check. As they are performed via http but Ghost redirects to https.
Maybe it's a solve to change live/readiness to a tcp check on the http port?

2021-11-29 10:51 UTC, miguelaeh requested changes
Thank you for the PR!

2021-11-29 10:51 UTC, miguelaeh commented on bitnami/ghost/Chart.yaml
> +version: 15.2.1
```suggestion
version: 15.1.3
```

2021-11-30 10:08 UTC, miguelaeh requested changes
Hi, 
It seems you need to bump the version again after rebasing master.

2021-12-21 01:23 UTC, closed without merging