Add security context setup to the mariadb metrics containers
bitnami/charts pull request #8247
Opened 2021-11-26 11:28 UTC by madrisan

Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>

**Description of the change**

This patch add the security context setup to the MariaDB metrics containers.

**Benefits**

This patch allows a deployment to restrict Kubernetes environments where Polaris deny the deployment of containers without a strict containerSecurityContext.

**Possible drawbacks**

There're should be no drawbacks, because for compatibility this feature is disabled by default.

**Additional information**

Successfully tested on Kubernetes with the following configuration:
```
metrics:
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  enabled: true
```

**Checklist** 

- [ x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-11-29 10:55 UTC, javsalgar commented
Hi! Thank you so much for the PR! Could you bump the minor version of the chart?

2021-11-30 17:33 UTC, madrisan commented
Done @javsalgar

2021-12-01 09:27 UTC, migruiz4 requested changes
Hi @madrisan,

Since this PR adds a new value it needs a minor version bump (10.1.0) and the new value to be added in the README.md.

2021-12-01 09:27 UTC, migruiz4 commented on bitnami/mariadb/Chart.yaml
> +version: 10.0.3
Please bump a minor version (`10.1.0`)

2021-12-01 16:05 UTC, migruiz4 approved these changes
Looks good to me! Thank you for applying the suggested changes.

2021-12-01 16:05 UTC, merged