[bitnami/keycloak] Disable http(s) service mapping
bitnami/charts pull request #8306
Opened 2021-12-03 21:10 UTC by wassy92x

**Description of the change**

Added possibility to disable http(s) mapping by setting service.port / service.httpsPort to 0.
The default value 80 and 443 will remain.

**Benefits**

This change is necessary if you like to use the exposed service with nginx-ingress-controller.
Nginx-Ingress will only work, if just one port is set inside the service.

**Possible drawbacks**

None

**Applicable issues**

None

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-12-09 09:02 UTC, javsalgar commented
Hi,

Could you let us know the issue that shows that nginx ingress controller will only work with one port? This sounds like a bug in nginx ingress controller itself.

2021-12-09 20:00 UTC, wassy92x commented
I found out that it is no issue with nginx ingress controller.
It's an issue of octant (an web-interface for kubernetes clusters).
Otant shows an error, that the port of the service is invalid.
It seems like the issue is solved in the newest version of octant, so you can decide if you like to merge my pull request or not.

2021-12-13 13:24 UTC, miguelaeh requested changes
thank you for the PR!
I don't see the real sense of the PR, but l added some comments.

>It seems like the issue is solved in the newest version of octant, so you can decide if you like to merge my pull request or not.

If it was an issue with octant I think we can just close this since there are no issues with that logic.

2021-12-13 13:24 UTC, miguelaeh commented on bitnami/keycloak/values.yaml
> +  ## 0 will disable http-mapping
If you want this to appear in the README it has to be added in the line above. Same for the next one

2021-12-13 13:24 UTC, miguelaeh commented on bitnami/keycloak/Chart.yaml
> +version: 5.3.0
```suggestion
version: 5.2.4
```

2021-12-13 13:24 UTC, miguelaeh commented on bitnami/keycloak/README.md
> +| `service.httpsPort`                | HTTPS Port. 0 will disable https mapping.                                                                                        | `443`                    |
Please, do not edit this manually, use https://github.com/bitnami-labs/readme-generator-for-helm

2021-12-13 22:48 UTC, closed without merging