[bitnami/thanos] Fix Thanos Receiver service port name
bitnami/charts pull request #8351
Opened 2021-12-09 10:23 UTC by v1ctorrhs

**Description of the change**

Currently the Thanos receiver Ingress points to a service port `remote-write` and the actual port name is called `remote`. 
Of course this introduces issues and traffic is not received corretly.

**Benefits**
Tha thanos receiver getting the traffic destined to it.

**Possible drawbacks**

None
**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-12-09 16:45 UTC, javsalgar approved these changes

2021-12-09 16:46 UTC, javsalgar requested changes
Hi,

This seems to be incorrect, right? According to the description, the port name should be remote and it is being changed to remote-write

2021-12-10 07:53 UTC, v1ctorrhs commented
> Hi,
> 
> This seems to be incorrect, right? According to the description, the port name should be remote and it is being changed to remote-write

The ingress is looking for a service port name `remote-write` and currently it is called `remote`.

```         
- path: /api/v1/receive
   {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
   pathType: {{ .Values.receive.ingress.pathType }}
   {{- end }}
   backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s"  (include "common.names.fullname" .) "receive") "servicePort" "remote-write" "context" $)  | nindent 14 }}
```

Therefore this changes the service port name from `remote` to `remote-write` so the ingress can match accordingly. 
I'm not sure what change you are requesting

2021-12-13 08:11 UTC, v1ctorrhs commented
@javsalgar  Any update here? Thanks

2021-12-13 15:50 UTC, marcosbc commented
Hi @v1ctorrhs, wouldn't it make more sense to fix the Ingress configuration? Since it is working for LoadBalancer and other configurations - See [ingress.yaml#L32](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/ingress.yaml#L32)

2021-12-14 16:23 UTC, v1ctorrhs commented
@marcosbc I thought i'd update the service since that name is already used in the [statefulset#L180](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/statefulset.yaml#L160) so it makes more sense to keep it consistent. 

just like the example you gave with [ingress.yaml#L38](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/ingress.yaml#L38) - the containerPort name is also `http` in [statefulset.yaml#L157](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/statefulset.yaml#L157) as well as in the service [service.yaml#L37](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/service.yaml#L37)

Can we please merge this, i'm trying to use it in production. I'm not trying to start a discussion, it's your chart - whatever you want to call it i'm fine with that as long as it works - which it currently doesn't.

2021-12-15 08:16 UTC, v1ctorrhs commented
It seems like this got fixed in b8a5eb44a1b6abaa4440d5dc5dc0e923358c028e

2021-12-15 08:16 UTC, closed without merging