[bitnami/grafana] add extraEnvVars for image-renderer
bitnami/charts pull request #8430
Opened 2021-12-15 18:04 UTC by ioachim-hub

Signed-off-by: Ioachim Lihor <ioachim.lihor@radcom.com>

**Description of the change**
In order to use image-renderer configuration environment variables it's need to use extraEnvVars to chart [Image Renderer Configuration](https://grafana.com/docs/grafana/latest/image-rendering/#configuration) 
For this I added extraEnvVars support

**Benefits**
Support for extraEnvVars for Grafana Image Renderer

**Possible drawbacks**
No possible knows limitations

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-12-16 09:45 UTC, miguelaeh requested changes
Please fix the version and execute the [readme-genrator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm) to update the README.md

2021-12-16 09:45 UTC, miguelaeh commented on bitnami/grafana/Chart.yaml
> +version: 7.2.13
```suggestion
version: 7.3.0
```

2021-12-16 13:18 UTC, ioachim-hub commented on bitnami/grafana/Chart.yaml
> +version: 7.2.13
@miguelaeh, done

2021-12-17 08:09 UTC, ioachim-hub commented
@miguelaeh 

Do you think I should change the version to 7.4.0 now (Already exists 7.3.0 #8431)

2021-12-20 11:28 UTC, javsalgar approved these changes
LGTM! Thanks!

2021-12-20 11:29 UTC, merged