[bitnami/wordpress] Add startup probe on wordpress helm chart
bitnami/charts pull request #8520
Opened 2021-12-29 08:20 UTC by Aju100

**Description of the change**
Add startup probe config 
 
**Benefits**
- startup probes help to know when a container application has started and it will be good for deployments on wp helm chart.

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2021-12-29 09:32 UTC, javsalgar commented
Hi,

Thank you so much for the PR! However, startupProbes were still not available in all k8s distros, so could you set it disabled by default to avoid compatibility issues?

2021-12-29 17:20 UTC, Aju100 commented
Hi @javsalgar I have disabled it.

2021-12-31 09:55 UTC, javsalgar requested changes

2021-12-31 09:55 UTC, javsalgar commented on bitnami/wordpress/values.yaml
> +customStartupProbe: {}
You are missing the metadata for `customStartupProbe`, could you fix it? (check the example of customReadinessProbe.

2021-12-31 14:25 UTC, javsalgar approved these changes

2021-12-31 16:29 UTC, merged