bitnami/grafana-operator fix default value for accessModes
bitnami/charts pull request #8554
Opened 2022-01-03 12:36 UTC by StianHaugland1

**Description of the change**
After recent [changes](https://github.com/bitnami/charts/commit/d87dec202858e218f08470a8a28d5397426b6a6c) to the grafana-operator chart Values.grafana.persistence.accessModes is expected to be a list:
https://github.com/bitnami/charts/blob/master/bitnami/grafana-operator/templates/grafana.yaml#L33

Change default grafana.persistence.accessModes to be a list.

**Benefits**

Fixes: Error: UPGRADE FAILED: template: grafana-operator/templates/grafana.yaml:34:23: executing "grafana-operator/templates/grafana.yaml" at <.Values.grafana.persistence.accessModes>: range can't iterate over ReadWriteOnce

**Possible drawbacks**

None

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2022-01-03 22:19 UTC, tomberget approved these changes
LGTM

2022-01-04 13:09 UTC, Mauraza requested changes

2022-01-04 13:09 UTC, Mauraza commented on bitnami/grafana-operator/Chart.yaml
> +version: 2.0.5
Could you change this to 2.1.0?
```suggestion
version: 2.1.0
```

2022-01-04 15:33 UTC, Mauraza approved these changes
Hi @StianHaugland1,

Thanks for the PR!! LGTM!

2022-01-04 15:33 UTC, merged