[bitnami/solr] Chart standardized
bitnami/charts pull request #8640
Opened 2022-01-12 11:48 UTC by juan131

Signed-off-by: juan131 <juanariza@vmware.com>

**Description of the change**

This PR standardizes the `bitnami/solr` chart to be in line with the rest of the catalog.

**Benefits**

Standardization.

**Possible drawbacks**

Changes the values structure forcing a major bump, check the README.md for more information.

**Applicable issues**

N/A

**Additional information**

Blocked by https://github.com/bitnami/charts/pull/8623 (major bump in dep)

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2022-01-14 12:33 UTC, migruiz4 requested changes
Please check my comments below.

In addition, please add the following missing value:
- `kubeVersion`

2022-01-14 12:33 UTC, migruiz4 commented on bitnami/solr/templates/statefulset.yaml
> -          {{- end }}
Why removing `lifecycleHooks`?

2022-01-18 08:22 UTC, juan131 commented on bitnami/solr/templates/NOTES.txt
> +    echo "Solr URL: ${NODE_IP}[${NODE_PORT}]"
The rest of examples were using brackets too. But I don't have a strong opinion on this

2022-01-18 11:47 UTC, juan131 commented on bitnami/solr/templates/statefulset.yaml
> -          {{- end }}
My mistake

2022-01-18 12:29 UTC, migruiz4 approved these changes
LGTM!

2022-01-18 17:42 UTC, merged