[bitnami/tomcat] Fix extraVolumes parameter
bitnami/charts pull request #8684
Opened 2022-01-17 08:25 UTC by migruiz4

**Description of the change**

Removes duplicated `extraVolumes` in Tomcat's pod.

**Benefits**

Fixes bug.

**Possible drawbacks**

None known.

**Applicable issues**

  - fixes #8681

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-01-17 11:11 UTC, carrodher approved these changes
LGTM

2022-01-17 14:08 UTC, juan131 requested changes
`.Values.extraVolumeMounts` is affected by a wrong indentation too. @migruiz4 please also fix that.

2022-01-17 18:31 UTC, yardenshoham approved these changes

2022-01-18 07:33 UTC, migruiz4 commented
@juan131 I applied the change to the `extraVolumeMounts` too, thanks.

2022-01-18 07:49 UTC, carrodher approved these changes

2022-01-18 10:56 UTC, patrickhoefer approved these changes

2022-01-19 08:07 UTC, merged