[bitnami/spring-cloud-dataflow] enable deployer secretRefs
bitnami/charts pull request #8842
Opened 2022-01-31 11:41 UTC by sergiupantiru

**Description of the change**

Added `deployer.secretRefs` to spring-cloud-dataflow chart (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_secret_references)

**Benefits**

Having the possibility to add secrets to the deployed apps.

**Possible drawbacks**

None (that I can think of)

**Applicable issues**

  - fixes #8837

**Additional information**

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-01-31 11:49 UTC, sergiupantiru commented
While running readme-generator -v values.yaml -r README.md I see more changes to the README.MD file. Is this to be expected?

2022-02-01 07:34 UTC, juan131 requested changes
Thanks so much for this great PR! We really appreciate it

Could you take a look to my comments when you have a chance?

> While running readme-generator -v values.yaml -r README.md I see more changes to the README.MD file. Is this to be expected?

Yes, that happens when other contributors modified the **values.yaml** without running the tool. Don't worry about it.

2022-02-01 07:34 UTC, juan131 commented on bitnami/spring-cloud-dataflow/Chart.yaml
> +version: 5.0.6
Please bump the minor version instead since you're including a new parameter:
```suggestion
version: 5.1.0
```

2022-02-01 11:56 UTC, juan131 approved these changes
LGTM

2022-02-01 11:56 UTC, merged