[bitnami/airflow] Chart standardization
bitnami/charts pull request #8909
Opened 2022-02-04 16:46 UTC by juan131

Signed-off-by: juan131 <juanariza@vmware.com>

**Description of the change**

This PR standardizes the `bitnami/airflow` chart to be in line with the rest of the catalog.

**Benefits**

Standardization.

**Possible drawbacks**

Changes the values structure forcing a major bump, check the README.md for more information.

**Applicable issues**

N/A

**Additional information**

Triggered after https://github.com/bitnami/charts/pull/8827 (major bump in PostgreSQL)

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

2022-02-08 09:00 UTC, migruiz4 requested changes
Hi, please check my comments below.

In addition, I have noticed the value `*.lifecycleHooks` is missing.

2022-02-08 09:25 UTC, juan131 commented on bitnami/airflow/templates/_helpers.tpl
> +
Yes, it's intentional. The default secret key changed in the latest PostgreSQL major, but Redis isn't affected.

2022-02-08 09:27 UTC, juan131 commented on bitnami/airflow/templates/metrics/deployment.yaml
> -            {{- end }}
recovered

2022-02-08 09:27 UTC, juan131 commented on bitnami/airflow/templates/config/secret.yaml
> +  airflow-secret-key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "airflow-secret-key" "providedValues" (list "auth.secretKey") "length" 32 "
Right, it's documented in the Upgrading Notes

2022-02-08 09:27 UTC, juan131 commented on bitnami/airflow/templates/scheduler/deployment.yaml
> -              containerPort: {{ .Values.worker.port }}
I've been doing some tests and I found no process listening in that port.

2022-02-08 09:28 UTC, juan131 commented on bitnami/airflow/values.yaml
> +  path: /pulse
Copy-paste error

2022-02-08 09:28 UTC, juan131 commented on bitnami/airflow/values.yaml
> +    nginx.ingress.kubernetes.io/affinity: cookie
Copy-paste error

2022-02-08 11:39 UTC, migruiz4 commented on bitnami/airflow/templates/_helpers.tpl
> +
Understood, thanks

2022-02-08 11:40 UTC, migruiz4 approved these changes
LGTM!

2022-02-09 10:45 UTC, migruiz4 commented on bitnami/airflow/Chart.yaml
> +description: Apache Airflow is a platform to programmatically author, schedule and monitor workflows.
Updating the majors of Redis and Postresql that have been already standardized.

2022-02-09 10:46 UTC, migruiz4 commented on bitnami/airflow/Chart.yaml
> +description: Apache Airflow is a platform to programmatically author, schedule and monitor workflows.
Sorry, you meant the description, right?

2022-02-09 10:46 UTC, migruiz4 approved these changes
LGTM

2022-02-09 10:48 UTC, juan131 commented on bitnami/airflow/Chart.yaml
> +description: Apache Airflow is a platform to programmatically author, schedule and monitor workflows.
I didn't change that... It seems the description was changed in the commit below:
- https://github.com/bitnami/charts/commit/fd78a9b306a82ef0d30418b5b47db45c254cf07b
Let me rebase and update the PR

2022-02-09 10:59 UTC, alemorcuq submitted a review, later dismissed

2022-02-09 11:59 UTC, migruiz4 submitted a review, later dismissed
Changes to adopt `global.postgresql` approved

2022-02-09 14:42 UTC, merged