[bitnami/nginx] add strategy value for the deployment
bitnami/charts pull request #9067
Opened 2022-02-18 10:08 UTC by messiahUA

**Description of the change**

Add a value to set deployment strategy.

**Benefits**

I would be possible to change the deployment strategy for the deployment.

**Possible drawbacks**

None.

**Applicable issues**

  - fixes #9054

**Additional information**

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-02-18 10:11 UTC, messiahUA commented
not sure why version bump check fails:
"Error: Detected changes in charts without version bump in Chart.yaml."
I've bumped the version...

2022-02-21 07:12 UTC, juan131 requested changes
Thanks so much for your PR @messiahUA ! Please take a look to my comments when you have a chacne.

2022-02-21 07:12 UTC, juan131 commented on bitnami/nginx/README.md
> +| `strategy`                              | Strategy for the deployment                                                               | `{}`    |
Please rename this parameter to "updateStrategy". We're using this name on every chart regardless it's a deployment or a statefulset.

2022-02-21 07:12 UTC, juan131 commented on bitnami/nginx/values.yaml
> +strategy: {}
Please use this instead:
```suggestion
## @param updateStrategy.type NGINX deployment strategy type
## @param updateStrategy.rollingUpdate NGINX deployment rolling update configuration parameters
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
##
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}
```

2022-02-21 08:55 UTC, messiahUA commented
@juan131 done, but I still don't understand why it complains about the version bump

2022-02-22 07:20 UTC, juan131 approved these changes
LGTM

2022-02-22 07:38 UTC, juan131 commented
> but I still don't understand why it complains about the version bump

To be honest, me neither @messiahUA. Probably it's because you're creating the PR from the "master" branch of you fork instead of creating a branch in your fork but I'm not very sure about this. 

I'll proceed and merge your PR regardless that test

2022-02-22 07:38 UTC, merged