[bitnami/nginx] Add hostIPC option for NGINX Deployment
bitnami/charts pull request #9155
Opened 2022-02-22 07:38 UTC by hjames9

Signed-off-by: Hayden James <hayden.james@gmail.com>

This adds the "hostIPC" option to the Deployment used for the NGINX chart in order to enable/disable that feature.  This allows you to enable host IPC (inter-process communication) for the NGINX pods, instead of only forcing the user to use an IPC namespace.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-02-22 10:03 UTC, miguelaeh requested changes
thanks for the PR!

2022-02-22 10:03 UTC, miguelaeh commented on bitnami/nginx/Chart.yaml
> +version: 9.8.1
this should be a bump of the minor verion

2022-02-22 12:52 UTC, hjames9 commented
@miguelaeh We should be good now

2022-02-23 14:53 UTC, hjames9 commented
@miguelaeh Anything else needed here?

2022-02-24 09:35 UTC, miguelaeh requested changes
Note that the version is not properly updated: it should be `9.9.0`

2022-02-24 20:25 UTC, hjames9 commented
@miguelaeh Thanks, I've corrected the version

2022-02-25 14:48 UTC, hjames9 commented
@miguelaeh Is this mergeable now or does it need more changes?

2022-02-25 15:09 UTC, miguelaeh approved these changes
LGTM!
Thanks!

2022-02-25 15:09 UTC, merged