[bitnami/redis] Fix readiness script typo
bitnami/charts pull request #9280
Opened 2022-03-03 11:33 UTC by migruiz4

Signed-off-by: Miguel Ruiz <miruiz@vmware.com>

Same fix as applied here: #9279

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-03-04 09:32 UTC, miguelaeh requested changes

2022-03-04 09:32 UTC, miguelaeh commented on bitnami/redis/templates/health-configmap.yaml
> +    if [ "$?" -eq "124" ]; then
```suggestion
    if [[ "$?" -eq "124" ]]; then
```

2022-03-04 09:32 UTC, miguelaeh commented on bitnami/redis/templates/health-configmap.yaml
> +    if [ "$?" -eq "124" ]; then
```suggestion
    if [[ "$?" -eq "124" ]]; then
```

2022-03-04 09:32 UTC, miguelaeh commented on bitnami/redis/templates/health-configmap.yaml
> +    if [ "$?" -eq "124" ]; then
```suggestion
    if [[ "$?" -eq "124" ]]; then
```

2022-03-04 09:32 UTC, miguelaeh commented on bitnami/redis/templates/health-configmap.yaml
> +    if [ "$?" -eq "124" ]; then
```suggestion
    if [[ "$?" -eq "124" ]]; then
```

2022-03-04 09:32 UTC, miguelaeh commented on bitnami/redis/templates/health-configmap.yaml
> +    if [ "$?" -eq "124" ]; then
```suggestion
    if [[ "$?" -eq "124" ]]; then
```

2022-03-04 09:38 UTC, migruiz4 commented
@miguelaeh Could you please provide more context on your change request?

I think the standard POSIX `[` is fine to check a number matches another.

2022-03-09 08:27 UTC, miguelaeh approved these changes
LGTM

2022-03-09 08:56 UTC, merged