[bitnami/redis-cluster] Fix readiness/liveness scripts typo
bitnami/charts pull request #9350
Opened 2022-03-09 12:41 UTC by kvendingoldo

2022-03-09 12:47 UTC, kvendingoldo commented
let me rewrite this script a little bit, 10 minutes

2022-03-09 18:26 UTC, kvendingoldo commented
@miguelaeh can you check it, pls?

2022-03-10 11:24 UTC, kvendingoldo commented
@rafariossaa @juan131 can you check it too, please?

2022-03-11 08:21 UTC, rafariossaa commented
@kvendingoldo ,
   Could you take a look to what I indicated ?

2022-03-11 21:04 UTC, kvendingoldo commented
@rafariossaa sorry, where?

2022-03-15 08:45 UTC, migruiz4 requested changes
Hi @kvendingoldo,

Please take a look at my comments below. Some linting issues plus `set -e` being removed.

In addition, readiness and liveness probes `exec` continue using `sh`.

2022-03-15 08:45 UTC, migruiz4 commented on bitnami/redis-cluster/templates/scripts-configmap.yaml
> +        {{- end }}
Please fix indentation. Args `--cert` and `--key` have two additional whitespaces.

2022-03-15 08:45 UTC, migruiz4 commented on bitnami/redis-cluster/templates/scripts-configmap.yaml
>    {{- end }}
Please fix indentation, arguments  should be in line with `-h localhost`

2022-03-15 08:45 UTC, migruiz4 commented on bitnami/redis-cluster/templates/scripts-configmap.yaml
> +        {{- end }}
Same here, please fix indentation.

2022-04-06 01:31 UTC, closed without merging