[bitnami/redis] Add possibility to set annotations for secret only
bitnami/charts pull request #9363
Opened 2022-03-09 18:23 UTC by jmc171144

**Description of the change**

These changes should allow annotations to be added to the redis secret only.

My use case is that I want to use [kubernetes reflector](https://github.com/emberstack/kubernetes-reflector#:~:text=Reflector%20is%20a%20Kubernetes%20addon,the%20same%20or%20other%20namespaces.) to reflect the `redis` secret on an other kubernetes namespace. 

I tried to use `commonAnnotations` to add the reflector annotations to the secret, it works the secret is well reflected but redis nodes are failing. 

It's how I would use it:

```
secretAnnotations:
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "passerelle-mobilisation"
```

**Benefits**

Allow to add annotations on secret only.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-03-15 08:41 UTC, alemorcuq requested changes
Great, thanks for the PR! LGTM, but please increase the version in a minor.

2022-03-15 08:41 UTC, alemorcuq commented on bitnami/redis/Chart.yaml
> +version: 16.5.3
```suggestion
version: 16.6.0
```

2022-03-15 10:21 UTC, jmc171144 commented
ok @alemorcuq thanks, I did it

2022-03-21 12:20 UTC, alemorcuq commented
There's some issue with the CI plus some conflicts here, can you rebase the PR?

2022-03-23 17:37 UTC, jmc171144 commented
@alemorcuq done

2022-03-28 09:01 UTC, jmc171144 commented
@alemorcuq done!

2022-03-28 09:02 UTC, alemorcuq approved these changes
Thanks. Everything looks good to me, let's see if the CI is able to run now.

2022-03-28 10:08 UTC, jmc171144 commented
Thanks! everything looks green now

2022-03-28 10:08 UTC, merged