[bitnami/redis-cluster] fix typo
bitnami/charts pull request #9424
Opened 2022-03-16 02:58 UTC by mamil

**Description of the change**
clean unnecessary blank and fix typo

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-03-16 08:46 UTC, alemorcuq commented
Thanks. Please, check the DCO for this commit.

2022-03-17 06:03 UTC, mamil commented
@alemorcuq done.

2022-03-18 15:50 UTC, alemorcuq requested changes
Thanks for the fix. Please, check my comment.

2022-03-18 15:50 UTC, alemorcuq commented on bitnami/redis-cluster/Chart.yaml
> +appVersion: 6.2.7
You should increase `version`, not `appVersion`.

2022-03-21 12:01 UTC, mamil commented
@alemorcuq thanks for your check, it's done again.

2022-03-21 12:15 UTC, alemorcuq approved these changes

2022-03-21 12:16 UTC, merged