[bitnami/ghost] Add subPath for the ghost-data volume
bitnami/charts pull request #9496
Opened 2022-03-21 09:18 UTC by longkai

Signed-off-by: longkai <im.longkai@gmail.com>

**Description of the change**

Allow user to specify `subPath` of ghost data volume.

**Benefits**

If the data volume comes from a nfs persistent volume(the user restores from a backup), it often takes another folder, thus providing a `subPath` is rational.

**Possible drawbacks**

No.

**Applicable issues**

No.

**Additional information**

No.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-03-21 09:25 UTC, carrodher commented
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

2022-03-21 10:10 UTC, longkai commented
The commit already got signed. Did something go wrong?

2022-03-22 09:39 UTC, miguelaeh submitted a review, later dismissed
thanks for the PR, please take a look at the comments.

2022-03-22 09:39 UTC, miguelaeh commented on bitnami/ghost/Chart.yaml
> +version: 16.2.3
Bump the minor version instead since you are adding a new feature.
```suggestion
version: 16.3.0
```

2022-03-22 09:39 UTC, miguelaeh commented on bitnami/ghost/README.md
> +| `persistence.existingMountSubPath`                   | The name of an existing volume's sub path to mount for persistence                                              | `""`                    |
Please use the ReadmeGenerator to update this: https://github.com/bitnami-labs/readme-generator-for-helm

2022-03-22 09:39 UTC, miguelaeh commented on bitnami/ghost/templates/deployment.yaml
> +              {{- if .Values.persistence.enabled }}
```suggestion
              {{- if .Values.persistence.existingMountSubPath }}
```

2022-03-22 09:39 UTC, miguelaeh commented on bitnami/ghost/templates/deployment.yaml
> +            {{- if .Values.persistence.enabled }}
```suggestion
            {{- if .Values.persistence.existingMountSubPath }}
```

2022-03-23 15:40 UTC, longkai commented
Done. Thanks for the nice review.

2022-03-24 12:10 UTC, migruiz4 requested changes
Hi @longkai,

Could you please rename the value `persistence.existingMountSubPath` as `persistence.subPath`?

This value exists in other charts in our catalog and we try to keep the names of the values unified to improve user experience, e.g. Redis, MariaDB, PostgreSQL, MongoDB.

2022-03-24 15:22 UTC, longkai commented
> Hi @longkai,
> 
> Could you please rename the value `persistence.existingMountSubPath` as `persistence.subPath`?
> 
> This value exists in other charts in our catalog and we try to keep the names of the values unified to improve user experience, e.g. Redis, MariaDB, PostgreSQL, MongoDB.

Done. It's better now.

2022-03-25 07:37 UTC, migruiz4 approved these changes
Thank you very much for applying the suggestions! Looks good to me!

2022-03-25 07:41 UTC, merged