[bitnami/harbor] Add configurable session timeout to harbor
bitnami/charts pull request #9583
Opened 2022-03-25 19:12 UTC by holzman

* [bitnami/harbor] Add configurable session timeout to harbor

The beego backend for harbor has a short (3600s) session timeout by
default, which can be too short for frequent users.  This adds a
configurable core.sessionTimeout value.

Signed-off-by: Burt Holzman <burt@fnal.gov>

* [bitnami/harbor] Rerender README on master

Signed-off-by: Burt Holzman <burt@fnal.gov>

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-03-28 08:48 UTC, miguelaeh requested changes
thanks for the PR!

2022-03-28 08:48 UTC, miguelaeh commented on bitnami/harbor/values.yaml
> +  ## sessionLifetime: 86400
```suggestion
  ##
```

2022-03-28 08:48 UTC, miguelaeh commented on bitnami/harbor/Chart.yaml
> +version: 12.2.3
```suggestion
version: 12.3.0
```

2022-03-28 14:41 UTC, holzman commented on bitnami/harbor/Chart.yaml
> +version: 12.2.3
ok

2022-03-31 19:23 UTC, holzman commented
Trivy scan seems to be timing out across the board (https://github.com/bitnami/charts/pulls?q=is%3Apr+is%3Aopen+harbor)

2022-04-07 10:00 UTC, miguelaeh approved these changes
LGTM

2022-04-08 08:42 UTC, miguelaeh commented
Could you please solve the conflicts, I am not sure if the jobs got stuck of they don't start because of the conflict

2022-04-08 14:10 UTC, holzman commented
Rebased, conflicts resolved.

2022-04-11 08:40 UTC, miguelaeh approved these changes

2022-04-11 08:56 UTC, merged