Add behindSslProxy flag
bitnami/charts pull request #9584
Opened 2022-03-25 19:48 UTC by roberto-civitas

Fixes #9582 

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-03-28 09:16 UTC, alemorcuq requested changes
Thanks for the PR! I'm not sure about the `behindSslProxy` parameter, I think it's not obvious what it does from the name. What do you think about adding a `targetPorts` parameter than can be configured? Other charts, like `bitnami/nginx-ingress-controller` use it. Could you take a look?

Also, please check the DCO, increase the chart version and add the new parameter to the README.md. Thanks!

2022-04-01 09:08 UTC, alemorcuq requested changes
Please, add the new parameters to the README and increase the chart version in a minor.

2022-04-04 17:53 UTC, paul-civitas commented
@alemorcuq how does it look now? Seems all checks now pass.

2022-04-04 17:56 UTC, paul-civitas requested changes

2022-04-04 17:56 UTC, paul-civitas commented on bitnami/contour/values.yaml
> +      http: http
Shouldn't these be numerical values?

2022-04-04 17:59 UTC, paul-civitas commented
@roberto-civitas 

Could you check over this again I don't think this is doing what you had in mind. Seems as it it would break existing deployments.

2022-04-04 18:23 UTC, paul-civitas commented
Oh I understand now. The "http" and "https" are references to the port definitions in the deployment spec here:

https://github.com/bitnami/charts/blob/master/bitnami/contour/templates/envoy/deployment.yaml#L178

And here:

https://github.com/bitnami/charts/blob/master/bitnami/contour/templates/envoy/deployment.yaml#L187

That's a brilliant solution. It didn't occur to me to do it that way.

2022-04-04 18:23 UTC, paul-civitas commented on bitnami/contour/values.yaml
> +      http: http
Nevermind! See: https://github.com/bitnami/charts/pull/9584#issuecomment-1087872902

2022-04-06 11:25 UTC, alemorcuq approved these changes
Thanks!

2022-04-06 11:25 UTC, merged