[bitnami/rabbitmq] Allow both definitions and setting credentials
bitnami/charts pull request #9638
Opened 2022-03-31 09:45 UTC by javsalgar

Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>

**Description of the change**

Up until now, the load definitions and the RabbitMQ credentials were incompatible. In the latest revision of the container we will allow setting both elements. If the "users" section inside the loadDefinitions file is set, then the credentials will be ignored.

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes https://github.com/bitnami/charts/issues/5976

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-03-31 09:56 UTC, migruiz4 requested changes
LGTM! Just a small suggestion to reduce the template logic

2022-03-31 09:56 UTC, migruiz4 commented on bitnami/rabbitmq/templates/statefulset.yaml
> +            {{- end }}
```suggestion
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: {{ ternary "yes" "no" .Values.loadDefinition.enabled | quote }}
            - name: RABBITMQ_DEFINITIONS_FILE
              value: {{ .Values.loadDefinition.file | quote }}
```

2022-03-31 10:46 UTC, migruiz4 approved these changes
LGTM!

2022-03-31 15:06 UTC, migruiz4 approved these changes

2022-04-01 09:41 UTC, merged

2022-04-01 11:11 UTC, javsalgar commented
Hi! 

We just released a new revision of the chart. Now, in case there is a definition WITHOUT the `users` section, it will set the credentials in the chart secret. If the `users` section is set, the credentials will be ignored.

I think this should cover your use case! :D