Remove nginx-ldap-auth-daemon dependency for Bitnami Nginx Intel Chart
bitnami/charts pull request #9647
Opened 2022-03-31 16:14 UTC by mdhont

Signed-off-by: michield <michield@vmware.com>

Description of the change

Remove nginx-ldap-auth-daemon dependency from Bitnami Nginx-intel Chart.

2022-04-01 08:01 UTC, carrodher reviewed
I would add a note in the Upgrade section describing what is the reason behind a major version bump. Since this is a new chart, probably you will need to create the whole section. You can check https://github.com/bitnami/charts/tree/master/bitnami/nginx#upgrading as example

2022-04-01 11:25 UTC, carrodher approved these changes
LGTM

2022-04-01 12:05 UTC, joancafom requested changes
Great PR! I added a couple of comments, could you please review them?

2022-04-01 12:05 UTC, joancafom commented on bitnami/nginx-intel/templates/deployment.yaml
>                mountPath: /opt/bitnami/nginx/conf/server_blocks
The `nginx-server-block-paths` was introduced as a consequence of LDAP addition. This means that it should also be removed and update the logic accordingly.

Refer to https://github.com/bitnami/charts/pull/2608/files#r427295257 for further details.

2022-04-01 12:05 UTC, joancafom commented on bitnami/nginx-intel/templates/server-block-configmap.yaml
>      include  "/opt/bitnami/nginx/conf/server_blocks/common/*.conf";
This should be removed

2022-04-04 14:53 UTC, joancafom submitted a review, later dismissed
LGTM!

2022-04-05 08:19 UTC, merged