[bitnami/odoo] Expose longpolling port
bitnami/charts pull request #9681
Opened 2022-04-04 13:56 UTC by kafai-lam

Signed-off-by: fai <lamkafai1997@gmail.com>

**Description of the change**

- pod: expose longpolling port, default to be `8072`
- service: expose longpolling service port
- ingress: redirect requests starts with `/longpolling/` to the longpolling service port

**Benefits**

According to Odoo documentation, [Live Chat related feature require extra longpolling config](https://www.odoo.com/documentation/15.0/administration/install/deploy.html#livechat)

**Possible drawbacks**

Extra service port and ingress rule were introduced

**Applicable issues**

- fixes #3097

**Additional information**

- N/a

**Checklist**
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-04-05 13:55 UTC, alemorcuq requested changes
Thanks for the PR, please check my comments.

2022-04-05 13:55 UTC, alemorcuq commented on bitnami/odoo/templates/deployment.yaml
> +              containerPort: {{ coalesce .Values.containerPorts.longpolling .Values.containerPort }}
I don't think this coalesce makes sense as the port must be different from the default port. I would do something like:

```
{{- if .Values.containerPorts.longpolling }}
- name: longpolling
  containerPort: {{ .Values.containerPorts.longpolling }}
{{- end }}
```

2022-04-05 13:55 UTC, alemorcuq commented on bitnami/odoo/templates/svc.yaml
> +      {{- end }}
Same comment here regarding `coalesce`. I would only add the service if there's a service and container port for longpolling.

2022-04-05 13:55 UTC, alemorcuq commented on bitnami/odoo/templates/ingress.yaml
> +            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "longpolling" "context" $)  | nindent 14 }}
This is being added inside a range for extraHosts, so it won't work as you expect. I think this `/longpolling/` path should be added to the previous host section.

2022-04-05 13:55 UTC, alemorcuq commented on bitnami/odoo/Chart.yaml
> +version: 21.2.6
The version should be a new minor.

2022-04-05 15:19 UTC, kafai-lam commented
@alemorcuq thanks for those comments. just fixed that commit. plz review

2022-04-11 09:01 UTC, alemorcuq commented on bitnami/odoo/templates/ingress.yaml
> +          - path: /longpolling/
What if Odoo is not intended to be accessed on `/` but on `/odoo`? I imagine the intended path would be `/odoo/longpolling`, right?

2022-05-03 01:31 UTC, closed without merging