[bitnami/magento] Chart standardised + Bump dependencies
bitnami/charts pull request #9710
Opened 2022-04-06 15:05 UTC by migruiz4

Signed-off-by: Miguel Ruiz <miruiz@vmware.com>

**Description of the change**

This PR standardizes the bitnami/magento chart to be in line with the rest of the catalog and updates its dependencies.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-04-11 09:17 UTC, fmulero requested changes
Hi @migruiz4, Please have a look to the following comments

2022-04-11 09:17 UTC, fmulero commented on bitnami/magento/templates/pv.yaml
> +    {{- end }}  capacity:
```suggestion
    {{- end }}
  capacity:
```

2022-04-11 09:17 UTC, fmulero commented on bitnami/magento/README.md
> +
We should add that  `persistence.accessMode` is now a list

2022-04-12 16:31 UTC, fmulero submitted a review, later dismissed
LGTM

2022-04-30 08:45 UTC, carrodher commented on bitnami/magento/Chart.yaml
> +    version: 10.x.x
Please note there is a new major in the database, see https://github.com/bitnami/charts/pull/9827
```suggestion
    version: 11.x.x
```

2022-05-05 09:13 UTC, fmulero approved these changes
👍

2022-05-05 09:57 UTC, fmulero approved these changes
Good Catch!

2022-05-05 17:08 UTC, carrodher submitted a review, later dismissed

2022-05-05 17:08 UTC, carrodher commented on bitnami/magento/README.md
> +Check [Elasticsearch Upgrading Notes](https://github.com/bitnami/charts/tree/master/bitnami/redis#to-1800) and [Redis Upgrading Notes](https://github.com/bitnami/charts/tree/master/bitnami/mariadb#to
```suggestion
Check [Elasticsearch Upgrading Notes](https://github.com/bitnami/charts/tree/master/bitnami/redis#to-1800) and [MariaDB Upgrading Notes](https://github.com/bitnami/charts/tree/master/bitnami/mariadb#to-1000) for more information.
```

2022-05-05 17:10 UTC, carrodher submitted a review, later dismissed

2022-05-09 09:20 UTC, merged