[bitnami/rabbitmq] Chart standardised
bitnami/charts pull request #9817
Opened 2022-04-18 15:29 UTC by migruiz4

**Description of the change**

This PR standardizes the bitnami/rabbitmq chart to be in line with the rest of the catalog.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-04-20 17:13 UTC, FraPazGal requested changes
Thanks for the PR! Please take a look at my comments

2022-04-26 16:17 UTC, migruiz4 commented on bitnami/rabbitmq/README.md
> +- `service.port` has been renamed as ``.
Done, thanks!

2022-04-26 16:18 UTC, migruiz4 commented on bitnami/rabbitmq/templates/configuration.yaml
> +  name: {{ printf "%s-config" (include "rabbitmq.fullname" .) }}
Removed `rabbitmq.fullname` and `rabbitmq.name` helpers

2022-04-27 16:51 UTC, FraPazGal approved these changes
LGTM!

2022-04-28 17:10 UTC, merged