[bitnami/postgresql]Feature/add read exetended config
bitnami/charts pull request #9866
Opened 2022-04-21 13:50 UTC by ajammali

**Description of the change**
Allow the support for extended configuration to the read replication.

**Benefits**
Add the ability to customize the PostgreSQL configuration file on the read replica.

**Possible drawbacks**
This still can't ensure that main configuration of the primary and read replicas is the same, which makes it impossible for the read to replace primary.

**Applicable issues**

  - fixes #9472

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-04-25 08:58 UTC, miguelaeh requested changes
Thanks for the PR!
I added some comments.
Also, I think it is confusing to use both `readReplica` and `readReplicas`, I suggest to use always the same to avoid confusion

2022-04-25 08:58 UTC, miguelaeh commented on bitnami/postgresql/Chart.yaml
> +version: 11.1.23
```suggestion
version: 11.2.0
```

2022-04-25 08:58 UTC, miguelaeh commented on bitnami/postgresql/templates/_helpers.tpl
> +{{- printf "%s-hl" (include "postgresql.readReplicas.fullname" .) | trunc 63 | trimSuffix "-" }}
```suggestion
{{- printf "%s-hl" (include "postgresql.readReplica.fullname" .) | trunc 63 | trimSuffix "-" }}
```

2022-04-25 08:58 UTC, miguelaeh commented on bitnami/postgresql/templates/_helpers.tpl
> +{{- printf "%s-hl" (include "postgresql.readReplicas.fullname" .) | trunc 63 | trimSuffix "-" }}
Seems that it was correct before the change, the function is called `readReplica`

2022-04-25 08:58 UTC, miguelaeh commented on bitnami/postgresql/templates/_helpers.tpl
> +{{- else -}}
```suggestion
```

2022-04-25 09:56 UTC, ajammali commented
Thanks for the feedback.
I resolved the comments.

2022-04-27 10:22 UTC, miguelaeh reviewed
Please resolve the conflicts by rebasing master, I added the `verify` label so the actions are run.

2022-04-27 10:47 UTC, ajammali commented
I think after rebasing master it all got messed up
if there is a way to correct this from your end or you can ignore this PR and you add the missing config your selves

2022-04-29 08:40 UTC, miguelaeh commented
You can move between the local git states using `git reflog` to reset the branch to the commit before the rebase. 

After that simply checking out to master, making a pull to update master, and then checking out to your branch and rebasing should not cause problems unless your fork has other changes.

2022-04-29 11:43 UTC, ajammali commented
> You can move between the local git states using `git reflog` to reset the branch to the commit before the rebase.
> 
> After that simply checking out to master, making a pull to update master, and then checking out to your branch and rebasing should not cause problems unless your fork has other changes.

the remote fork already has other changes from rebase. I'm not sure if it's a good idea to just delete the PR and start the whole thing all over

2022-05-05 07:48 UTC, rafariossaa commented
I guess yes, that would be a better approach. 
Refer to this PR when you create the new one.

2022-05-12 07:27 UTC, ajammali commented
I created a new PR #10165 to replace this one.

2022-05-12 14:44 UTC, closed without merging