[bitnami/parse] Parse standarization
bitnami/charts pull request #9867
Opened 2022-04-21 14:10 UTC by fmulero

Signed-off-by: Fran Mulero <fmulero@vmware.com>

**Description of the change**

This PR updates mongodb dependency and applies standardisation changes to be in line with the rest of the catalog.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-04-21 15:37 UTC, FraPazGal requested changes
I added some suggestions and a couple of concerns, please take a look at them.

Additionally, regarding the use of a new MongoDB major, we need to update the `mongodb.persistence.accessMode` param as it is now `mongodb.persistence.accessModes` and uses a different format.

2022-04-21 15:37 UTC, FraPazGal commented on bitnami/parse/templates/ingress.yaml
> +            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "http-dahsboard" "context" $)  | nindent 14 }}
```suggestion
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "http-dashboard" "context" $)  | nindent 14 }}
```

2022-04-21 15:39 UTC, FraPazGal commented
Please take into account the need to update parse's [vib pipeline](https://github.com/bitnami/charts/blob/master/.vib/parse/vib-verify.json) as you changed the `service.port` definition. You may need to rebase from master to have said fail in your branch.

2022-04-25 09:27 UTC, fmulero commented on bitnami/parse/values.yaml
> +    enabled: true
I left it as `true` during my tests

2022-04-25 09:40 UTC, fmulero commented on bitnami/parse/values.yaml
> +  replicaCount: 1
No issues detected (at the moment). `sessionAffinity` needs to be configured to allow using multiple dashboard replicas properly

2022-04-29 11:45 UTC, migruiz4 requested changes
Two minor changes requested, apart from that looks good to me

2022-04-29 11:45 UTC, migruiz4 commented on bitnami/parse/Chart.yaml
> +    version: ">=11, <=12"
```suggestion
    version: "12.x.x"
```

2022-04-29 11:45 UTC, migruiz4 commented on bitnami/parse/README.md
> +- `service.port` is renamed to `service.ports.mongodb`
This is a typo, it should be `service.ports.http`, right?

2022-05-03 10:32 UTC, migruiz4 submitted a review, later dismissed
LGTM

2022-05-03 16:22 UTC, migruiz4 requested changes
Overall looks good to me, just a typo in the README.md

2022-05-03 16:22 UTC, migruiz4 commented on bitnami/parse/README.md
> +- `service.nodePort` is renamed to `service.dashboard.nodePorts.http`
Here you mention `service.dashboard.*`, but the value is `dashboard.service` if I'm not mistaken.

2022-05-03 17:19 UTC, migruiz4 approved these changes
LGTM!

2022-05-04 07:33 UTC, migruiz4 submitted a review, later dismissed

2022-05-04 07:33 UTC, migruiz4 approved these changes

2022-05-04 08:48 UTC, merged