[bitnami/postgresql] Add metrics support to read replica
bitnami/charts pull request #9881
Opened 2022-04-22 08:33 UTC by ajammali

Signed-off-by: Anouar Jammali <jammali.anouar@gmail.com>

**Description of the change**
Add the following to the read replica templates:

> Metrics sidecar to read statefulset.
> Metrics configmap for read replica.
> ServiceMonitor for read replica.
> PrometheusRule CRD for both read and primary replicas to avoid double alerting rules.

**Benefits**

Generate metrics for the read replication.

**Possible drawbacks**

**Applicable issues**

  - fixes #9869 

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-04-25 15:04 UTC, dgomezleon requested changes
Thanks a lot for contributing. I have just required some minor changes.

2022-05-12 14:53 UTC, ajammali commented on bitnami/postgresql/templates/prometheusrule.yaml
> +  namespace: {{ default .Release.Namespace .Values.metrics.prometheusRule.namespace }}
checked

2022-05-12 14:53 UTC, ajammali commented on bitnami/postgresql/templates/read/servicemonitor.yaml
> +  namespace: {{ default .Release.Namespace .Values.metrics.serviceMonitor.namespace }}
checked

2022-05-12 14:53 UTC, ajammali commented on bitnami/postgresql/templates/read/servicemonitor.yaml
> +      - {{ .Release.Namespace }}
checked

2022-05-12 14:53 UTC, ajammali commented on bitnami/postgresql/templates/read/metrics-configmap.yaml
> +  namespace: {{ .Release.Namespace }}
checked

2022-05-13 07:08 UTC, dgomezleon commented on bitnami/postgresql/templates/read/metrics-configmap.yaml
> +  namespace: {{ .Release.Namespace }}
It seems you missed this one.

2022-05-13 08:24 UTC, rafariossaa commented
Also, take a look to the conflict in `Chart.yaml`

2022-05-13 09:23 UTC, ajammali commented on bitnami/postgresql/templates/read/metrics-configmap.yaml
> +  namespace: {{ .Release.Namespace }}
done

2022-05-13 16:34 UTC, dgomezleon approved these changes
LGTM

2022-05-13 16:34 UTC, merged